-- chromawash: Chroma Wash
-- Proc amp, chroma H blur, 2-line V blur, chroma posterize; V-channel key against a palette. P12 fades to the source.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/chromawash.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   k1         control       1 ->   2
--   k2         control       1 ->   2
--   k3         control       1 ->   2
--   k4         control       1 ->   2
--   k5         control       1 ->   2
--   k6         control       1 ->   2
--   kglide     glide         1 ->   2
--   p12        control       1 ->   2
--   glide      glide         1 ->   2
--   pa         procamp       1 ->   6
--   hb         hblur         6 ->  13
--   vb         vblur        13 ->  20  (2-line colour average: 15 EBR)
--   key        threshold    20 ->  23  (keys on V (red-difference) of the processed picture)
--   post       posterize    20 ->  21
--   pal        colorizer    23 ->  25
--   keymix     mix          25 ->  29  (per-pixel key: amount is the threshold mask)
--   wetmix     mix          29 ->  33
--   vout       video_out    33 ->  34
-- Program latency: 34 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   post.out         34-bit, delayed by 2 / 4 clocks (136 FF)
--   key.mask         10-bit, delayed by 2 clocks (20 FF)
--   vin.out          34-bit, delayed by 28 clocks (952 FF)
-- Chroma of key is never consumed downstream; synthesis removes it.
-- Controls:
--   K1   registers_in(0)     Bright
--   K2   registers_in(1)     Contrast
--   K3   registers_in(2)     Saturation
--   K4   registers_in(3)     Key Level
--   K5   registers_in(4)     Key Soft
--   K6   registers_in(5)     Key Amount
--   P12  registers_in(7)     Dry/Wet
-- Estimate: 5918 LC (77.1 %), 15 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture chromawash of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_k1_value             : unsigned(10 - 1 downto 0);
  signal s_k2_value             : unsigned(10 - 1 downto 0);
  signal s_k3_value             : unsigned(10 - 1 downto 0);
  signal s_k4_value             : unsigned(10 - 1 downto 0);
  signal s_k5_value             : unsigned(10 - 1 downto 0);
  signal s_k6_value             : unsigned(10 - 1 downto 0);
  signal s_kglide_value         : unsigned(10 - 1 downto 0);
  signal s_p12_value            : unsigned(10 - 1 downto 0);
  signal s_glide_value          : unsigned(10 - 1 downto 0);
  signal s_pa_out               : t_vm_stream;
  signal s_hb_out               : t_vm_stream;
  signal s_vb_out               : t_vm_stream;
  signal s_key_out              : t_vm_stream;
  signal s_key_mask             : unsigned(10 - 1 downto 0);
  signal s_post_out             : t_vm_stream;
  signal s_pal_out              : t_vm_stream;
  signal s_keymix_out           : t_vm_stream;
  signal s_wetmix_out           : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_post_out_d2          : t_vm_stream;
  signal s_post_out_d4          : t_vm_stream;
  signal s_key_mask_d2          : unsigned(10 - 1 downto 0);
  signal s_vin_out_d28          : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- k1 (K1: Bright)
  u_k1 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0), o_value => s_k1_value);

  -- k2 (K2: Contrast)
  u_k2 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1), o_value => s_k2_value);

  -- k3 (K3: Saturation)
  u_k3 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2), o_value => s_k3_value);

  -- k4 (K4: Key Level)
  u_k4 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3), o_value => s_k4_value);

  -- k5 (K5: Key Soft)
  u_k5 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(4), o_value => s_k5_value);

  -- k6 (K6: Key Amount)
  u_k6 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(5), o_value => s_k6_value);

  -- kglide (Glide)
  u_kglide : entity work.vm_glide
    generic map (G_SHIFT => 2)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_k6_value,
              o_value => s_kglide_value);

  -- p12 (P12: Dry/Wet)
  u_p12 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(7),
              o_value => s_p12_value);

  -- glide (Glide)
  u_glide : entity work.vm_glide
    generic map (G_SHIFT => 2)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_p12_value,
              o_value => s_glide_value);

  -- pa (Proc Amp)
  u_pa : entity work.vm_procamp
    generic map (G_IMPL => "shift", G_BITS => 5)
    port map (clk => clk, i_stream => s_vin_out, i_bright => s_k1_value,
              i_contrast => s_k2_value, i_sat => s_k3_value, o_stream => s_pa_out);

  -- hb (H Blur)
  u_hb : entity work.vm_hblur
    generic map (G_TAPS => 5, G_CHROMA => true)
    port map (clk => clk, i_stream => s_pa_out, o_stream => s_hb_out);

  -- vb (V Blur): 2-line colour average: 15 EBR
  u_vb : entity work.vm_vblur
    generic map (G_TAPS => 2, G_CHROMA => true, G_DEPTH_BITS => 11)
    port map (clk => clk, i_stream => s_hb_out, o_stream => s_vb_out);

  -- key (Threshold): keys on V (red-difference) of the processed picture
  u_key : entity work.vm_threshold
    generic map (G_CHANNEL => 2, G_SOFT => true)
    port map (clk => clk, i_stream => s_vb_out, i_level => s_k4_value, i_soft => s_k5_value,
              o_stream => s_key_out, o_mask => s_key_mask);

  -- post (Posterize)
  u_post : entity work.vm_posterize
    generic map (G_BITS => 4, G_CHROMA => true)
    port map (clk => clk, i_stream => s_vb_out, o_stream => s_post_out);
  u_dly_post_out_2 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_post_out, o_stream => s_post_out_d2);
  u_dly_post_out_4 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_post_out_d2, o_stream => s_post_out_d4);

  -- pal (Colorizer)
  u_pal : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 2, G_PALETTE => "07c30d1d41722b23602ae0992b93ac200200")
    port map (clk => clk, i_stream => s_post_out_d2, i_index => s_key_mask,
              o_stream => s_pal_out);
  u_dly_key_mask_2 : entity work.vm_delay_scalar generic map (G_WIDTH => 10, G_DELAY => 2)
    port map (clk => clk, i_value => s_key_mask, o_value => s_key_mask_d2);

  -- keymix (Mix): per-pixel key: amount is the threshold mask
  u_keymix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 6)
    port map (clk => clk, i_a => s_post_out_d4, i_b => s_pal_out, i_amount => s_key_mask_d2,
              o_stream => s_keymix_out);
  u_dly_vin_out_28 : entity work.vm_delay_stream generic map (G_DELAY => 28)
    port map (clk => clk, i_stream => s_vin_out, o_stream => s_vin_out_d28);

  -- wetmix (Mix)
  u_wetmix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 4)
    port map (clk => clk, i_a => s_vin_out_d28, i_b => s_keymix_out, i_amount => s_glide_value,
              o_stream => s_wetmix_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_wetmix_out, o_data => data_out);
end architecture chromawash;
