-- Auto-generated by build_face_mesh.py.  Edit face_mesh.py, not this file.
-- Edges: 51
--   group 0 (STATIC): 22 edges
--   group 1 (BROW): 4 edges
--   group 2 (EYE): 16 edges
--   group 3 (MOUTH): 9 edges

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package bishop_mesh_pkg is

    constant C_NUM_EDGES : natural := 51;

    constant C_GRP_STATIC : natural := 0;
    constant C_GRP_BROW   : natural := 1;
    constant C_GRP_EYE    : natural := 2;
    constant C_GRP_MOUTH  : natural := 3;

    type t_int_array is array (natural range <>) of integer;

    -- y_min per edge
    constant C_EDGE_Y_MIN : t_int_array(0 to C_NUM_EDGES - 1) := (
         -298,  -249,  -106,    27,   195,   300,   195,    27,
         -106,  -249,  -298,  -108,  -108,  -108,  -108,   -48,
          -48,   -40,   -40,   -48,   -48,   -40,   -40,   -55,
          -55,   108,   108,   108,   149,   149,   154,   154,
          154,  -300,  -300,   -50,   -50,   -31,   -31,   -50,
          -50,   -31,   -31,   -70,   -70,   127,   127,   147,
          147,   173,   173
    );

    -- y_max per edge
    constant C_EDGE_Y_MAX : t_int_array(0 to C_NUM_EDGES - 1) := (
         -249,  -106,    27,   195,   300,   300,   300,   195,
           27,  -106,  -249,   -91,   -91,   -91,   -91,   -40,
          -40,   -32,   -32,   -40,   -40,   -32,   -32,   108,
          108,   126,   126,   108,   154,   154,   172,   172,
          154,  -299,  -299,   -49,   -49,   -30,   -30,   -49,
          -49,   -30,   -30,   -56,   -56,   129,   129,   148,
          148,   174,   174
    );

    -- x at y_min, Q9.7 (128x pixels)
    constant C_EDGE_X_TOP : t_int_array(0 to C_NUM_EDGES - 1) := (
         -666, -16980, -22465, -20637, -13714, -5224, 13714, 20637,
        22465, 16980,   666, -9796, -9796,  9796,  9796, -10710,
        -8752, -4571, -14367,  8752, 10710, 14367,  4571,  -270,
          270, -3265,  3265, -3265, -2240,  2240,  7837, -7837,
        -7837,     0,     0, -9796, -9796, -9269, -10254,  9796,
         9796, 10254,  9269,     0,     0,  -320,   320,     0,
            0,   389,  -389
    );

    -- slope dx/dy, Q9.7 (128x pixels/row)
    constant C_EDGE_SLOPE : t_int_array(0 to C_NUM_EDGES - 1) := (
         -333,   -38,    14,    41,    81, 10449,   -81,   -41,
          -14,    38,   333,  -423,   346,  -346,   423,  -457,
          522,  -522,   457,  -522,   457,  -457,   522,   -18,
           18,   155,  -155,  6531, -1120,  1120,  -392,   392,
        15673,  -333,   333,  -457,   522,  -522,   457,  -522,
          457,  -457,   522,   -18,    18,   155,  -155, -1120,
         1120,  -392,   392
    );

    -- animation group
    constant C_EDGE_GROUP : t_int_array(0 to C_NUM_EDGES - 1) := (
            0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     1,     1,     1,     1,     2,
            2,     2,     2,     2,     2,     2,     2,     0,
            0,     0,     0,     0,     3,     3,     3,     3,
            3,     0,     0,     2,     2,     2,     2,     2,
            2,     2,     2,     0,     0,     0,     0,     3,
            3,     3,     3
    );

    -- 1=boundary (EOR), 0=detail (visible only)
    constant C_EDGE_BND : t_int_array(0 to C_NUM_EDGES - 1) := (
            1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     0,     0,     0,     0,     1,
            1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     0,     1,     1,     1,     1,
            0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0
    );

end package bishop_mesh_pkg;
