-- Auto-generated by build_face_mesh.py.  Edit face_mesh.py, not this file.
-- Expressions (5): neutral, happy, sad, angry, surprised
-- Edges per expression (padded to max): 51

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package bishop_mesh_pkg is

    constant C_NUM_EDGES : natural := 51;
    constant C_NUM_EXPR  : natural := 5;

    constant C_GRP_STATIC : natural := 0;
    constant C_GRP_BROW   : natural := 1;
    constant C_GRP_EYE    : natural := 2;
    constant C_GRP_MOUTH  : natural := 3;

    constant C_EXPR_NEUTRAL : natural := 0;
    constant C_EXPR_HAPPY : natural := 1;
    constant C_EXPR_SAD : natural := 2;
    constant C_EXPR_ANGRY : natural := 3;
    constant C_EXPR_SURPRISED : natural := 4;

    type t_int_array is array (natural range <>) of integer;

    -- y_min — neutral
    constant C_EDGE_Y_MIN_0 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -297,   -249,   -106,     27,    195,    300,    195,     27,
          -106,   -249,   -297,   -108,   -108,   -108,   -108,    -47,
           -47,    -40,    -40,    -47,    -47,    -40,    -40,    -34,
           -34,    108,    108,    108,    149,    149,    154,    154,
           154,   -300,   -300,    -50,    -50,    -32,    -32,    -50,
           -50,    -32,    -32,    -70,    -70,    125,    125,    147,
           147,    172,    172
    );

    -- y_min — happy
    constant C_EDGE_Y_MIN_1 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -297,   -249,   -106,     27,    195,    300,    195,     27,
          -106,   -249,   -297,   -108,   -108,   -108,   -108,    -46,
           -46,    -40,    -42,    -46,    -46,    -42,    -40,    -36,
           -36,    106,    106,    106,    143,    143,    144,    144,
           144,   -300,   -300,    -48,    -48,    -36,    -36,    -48,
           -48,    -36,    -36,    -70,    -70,    124,    124,    141,
           141,    175,    175
    );

    -- y_min — sad
    constant C_EDGE_Y_MIN_2 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -297,   -249,   -106,     27,    195,    300,    195,     27,
          -106,   -249,   -297,   -110,   -110,   -110,   -110,    -44,
           -44,    -40,    -38,    -44,    -44,    -38,    -40,    -34,
           -34,    108,    108,    108,    148,    148,    164,    164,
           164,   -300,   -300,    -46,    -46,    -30,    -30,    -46,
           -46,    -30,    -30,    -70,    -70,    125,    125,    145,
           145,    169,    169
    );

    -- y_min — angry
    constant C_EDGE_Y_MIN_3 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -297,   -249,   -106,     27,    195,    300,    195,     27,
          -106,   -249,   -297,   -105,   -105,   -105,   -105,    -46,
           -46,    -40,    -40,    -46,    -46,    -40,    -40,    -31,
           -31,    105,    105,    105,    151,    151,    156,    156,
           156,   -300,   -300,    -48,    -48,    -33,    -33,    -48,
           -48,    -33,    -33,    -65,    -65,    122,    122,    149,
           149,    168,    168
    );

    -- y_min — surprised
    constant C_EDGE_Y_MIN_4 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -297,   -249,   -106,     27,    195,    300,    195,     27,
          -106,   -249,   -297,   -122,   -122,   -122,   -122,    -52,
           -52,    -40,    -40,    -52,    -52,    -40,    -40,    -34,
           -34,    108,    108,    108,    145,    145,    156,    156,
           156,   -300,   -300,    -55,    -55,    -28,    -28,    -55,
           -55,    -28,    -28,    -70,    -70,    125,    125,    142,
           142,    184,    184
    );

    -- y_max — neutral
    constant C_EDGE_Y_MAX_0 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -249,   -106,     27,    195,    300,    300,    300,    195,
            27,   -106,   -249,    -91,    -91,    -91,    -91,    -40,
           -40,    -33,    -33,    -40,    -40,    -33,    -33,    108,
           108,    124,    124,    108,    154,    154,    171,    171,
           154,   -298,   -298,    -48,    -48,    -30,    -30,    -48,
           -48,    -30,    -30,    -35,    -35,    129,    129,    148,
           148,    174,    174
    );

    -- y_max — happy
    constant C_EDGE_Y_MAX_1 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -249,   -106,     27,    195,    300,    300,    300,    195,
            27,   -106,   -249,    -91,    -91,    -91,    -91,    -42,
           -40,    -37,    -37,    -40,    -42,    -37,    -37,    106,
           106,    123,    123,    106,    144,    144,    174,    174,
           144,   -298,   -298,    -47,    -47,    -35,    -35,    -47,
           -47,    -35,    -35,    -37,    -37,    129,    129,    142,
           142,    178,    178
    );

    -- y_max — sad
    constant C_EDGE_Y_MAX_2 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -249,   -106,     27,    195,    300,    300,    300,    195,
            27,   -106,   -249,    -86,   -101,   -101,    -86,    -38,
           -40,    -31,    -31,    -40,    -38,    -31,    -31,    108,
           108,    124,    124,    108,    164,    164,    168,    168,
           164,   -298,   -298,    -45,    -45,    -28,    -28,    -45,
           -45,    -28,    -28,    -35,    -35,    129,    129,    147,
           147,    170,    170
    );

    -- y_max — angry
    constant C_EDGE_Y_MAX_3 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -249,   -106,     27,    195,    300,    300,    300,    195,
            27,   -106,   -249,    -99,    -81,    -81,    -99,    -40,
           -40,    -34,    -34,    -40,    -40,    -34,    -34,    105,
           105,    121,    121,    105,    156,    156,    167,    167,
           156,   -298,   -298,    -47,    -47,    -32,    -32,    -47,
           -47,    -32,    -32,    -32,    -32,    126,    126,    150,
           150,    170,    170
    );

    -- y_max — surprised
    constant C_EDGE_Y_MAX_4 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -249,   -106,     27,    195,    300,    300,    300,    195,
            27,   -106,   -249,   -102,   -102,   -102,   -102,    -40,
           -40,    -29,    -29,    -40,    -40,    -29,    -29,    108,
           108,    124,    124,    108,    156,    156,    183,    183,
           156,   -298,   -298,    -53,    -53,    -26,    -26,    -53,
           -53,    -26,    -26,    -35,    -35,    129,    129,    144,
           144,    187,    187
    );

    -- x at y_min, Q9.7 (128x px) — neutral
    constant C_EDGE_X_TOP_0 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -999, -16980, -22465, -20637, -13714,  -5224,  13714,  20637,
         22465,  16980,    999,  -9796,  -9796,   9796,   9796, -11167,
         -8230,  -4571, -14367,   8230,  11167,  14367,   4571,   -648,
           648,  -3265,   3265,  -3265,  -2240,   2240,   7837,  -7837,
         -7837,      0,      0,  -9796,  -9796,  -8747, -10711,   9796,
          9796,  10711,   8747,      0,      0,   -630,    630,      0,
             0,    781,   -781
    );

    -- x at y_min, Q9.7 (128x px) — happy
    constant C_EDGE_X_TOP_1 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -999, -16980, -22465, -20637, -13714,  -5224,  13714,  20637,
         22465,  16980,    999,  -9796,  -9796,   9796,   9796, -11320,
         -8490,  -4571, -14367,   8490,  11320,  14367,   4571,   -646,
           646,  -3265,   3265,  -3265,  -5922,   5922,   8882,  -8882,
         -8882,      0,      0,  -9796,  -9796,  -8751, -10449,   9796,
          9796,  10449,   8751,      0,      0,   -709,    709,      0,
             0,    791,   -791
    );

    -- x at y_min, Q9.7 (128x px) — sad
    constant C_EDGE_X_TOP_2 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -999, -16980, -22465, -20637, -13714,  -5224,  13714,  20637,
         22465,  16980,    999,  -9796,  -9796,   9796,   9796, -10938,
         -8054,  -4571, -14367,   8054,  10938,  14367,   4571,   -648,
           648,  -3265,   3265,  -3265,  -1176,   1176,   7445,  -7445,
         -7445,      0,      0,  -9796,  -9796,  -8921, -10711,   9796,
          9796,  10711,   8921,      0,      0,   -630,    630,      0,
             0,   1240,  -1240
    );

    -- x at y_min, Q9.7 (128x px) — angry
    constant C_EDGE_X_TOP_3 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -999, -16980, -22465, -20637, -13714,  -5224,  13714,  20637,
         22465,  16980,    999,  -9796,  -9796,   9796,   9796, -10874,
         -8424,  -4310, -14106,   8424,  10874,  14106,   4310,   -646,
           646,  -3265,   3265,  -3265,  -2240,   2240,   7837,  -7837,
         -7837,      0,      0,  -9796,  -9796,  -9112, -10333,   9796,
          9796,  10333,   9112,      0,      0,   -630,    630,      0,
             0,   1117,  -1117
    );

    -- x at y_min, Q9.7 (128x px) — surprised
    constant C_EDGE_X_TOP_4 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -999, -16980, -22465, -20637, -13714,  -5224,  13714,  20637,
         22465,  16980,    999,  -9796,  -9796,   9796,   9796, -10711,
         -8752,  -4571, -14367,   8752,  10711,  14367,   4571,   -648,
           648,  -3265,   3265,  -3265,  -1512,   1512,   7053,  -7053,
         -7053,      0,      0,  -9796,  -9796,  -9047, -10443,   9796,
          9796,  10443,   9047,      0,      0,   -630,    630,      0,
             0,    669,   -669
    );

    -- slope dx/dy, Q9.7 (128x px/row) — neutral
    constant C_EDGE_SLOPE_0 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -333,    -38,     14,     41,     81,  10449,    -81,    -41,
           -14,     38,    333,   -423,    346,   -346,    423,   -457,
           522,   -522,    457,   -522,    457,   -457,    522,    -18,
            18,    155,   -155,   6531,  -1120,   1120,   -392,    392,
         15673,   -333,    333,   -457,    522,   -522,    457,   -522,
           457,   -457,    522,    -18,     18,    155,   -155,  -1120,
          1120,   -392,    392
    );

    -- slope dx/dy, Q9.7 (128x px/row) — happy
    constant C_EDGE_SLOPE_1 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -333,    -38,     14,     41,     81,  10449,    -81,    -41,
           -14,     38,    333,   -423,    346,   -346,    423,   -762,
           653,  -1045,    653,   -653,    762,   -653,   1045,    -19,
            19,    142,   -142,   6531,  -2961,   2961,   -261,    261,
         17763,   -333,    333,   -762,    653,  -1045,    653,   -653,
           762,   -653,   1045,    -19,     19,    142,   -142,  -2961,
          2961,   -261,    261
    );

    -- slope dx/dy, Q9.7 (128x px/row) — sad
    constant C_EDGE_SLOPE_2 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -333,    -38,     14,     41,     81,  10449,    -81,    -41,
           -14,     38,    333,   -299,    697,   -697,    299,   -571,
           871,   -435,    457,   -871,    571,   -457,    435,    -18,
            18,    155,   -155,   6531,   -392,    392,  -1241,   1241,
         14890,   -333,    333,   -571,    871,   -435,    457,   -871,
           571,   -457,    435,    -18,     18,    155,   -155,   -392,
           392,  -1241,   1241
    );

    -- slope dx/dy, Q9.7 (128x px/row) — angry
    constant C_EDGE_SLOPE_3 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -333,    -38,     14,     41,     81,  10449,    -81,    -41,
           -14,     38,    333,  -1197,    261,   -261,   1197,   -539,
           686,   -686,    539,   -686,    539,   -539,    686,    -19,
            19,    155,   -155,   6531,  -1120,   1120,   -560,    560,
         15673,   -333,    333,   -539,    686,   -686,    539,   -686,
           539,   -539,    686,    -19,     19,    155,   -155,  -1120,
          1120,   -560,    560
    );

    -- slope dx/dy, Q9.7 (128x px/row) — surprised
    constant C_EDGE_SLOPE_4 : t_int_array(0 to C_NUM_EDGES - 1) := (
          -333,    -38,     14,     41,     81,  10449,    -81,    -41,
           -14,     38,    333,   -359,    294,   -294,    359,   -305,
           348,   -373,    327,   -348,    305,   -327,    373,    -18,
            18,    155,   -155,   6531,   -504,    504,   -228,    228,
         14106,   -333,    333,   -305,    348,   -373,    327,   -348,
           305,   -327,    373,    -18,     18,    155,   -155,   -504,
           504,   -228,    228
    );

    -- animation group per edge (expression-independent)
    constant C_EDGE_GROUP : t_int_array(0 to C_NUM_EDGES - 1) := (
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      1,      1,      1,      1,      2,
             2,      2,      2,      2,      2,      2,      2,      0,
             0,      0,      0,      0,      3,      3,      3,      3,
             3,      0,      0,      2,      2,      2,      2,      2,
             2,      2,      2,      0,      0,      0,      0,      3,
             3,      3,      3
    );

    -- 1=boundary (EOR), 0=detail/no-op (expression-independent)
    constant C_EDGE_BND : t_int_array(0 to C_NUM_EDGES - 1) := (
             1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      0,      0,      0,      0,      1,
             1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      0,      1,      1,      1,      1,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0
    );

    function f_y_min(expr, idx : natural) return integer;
    function f_y_max(expr, idx : natural) return integer;
    function f_x_top(expr, idx : natural) return integer;
    function f_slope(expr, idx : natural) return integer;

end package bishop_mesh_pkg;

package body bishop_mesh_pkg is

    function f_y_min(expr, idx : natural) return integer is
    begin
        case expr is
            when 0 => return C_EDGE_Y_MIN_0(idx);
            when 1 => return C_EDGE_Y_MIN_1(idx);
            when 2 => return C_EDGE_Y_MIN_2(idx);
            when 3 => return C_EDGE_Y_MIN_3(idx);
            when others => return C_EDGE_Y_MIN_4(idx);
        end case;
    end function;

    function f_y_max(expr, idx : natural) return integer is
    begin
        case expr is
            when 0 => return C_EDGE_Y_MAX_0(idx);
            when 1 => return C_EDGE_Y_MAX_1(idx);
            when 2 => return C_EDGE_Y_MAX_2(idx);
            when 3 => return C_EDGE_Y_MAX_3(idx);
            when others => return C_EDGE_Y_MAX_4(idx);
        end case;
    end function;

    function f_x_top(expr, idx : natural) return integer is
    begin
        case expr is
            when 0 => return C_EDGE_X_TOP_0(idx);
            when 1 => return C_EDGE_X_TOP_1(idx);
            when 2 => return C_EDGE_X_TOP_2(idx);
            when 3 => return C_EDGE_X_TOP_3(idx);
            when others => return C_EDGE_X_TOP_4(idx);
        end case;
    end function;

    function f_slope(expr, idx : natural) return integer is
    begin
        case expr is
            when 0 => return C_EDGE_SLOPE_0(idx);
            when 1 => return C_EDGE_SLOPE_1(idx);
            when 2 => return C_EDGE_SLOPE_2(idx);
            when 3 => return C_EDGE_SLOPE_3(idx);
            when others => return C_EDGE_SLOPE_4(idx);
        end case;
    end function;

end package body bishop_mesh_pkg;
