-- vmnodes_test: VM Nodes Test
-- Node-library test: proc amp, V+H blur and threshold mixed with a colourized sine wave; P12 crossfades.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/vmnodes_test.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   rate       constant      0 ->   0  (LFO rate: 2^14/48 = 341 frames per cycle)
--   vin        video_in      0 ->   1
--   k1         control       1 ->   2
--   k2         control       1 ->   2
--   k3         control       1 ->   2
--   k4         control       1 ->   2
--   k5         control       1 ->   2
--   k6         control       1 ->   2
--   p12        control       1 ->   2
--   glide      glide         1 ->   2
--   pa         procamp       1 ->   6
--   ramp       hramp         1 ->   2
--   s7         control       1 ->   2  (top 2 bits of 0/1023 select shape 0 or 3)
--   lfo        lfo           1 ->   3
--   osc        osc           2 ->   5
--   vb         vblur         6 ->  13
--   hb         hblur        13 ->  19
--   th         threshold    19 ->  22
--   col        colorizer    22 ->  24
--   mix        mix          24 ->  28
--   vout       video_out    28 ->  29
-- Program latency: 29 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   osc.wave         10-bit, delayed by 17 clocks (170 FF)
--   th.out           34-bit, delayed by 2 clocks (68 FF)
-- Chroma of pa, vb, hb is never consumed downstream; synthesis removes it.
-- Controls:
--   K1   registers_in(0)     Bright
--   K2   registers_in(1)     Contrast
--   K3   registers_in(2)     Saturation
--   K4   registers_in(3)     Level
--   K5   registers_in(4)     Softness
--   K6   registers_in(5)     Wave Freq
--   P12  registers_in(7)     Mix
--   S7   registers_in(6)(0)  LFO Shape
-- Estimate: 3804 LC (49.5 %), 10 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture vmnodes_test of program_top is
  signal s_rate_value           : unsigned(10 - 1 downto 0);
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_k1_value             : unsigned(10 - 1 downto 0);
  signal s_k2_value             : unsigned(10 - 1 downto 0);
  signal s_k3_value             : unsigned(10 - 1 downto 0);
  signal s_k4_value             : unsigned(10 - 1 downto 0);
  signal s_k5_value             : unsigned(10 - 1 downto 0);
  signal s_k6_value             : unsigned(10 - 1 downto 0);
  signal s_p12_value            : unsigned(10 - 1 downto 0);
  signal s_glide_value          : unsigned(10 - 1 downto 0);
  signal s_pa_out               : t_vm_stream;
  signal s_ramp_ramp            : unsigned(10 - 1 downto 0);
  signal s_s7_value             : unsigned(10 - 1 downto 0);
  signal s_lfo_value            : unsigned(10 - 1 downto 0);
  signal s_osc_wave             : unsigned(10 - 1 downto 0);
  signal s_vb_out               : t_vm_stream;
  signal s_hb_out               : t_vm_stream;
  signal s_th_out               : t_vm_stream;
  signal s_th_mask              : unsigned(10 - 1 downto 0);
  signal s_col_out              : t_vm_stream;
  signal s_mix_out              : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_osc_wave_d17         : unsigned(10 - 1 downto 0);
  signal s_th_out_d2            : t_vm_stream;
begin

  -- rate (Constant): LFO rate: 2^14/48 = 341 frames per cycle
  u_rate : entity work.vm_constant
    generic map (G_WIDTH => 10, G_VALUE => 48)
    port map (clk => clk, o_value => s_rate_value);

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- k1 (K1: Bright)
  u_k1 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0), o_value => s_k1_value);

  -- k2 (K2: Contrast)
  u_k2 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1), o_value => s_k2_value);

  -- k3 (K3: Saturation)
  u_k3 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2), o_value => s_k3_value);

  -- k4 (K4: Level)
  u_k4 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3), o_value => s_k4_value);

  -- k5 (K5: Softness)
  u_k5 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(4), o_value => s_k5_value);

  -- k6 (K6: Wave Freq)
  u_k6 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(5), o_value => s_k6_value);

  -- p12 (P12: Mix)
  u_p12 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(7),
              o_value => s_p12_value);

  -- glide (Glide)
  u_glide : entity work.vm_glide
    generic map (G_SHIFT => 3)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_p12_value,
              o_value => s_glide_value);

  -- pa (Proc Amp)
  u_pa : entity work.vm_procamp
    generic map (G_IMPL => "shift", G_BITS => 5)
    port map (clk => clk, i_stream => s_vin_out, i_bright => s_k1_value,
              i_contrast => s_k2_value, i_sat => s_k3_value, o_stream => s_pa_out);

  -- ramp (H Ramp)
  u_ramp : entity work.vm_hramp
    generic map (G_FRAC => 6, G_WRAP => true)
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_k6_value,
              i_offset => to_unsigned(0, 10), o_ramp => s_ramp_ramp);

  -- s7 (S7: LFO Shape): top 2 bits of 0/1023 select shape 0 or 3
  u_s7 : entity work.vm_control
    generic map (G_BIT => 0, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6), o_value => s_s7_value);

  -- lfo (LFO)
  u_lfo : entity work.vm_lfo
    generic map (G_PHASE_BITS => 14, G_ROM_STYLE => "logic")
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_rate_value,
              i_shape => s_s7_value(9 downto 8), o_value => s_lfo_value);

  -- osc (Oscillator)
  u_osc : entity work.vm_osc
    generic map (G_ADDR_BITS => 8, G_FREQ_SHIFT => 0, G_ROM_STYLE => "logic")
    port map (clk => clk, i_theta => s_ramp_ramp, i_phase => s_lfo_value, o_wave => s_osc_wave);

  -- vb (V Blur)
  u_vb : entity work.vm_vblur
    generic map (G_TAPS => 3, G_CHROMA => false, G_DEPTH_BITS => 11)
    port map (clk => clk, i_stream => s_pa_out, o_stream => s_vb_out);

  -- hb (H Blur)
  u_hb : entity work.vm_hblur
    generic map (G_TAPS => 3, G_CHROMA => false)
    port map (clk => clk, i_stream => s_vb_out, o_stream => s_hb_out);

  -- th (Threshold)
  u_th : entity work.vm_threshold
    generic map (G_CHANNEL => 0, G_SOFT => true)
    port map (clk => clk, i_stream => s_hb_out, i_level => s_k4_value, i_soft => s_k5_value,
              o_stream => s_th_out, o_mask => s_th_mask);
  u_dly_osc_wave_17 : entity work.vm_delay_scalar generic map (G_WIDTH => 10, G_DELAY => 17)
    port map (clk => clk, i_value => s_osc_wave, o_value => s_osc_wave_d17);

  -- col (Colorizer)
  u_col : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 3,
                 G_PALETTE => "0402002000722e01dc0ff2c12b41361a538c2470d430431505e26e30522e0fa3ac200200")
    port map (clk => clk, i_stream => s_th_out, i_index => s_osc_wave_d17, o_stream => s_col_out);
  u_dly_th_out_2 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_th_out, o_stream => s_th_out_d2);

  -- mix (Mix)
  u_mix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 4)
    port map (clk => clk, i_a => s_col_out, i_b => s_th_out_d2, i_amount => s_glide_value,
              o_stream => s_mix_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_mix_out, o_data => data_out);
end architecture vmnodes_test;
