-- iron_lantern: Iron Lantern
-- Inverted, horizontal sine wave, 16-colour palette, P12 crossfades them.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/iron_lantern.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   ctl_lfo_speed control       1 ->   2
--   ctl_wave_freq control       1 ->   2
--   neg        invert        1 ->   2
--   p12        control       1 ->   2
--   glide      glide         1 ->   2
--   sw_lfo_shape control       1 ->   2
--   lfo        lfo           1 ->   3
--   ramp       hramp         1 ->   2
--   osc        osc           2 ->   5
--   pal        colorizer     5 ->   7
--   mix        mix           7 ->  11
--   vout       video_out    11 ->  12
-- Program latency: 12 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   neg.out          34-bit, delayed by 3 / 5 clocks (170 FF)
-- Controls:
--   K2   registers_in(1)     LFO Speed
--   K1   registers_in(0)     Wave Freq
--   P12  registers_in(7)     Mix
--   S7   registers_in(6)(0)  LFO Shape
-- Estimate: 2592 LC (33.8 %), 0 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture iron_lantern of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_ctl_lfo_speed_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_wave_freq_value  : unsigned(10 - 1 downto 0);
  signal s_neg_out              : t_vm_stream;
  signal s_p12_value            : unsigned(10 - 1 downto 0);
  signal s_glide_value          : unsigned(10 - 1 downto 0);
  signal s_sw_lfo_shape_value   : unsigned(10 - 1 downto 0);
  signal s_lfo_value            : unsigned(10 - 1 downto 0);
  signal s_ramp_ramp            : unsigned(10 - 1 downto 0);
  signal s_osc_wave             : unsigned(10 - 1 downto 0);
  signal s_pal_out              : t_vm_stream;
  signal s_mix_out              : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_neg_out_d3           : t_vm_stream;
  signal s_neg_out_d5           : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- ctl_lfo_speed (K2: LFO Speed)
  u_ctl_lfo_speed : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1),
              o_value => s_ctl_lfo_speed_value);

  -- ctl_wave_freq (K1: Wave Freq)
  u_ctl_wave_freq : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0),
              o_value => s_ctl_wave_freq_value);

  -- neg (Invert)
  u_neg : entity work.vm_invert
    generic map (G_LUMA => true, G_CHROMA => false)
    port map (clk => clk, i_stream => s_vin_out, o_stream => s_neg_out);

  -- p12 (P12: Mix)
  u_p12 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(7),
              o_value => s_p12_value);

  -- glide (Glide)
  u_glide : entity work.vm_glide
    generic map (G_SHIFT => 2)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_p12_value,
              o_value => s_glide_value);

  -- sw_lfo_shape (S7: LFO Shape)
  u_sw_lfo_shape : entity work.vm_control
    generic map (G_BIT => 0, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6),
              o_value => s_sw_lfo_shape_value);

  -- lfo (LFO)
  u_lfo : entity work.vm_lfo
    generic map (G_PHASE_BITS => 18, G_ROM_STYLE => "logic")
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_ctl_lfo_speed_value,
              i_shape => s_sw_lfo_shape_value(9 downto 8), o_value => s_lfo_value);

  -- ramp (H Ramp)
  u_ramp : entity work.vm_hramp
    generic map (G_FRAC => 7, G_WRAP => true)
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_ctl_wave_freq_value,
              i_offset => s_lfo_value, o_ramp => s_ramp_ramp);

  -- osc (Oscillator)
  u_osc : entity work.vm_osc
    generic map (G_ADDR_BITS => 8, G_FREQ_SHIFT => 0, G_ROM_STYLE => "logic")
    port map (clk => clk, i_theta => s_ramp_ramp, i_phase => s_lfo_value, o_wave => s_osc_wave);
  u_dly_neg_out_3 : entity work.vm_delay_stream generic map (G_DELAY => 3)
    port map (clk => clk, i_stream => s_neg_out, o_stream => s_neg_out_d3);
  u_dly_neg_out_5 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_neg_out_d3, o_stream => s_neg_out_d5);

  -- pal (Colorizer)
  u_pal : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 4,
                 G_PALETTE => "0ee1b022112819221714b18220316117a1e91731731c718116f19e18b16d16f1991741411c019512a1e81bc1122121eb0f823d2200de26a25c0c225b2900d222f2c30f81fa2fa123")
    port map (clk => clk, i_stream => s_neg_out_d3, i_index => s_osc_wave, o_stream => s_pal_out);

  -- mix (Mix)
  u_mix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 3)
    port map (clk => clk, i_a => s_neg_out_d5, i_b => s_pal_out, i_amount => s_glide_value,
              o_stream => s_mix_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_mix_out, o_data => data_out);
end architecture iron_lantern;
