-- ash_pulse: Ash Pulse
-- Embossed, colour posterize, keyed on luma, horizontal sine wave, 16-colour palette, sub-blended, colour fringing.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/ash_pulse.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   ctl_key_level control       1 ->   2
--   ctl_key_soft control       1 ->   2
--   ctl_lfo_speed control       1 ->   2
--   ctl_wave_freq control       1 ->   2
--   emb        relief        1 ->   4
--   post       posterize     4 ->   5
--   key        threshold     5 ->   8
--   sw_lfo_shape control       1 ->   2
--   lfo        lfo           1 ->   3
--   ramp       hramp         1 ->   2
--   osc        osc           2 ->   5
--   pal        colorizer     5 ->   7
--   blend      blend         7 ->   9
--   fringe     chroma_shift   9 ->  10
--   vout       video_out    10 ->  11
-- Program latency: 11 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   post.out         34-bit, delayed by 2 clocks (68 FF)
-- Chroma of vin, key is never consumed downstream; synthesis removes it.
-- Controls:
--   K1   registers_in(0)     Key Level
--   K2   registers_in(1)     Key Soft
--   K4   registers_in(3)     LFO Speed
--   K3   registers_in(2)     Wave Freq
--   S7   registers_in(6)(0)  LFO Shape
-- Estimate: 2601 LC (33.9 %), 0 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture ash_pulse of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_ctl_key_level_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_key_soft_value   : unsigned(10 - 1 downto 0);
  signal s_ctl_lfo_speed_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_wave_freq_value  : unsigned(10 - 1 downto 0);
  signal s_emb_out              : t_vm_stream;
  signal s_emb_mask             : unsigned(10 - 1 downto 0);
  signal s_post_out             : t_vm_stream;
  signal s_key_out              : t_vm_stream;
  signal s_key_mask             : unsigned(10 - 1 downto 0);
  signal s_sw_lfo_shape_value   : unsigned(10 - 1 downto 0);
  signal s_lfo_value            : unsigned(10 - 1 downto 0);
  signal s_ramp_ramp            : unsigned(10 - 1 downto 0);
  signal s_osc_wave             : unsigned(10 - 1 downto 0);
  signal s_pal_out              : t_vm_stream;
  signal s_blend_out            : t_vm_stream;
  signal s_fringe_out           : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_post_out_d2          : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- ctl_key_level (K1: Key Level)
  u_ctl_key_level : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0),
              o_value => s_ctl_key_level_value);

  -- ctl_key_soft (K2: Key Soft)
  u_ctl_key_soft : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1),
              o_value => s_ctl_key_soft_value);

  -- ctl_lfo_speed (K4: LFO Speed)
  u_ctl_lfo_speed : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3),
              o_value => s_ctl_lfo_speed_value);

  -- ctl_wave_freq (K3: Wave Freq)
  u_ctl_wave_freq : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2),
              o_value => s_ctl_wave_freq_value);

  -- emb (Relief)
  u_emb : entity work.vm_relief
    generic map (G_SPAN => 2, G_GAIN => 3)
    port map (clk => clk, i_stream => s_vin_out, o_stream => s_emb_out, o_mask => s_emb_mask);

  -- post (Posterize)
  u_post : entity work.vm_posterize
    generic map (G_BITS => 3, G_CHROMA => true)
    port map (clk => clk, i_stream => s_emb_out, o_stream => s_post_out);

  -- key (Threshold)
  u_key : entity work.vm_threshold
    generic map (G_CHANNEL => 0, G_SOFT => true)
    port map (clk => clk, i_stream => s_post_out, i_level => s_ctl_key_level_value,
              i_soft => s_ctl_key_soft_value, o_stream => s_key_out, o_mask => s_key_mask);

  -- sw_lfo_shape (S7: LFO Shape)
  u_sw_lfo_shape : entity work.vm_control
    generic map (G_BIT => 0, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6),
              o_value => s_sw_lfo_shape_value);

  -- lfo (LFO)
  u_lfo : entity work.vm_lfo
    generic map (G_PHASE_BITS => 16, G_ROM_STYLE => "logic")
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_ctl_lfo_speed_value,
              i_shape => s_sw_lfo_shape_value(9 downto 8), o_value => s_lfo_value);

  -- ramp (H Ramp)
  u_ramp : entity work.vm_hramp
    generic map (G_FRAC => 8, G_WRAP => true)
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_ctl_wave_freq_value,
              i_offset => s_lfo_value, o_ramp => s_ramp_ramp);

  -- osc (Oscillator)
  u_osc : entity work.vm_osc
    generic map (G_ADDR_BITS => 8, G_FREQ_SHIFT => 1, G_ROM_STYLE => "logic")
    port map (clk => clk, i_theta => s_ramp_ramp, i_phase => to_unsigned(825, 10),
              o_wave => s_osc_wave);

  -- pal (Colorizer)
  u_pal : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 4,
                 G_PALETTE => "0fd1a921612719620513e18d1ec1511861cb15f1821a316a1811741831921521ab1b513b1d41df1231fe21010922b2490ef22527d0f81fb2ae11d1c82e514718d32017814a3601af")
    port map (clk => clk, i_stream => s_post_out, i_index => s_osc_wave, o_stream => s_pal_out);
  u_dly_post_out_2 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_post_out, o_stream => s_post_out_d2);

  -- blend (Blend)
  u_blend : entity work.vm_blend
    generic map (G_MODE => "sub")
    port map (clk => clk, i_a => s_post_out_d2, i_b => s_pal_out, o_stream => s_blend_out);

  -- fringe (Chroma Shift)
  u_fringe : entity work.vm_chroma_shift
    generic map (G_PIXELS => 8, G_LEAD => "luma")
    port map (clk => clk, i_stream => s_blend_out, o_stream => s_fringe_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_fringe_out, o_data => data_out);
end architecture ash_pulse;
