-- iron_harbor: Iron Harbor
-- Smeared, V blur, embossed, keyed on luma, mixed through the key, P12 fades back to the source, colour fringing.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/iron_harbor.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   ctl_grain  control       1 ->   2
--   ctl_key_level control       1 ->   2
--   ctl_key_soft control       1 ->   2
--   ctl_smear_level control       1 ->   2
--   grain      noise         1 ->   4
--   osc        shaper        4 ->   5
--   p12        control       1 ->   2
--   glide      glide         1 ->   2
--   smkey      threshold     1 ->   4
--   smear      smear         4 ->   5
--   vb         vblur         5 ->  12
--   emb        relief       12 ->  15
--   key        threshold    15 ->  18
--   pal        colorizer    15 ->  17
--   mix        mix          18 ->  22
--   wet        mix          22 ->  26
--   fringe     chroma_shift  26 ->  27
--   vout       video_out    27 ->  28
-- Program latency: 28 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   vin.out          34-bit, delayed by 3 / 21 clocks (714 FF)
--   osc.out          10-bit, delayed by 10 clocks (100 FF)
--   emb.out          34-bit, delayed by 3 clocks (102 FF)
--   pal.out          34-bit, delayed by 1 clocks (34 FF)
-- Chroma of smkey, smear, vb, key is never consumed downstream; synthesis removes it.
-- Controls:
--   K4   registers_in(3)     Grain
--   K2   registers_in(1)     Key Level
--   K3   registers_in(2)     Key Soft
--   K1   registers_in(0)     Smear Level
--   P12  registers_in(7)     Dry/Wet
-- Estimate: 4437 LC (57.8 %), 20 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture iron_harbor of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_ctl_grain_value      : unsigned(10 - 1 downto 0);
  signal s_ctl_key_level_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_key_soft_value   : unsigned(10 - 1 downto 0);
  signal s_ctl_smear_level_value : unsigned(10 - 1 downto 0);
  signal s_grain_noise          : unsigned(10 - 1 downto 0);
  signal s_osc_out              : unsigned(10 - 1 downto 0);
  signal s_p12_value            : unsigned(10 - 1 downto 0);
  signal s_glide_value          : unsigned(10 - 1 downto 0);
  signal s_smkey_out            : t_vm_stream;
  signal s_smkey_mask           : unsigned(10 - 1 downto 0);
  signal s_smear_out            : t_vm_stream;
  signal s_vb_out               : t_vm_stream;
  signal s_emb_out              : t_vm_stream;
  signal s_emb_mask             : unsigned(10 - 1 downto 0);
  signal s_key_out              : t_vm_stream;
  signal s_key_mask             : unsigned(10 - 1 downto 0);
  signal s_pal_out              : t_vm_stream;
  signal s_mix_out              : t_vm_stream;
  signal s_wet_out              : t_vm_stream;
  signal s_fringe_out           : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_vin_out_d3           : t_vm_stream;
  signal s_vin_out_d21          : t_vm_stream;
  signal s_osc_out_d10          : unsigned(10 - 1 downto 0);
  signal s_emb_out_d3           : t_vm_stream;
  signal s_pal_out_d1           : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- ctl_grain (K4: Grain)
  u_ctl_grain : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3),
              o_value => s_ctl_grain_value);

  -- ctl_key_level (K2: Key Level)
  u_ctl_key_level : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1),
              o_value => s_ctl_key_level_value);

  -- ctl_key_soft (K3: Key Soft)
  u_ctl_key_soft : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2),
              o_value => s_ctl_key_soft_value);

  -- ctl_smear_level (K1: Smear Level)
  u_ctl_smear_level : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0),
              o_value => s_ctl_smear_level_value);

  -- grain (Noise)
  u_grain : entity work.vm_noise
    generic map (G_ANIMATE => false)
    port map (clk => clk, i_stream => s_vin_out, i_size => s_ctl_grain_value,
              o_noise => s_grain_noise);

  -- osc (Shaper)
  u_osc : entity work.vm_shaper
    generic map (G_OP => "fold")
    port map (clk => clk, i_x => s_grain_noise, i_gain => to_unsigned(979, 10),
              o_out => s_osc_out);

  -- p12 (P12: Dry/Wet)
  u_p12 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(7),
              o_value => s_p12_value);

  -- glide (Glide)
  u_glide : entity work.vm_glide
    generic map (G_SHIFT => 3)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_p12_value,
              o_value => s_glide_value);

  -- smkey (Threshold)
  u_smkey : entity work.vm_threshold
    generic map (G_CHANNEL => 0, G_SOFT => false)
    port map (clk => clk, i_stream => s_vin_out, i_level => s_ctl_smear_level_value,
              i_soft => to_unsigned(0, 10), o_stream => s_smkey_out, o_mask => s_smkey_mask);
  u_dly_vin_out_3 : entity work.vm_delay_stream generic map (G_DELAY => 3)
    port map (clk => clk, i_stream => s_vin_out, o_stream => s_vin_out_d3);
  u_dly_vin_out_21 : entity work.vm_delay_stream generic map (G_DELAY => 18)
    port map (clk => clk, i_stream => s_vin_out_d3, o_stream => s_vin_out_d21);

  -- smear (Smear)
  u_smear : entity work.vm_smear
    port map (clk => clk, i_stream => s_vin_out_d3, i_mask => s_smkey_mask,
              o_stream => s_smear_out);

  -- vb (V Blur)
  u_vb : entity work.vm_vblur
    generic map (G_TAPS => 5, G_CHROMA => false, G_DEPTH_BITS => 11)
    port map (clk => clk, i_stream => s_smear_out, o_stream => s_vb_out);

  -- emb (Relief)
  u_emb : entity work.vm_relief
    generic map (G_SPAN => 3, G_GAIN => 3)
    port map (clk => clk, i_stream => s_vb_out, o_stream => s_emb_out, o_mask => s_emb_mask);

  -- key (Threshold)
  u_key : entity work.vm_threshold
    generic map (G_CHANNEL => 0, G_SOFT => true)
    port map (clk => clk, i_stream => s_emb_out, i_level => s_ctl_key_level_value,
              i_soft => s_ctl_key_soft_value, o_stream => s_key_out, o_mask => s_key_mask);
  u_dly_osc_out_10 : entity work.vm_delay_scalar generic map (G_WIDTH => 10, G_DELAY => 10)
    port map (clk => clk, i_value => s_osc_out, o_value => s_osc_out_d10);

  -- pal (Colorizer)
  u_pal : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 4,
                 G_PALETTE => "0e01c91c60fc1c71b011f1cf1a01431db1901691ec17e18f20316b1b721e1581df23e1441e025914d1d927615c1cc29716f1b92bb1861a12e21a218430c1c118b3211e81b9320218")
    port map (clk => clk, i_stream => s_emb_out, i_index => s_osc_out_d10, o_stream => s_pal_out);
  u_dly_emb_out_3 : entity work.vm_delay_stream generic map (G_DELAY => 3)
    port map (clk => clk, i_stream => s_emb_out, o_stream => s_emb_out_d3);
  u_dly_pal_out_1 : entity work.vm_delay_stream generic map (G_DELAY => 1)
    port map (clk => clk, i_stream => s_pal_out, o_stream => s_pal_out_d1);

  -- mix (Mix)
  u_mix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 4)
    port map (clk => clk, i_a => s_emb_out_d3, i_b => s_pal_out_d1, i_amount => s_key_mask,
              o_stream => s_mix_out);

  -- wet (Mix)
  u_wet : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 4)
    port map (clk => clk, i_a => s_vin_out_d21, i_b => s_mix_out, i_amount => s_glide_value,
              o_stream => s_wet_out);

  -- fringe (Chroma Shift)
  u_fringe : entity work.vm_chroma_shift
    generic map (G_PIXELS => 2, G_LEAD => "chroma")
    port map (clk => clk, i_stream => s_wet_out, o_stream => s_fringe_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_fringe_out, o_data => data_out);
end architecture iron_harbor;
