#!/usr/bin/env python3
"""Matrix Rain colour wheel -> VHDL constant (paste into matrix_rain.vhd).

Each entry is a chroma-per-level direction plus a luma gain, so a lit pixel at
level L (above black) renders as  Y = 64 + L*k,  Cr/Cb = 512 + L*k*c/512.
  cu = 512 * 0.7293 * (R/Y - 1)    (stored U = Cr: Videomancer U/V swap)
  cv = 512 * 0.5769 * (B/Y - 1)    (stored V = Cb)
  0.7293 = 0.713*896/876, 0.5769 = 0.564*896/876 (10-bit chroma/luma scales)
k (3-bit scale8 select, gain (sel+1)/8) keeps the brightest channel of the
body peak (L=500, Y'=0.571) at or under full scale, so dim hues (blue) still
fade over the whole tail instead of sitting clipped.
Index 0..63 is a closed hue wheel (phosphor green at 32 = knob centre);
index 64 is white.
"""
anchors = [  # (wheel index, R, G, B)
    (0,  1.00, 0.08, 0.08),   # red
    (8,  1.00, 0.42, 0.00),   # orange
    (16, 1.00, 0.75, 0.00),   # amber
    (24, 0.50, 1.00, 0.00),   # lime
    (32, 0.00, 1.00, 0.069),  # phosphor green (ziffern-verified hue)
    (40, 0.00, 0.90, 1.00),   # cyan
    (48, 0.10, 0.30, 1.00),   # blue
    (56, 0.65, 0.10, 1.00),   # violet
    (64, 1.00, 0.08, 0.08),   # back to red
]

def entry(r, g, b):
    y = 0.299 * r + 0.587 * g + 0.114 * b
    cu = round(512 * 0.7293 * (r / y - 1))
    cv = round(512 * 0.5769 * (b / y - 1))
    k = y / (max(r, g, b) * 0.571)
    sel = max(0, min(7, int(k * 8) - 1))
    return cu, cv, sel

ents = []
for i in range(64):
    for (i0, *c0), (i1, *c1) in zip(anchors, anchors[1:]):
        if i0 <= i < i1:
            t = (i - i0) / (i1 - i0)
            ents.append(entry(*[a + (b - a) * t for a, b in zip(c0, c1)]))
ents.append((0, 0, 7))  # white

def word(cu, cv, sel):
    assert abs(cu) < 1024 and abs(cv) < 1024
    return ((cu < 0) << 31) | (abs(cu) << 21) | ((cv < 0) << 20) | (abs(cv) << 10) | sel

lines = [f'x"{word(*e):08X}"' for e in ents]
print("    -- generated by genpal.py: [31] U sign, [30:21] |cu|, [20] V sign, [19:10] |cv|, [2:0] k")
print("    constant C_PAL : t_pal := (")
for j in range(0, len(lines), 6):
    sep = "," if j + 6 < len(lines) else ","
    print("        " + ", ".join(lines[j:j + 6]) + sep)
print("        others => x\"00000007\");")
if __name__ == "__main__":
    import sys
    if "-v" in sys.argv:
        for i, e in enumerate(ents):
            print(i, e, file=sys.stderr)
