#!/usr/bin/env python3
# matrix_rain.py - Build hook for the Matrix Rain Videomancer program.
# Copyright (C) 2026  bluecondition
# SPDX-License-Identifier: GPL-3.0-only
#
# Generates matrix_rain_glyphs_pkg.vhd, a packed 16x16 1-bit glyph ROM, from
# the vendored GNU Unifont bitmap subset `unifont_jp.hex`.
#
# Why Unifont .hex (not a TTF + rasterizer): Unifont IS a native 16-pixel
# bitmap font, so its .hex data already contains exactly the pixels we want -
# no antialiasing, no thresholding, fully deterministic across machines and
# with zero third-party Python dependencies (no Pillow).  This is the safest
# possible input for an FPGA glyph ROM.
#
# Font provenance / license:
#   GNU Unifont 15.1.05  (http://unifoundry.com/unifont/)
#   Copyright Roman Czyborra, Paul Hardy, et al.
#   Dual-licensed GNU GPL-2.0-or-later (with the GNU font embedding exception)
#   and SIL Open Font License 1.1 - both compatible with this program's GPL-3.0.
#   `unifont_jp.hex` is a verbatim subset of the upstream .hex (the exact glyph
#   rows for the codepoints we use, in ROM-index order), produced once at
#   vendor time; this hook only re-packs it into VHDL.
#
# Glyph set / ROM order (index = line order in unifont_jp.hex):
#   - Half-width katakana  U+FF66 .. U+FF9D   (56 glyphs, the authentic Matrix
#     "digital rain" characters)
#   - Digits               U+0030 .. U+0039   (10)
#   - A few Latin/symbols   A Z : = * + - .    (8)
#
# Each upstream half-width glyph is 8 px wide x 16 px tall (32 hex chars = 16
# rows x 2 hex/row).  We center the 8-wide glyph inside a 16-wide cell (columns
# 4..11) so the cell is square (16x16) and the S8 "mirror" switch is meaningful.
# Output rows are 16-bit std_logic_vector with the MSB = leftmost pixel.

import os
import sys

# Horizontal offset (in pixels) of the 8-wide glyph within the 16-wide cell.
# 4 -> glyph occupies columns 4..11 (centered).
GLYPH_X_OFFSET = 4
CELL_W = 16
CELL_H = 16


def parse_hex_line(line):
    """Return (codepoint:int, rows:list[int]) for one unifont .hex line.

    rows is a list of CELL_H 16-bit ints, MSB = leftmost pixel, with the
    8-wide source glyph placed at GLYPH_X_OFFSET inside the 16-wide cell.
    Only 8-wide (32 hex char) glyphs are expected; 16-wide (64 hex) are
    accepted too (placed left-aligned) just in case.
    """
    code_s, bits = line.split(":")
    code = int(code_s, 16)
    if len(bits) == 32:          # 8 px wide: 2 hex per row
        per_row = 2
        src_w = 8
    elif len(bits) == 64:        # 16 px wide: 4 hex per row
        per_row = 4
        src_w = 16
    else:
        raise ValueError(f"U+{code:04X}: unexpected hex length {len(bits)}")

    rows = []
    for r in range(CELL_H):
        chunk = bits[r * per_row:(r + 1) * per_row]
        val = int(chunk, 16)                  # MSB = leftmost of the src_w field
        if src_w == 8:
            # Place the 8-bit field at columns OFFSET..OFFSET+7 of a 16-bit cell.
            # bit7 (leftmost) -> column OFFSET -> 16-bit position (15-OFFSET).
            row16 = val << (CELL_W - src_w - GLYPH_X_OFFSET)
        else:
            row16 = val                       # already 16 wide, left-aligned
        rows.append(row16 & 0xFFFF)
    return code, rows


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    hex_path = os.path.join(here, "unifont_jp.hex")
    out_path = os.path.join(here, "matrix_rain_glyphs_pkg.vhd")

    print("Generating matrix_rain glyph ROM from unifont_jp.hex ...")

    glyphs = []   # list of (codepoint, [16 rows])
    with open(hex_path, "r") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            glyphs.append(parse_hex_line(line))

    n = len(glyphs)
    if n == 0:
        print("ERROR: no glyphs parsed from unifont_jp.hex", file=sys.stderr)
        return 1

    lines = []
    lines.append("-- AUTO-GENERATED by matrix_rain.py - do not edit by hand.")
    lines.append(f"-- {n} glyphs x {CELL_H} rows x {CELL_W} bits.  MSB = leftmost pixel.")
    lines.append("-- Source: GNU Unifont 15.1.05 (GPL-2.0-or-later / OFL-1.1).")
    lines.append("-- 8-wide half-width glyphs centered at column "
                 f"{GLYPH_X_OFFSET} of each 16-wide cell.")
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("")
    lines.append("package matrix_rain_glyphs_pkg is")
    lines.append("")
    lines.append(f"    constant C_NGLYPH    : integer := {n};")
    lines.append(f"    constant C_GLYPH_W   : integer := {CELL_W};")
    lines.append(f"    constant C_GLYPH_H   : integer := {CELL_H};")
    lines.append("")
    lines.append("    type t_glyph_rom is array (0 to C_NGLYPH - 1, 0 to C_GLYPH_H - 1)")
    lines.append("        of std_logic_vector(C_GLYPH_W - 1 downto 0);")
    lines.append("")
    lines.append("    constant C_GLYPHS : t_glyph_rom := (")

    last = n - 1
    for idx, (code, rows) in enumerate(glyphs):
        row_strs = ", ".join(f'x"{r:04X}"' for r in rows)
        sep = "," if idx < last else " "
        lines.append(f"        {idx:3d} => ({row_strs}){sep}  -- U+{code:04X}")
    lines.append("    );")
    lines.append("")
    lines.append("end package matrix_rain_glyphs_pkg;")
    lines.append("")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path} ({n} glyphs, {CELL_W}x{CELL_H} 1bpp)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
