-- Pyre: advected-field fire — a real 2D temperature field simulation
-- LZX Industries Community FPGA Program
--
-- Not scrolling noise: a 256x64 4-bit TEMPERATURE GRID lives in EBR and is
-- re-simulated every field by semi-Lagrangian advection.  Each cell gathers
-- (bilinear) from where its parcel came from one field ago, moving through a
-- velocity field made of curl noise (divergence-free turbulence from the
-- analytic derivatives of two octaves of smoothstep value noise), buoyancy
-- (hot cells rise faster -> pointed, stretching tongues), and entrainment
-- (flow converges toward hotter neighbours -> tongues self-sharpen and
-- separate).  Parcels cool by a base rate plus a temperature-proportional
-- term plus a random grain; cool parcels linger as smoke.  A flickering
-- burner at the bottom row (or, in Luma Mod, every bright video cell)
-- injects heat.  Cells are stored as 4 bits with hash-dithered stochastic
-- rounding, so sub-level cooling rates still act on average.  The grid is
-- swept one row per display row, just behind the raster, with a one-row
-- delayed write-back, so ONE grid bank is enough: the raster always sees
-- last field's complete state while this field's is computed above it.
-- K2 Width compresses the turbulence/burner lattices horizontally: narrow,
-- dense tongues at full.  Streams narrower than 1536 px (SD, 720p) run the
-- sim and display at half horizontal resolution (128 cell pairs) to fit
-- 480i's 3.2k-clock row budget and the display reader's 6-px cell minimum.
--
-- Display: a 3-row cache feeds a smoothstep-bilinear upsample (7.5x17 px
-- cells at 1080p), then a 256-entry blackbody palette ROM (limited-range
-- 10-bit YUV, U/V swapped for hardware).  Blue Flame negates the chroma.
-- Output is gated to neutral outside active video; every per-field action
-- fires once per field even when analog vsync serrates.
--
-- License: GPL-3.0
-- Author: ron

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.all;

architecture pyre of program_top is

  constant C_LATENCY : integer := 12;

  -- ------------------------------------------------------------------
  -- Tables (generated by gen_tables.py)
  -- ------------------------------------------------------------------
  -- @@TABLES_BEGIN@@
  type t_sd is array(0 to 127) of unsigned(16 downto 0);
  constant C_SD : t_sd := (
    0 => "00000000000000000", 1 => "00000000000000110", 2 => "00000000000001100", 3 => "00000000000010010",
    4 => "00000000100010111", 5 => "00000000100011101", 6 => "00000001000100010", 7 => "00000001000101000",
    8 => "00000001100101101", 9 => "00000010000110010", 10 => "00000010000110111", 11 => "00000010100111100",
    12 => "00000011001000001", 13 => "00000011101000110", 14 => "00000100101001011", 15 => "00000101001001111",
    16 => "00000101101010100", 17 => "00000110001011000", 18 => "00000111001011101", 19 => "00000111101100001",
    20 => "00001000101100101", 21 => "00001001001101001", 22 => "00001010001101101", 23 => "00001011001110001",
    24 => "00001100001110101", 25 => "00001100101111001", 26 => "00001101101111100", 27 => "00001110110000000",
    28 => "00001111110000011", 29 => "00010000110000111", 30 => "00010010010001010", 31 => "00010011010001101",
    32 => "00010100010010000", 33 => "00010101010010011", 34 => "00010110110010110", 35 => "00010111110011001",
    36 => "00011000110011011", 37 => "00011010010011110", 38 => "00011011010100000", 39 => "00011100110100011",
    40 => "00011101110100101", 41 => "00011111010100111", 42 => "00100000110101001", 43 => "00100001110101011",
    44 => "00100011010101101", 45 => "00100100110101111", 46 => "00100101110110001", 47 => "00100111010110010",
    48 => "00101000110110100", 49 => "00101010010110101", 50 => "00101011110110111", 51 => "00101101010111000",
    52 => "00101110010111001", 53 => "00101111110111010", 54 => "00110001010111011", 55 => "00110010110111100",
    56 => "00110100010111101", 57 => "00110101110111110", 58 => "00110111010111110", 59 => "00111000110111111",
    60 => "00111010010111111", 61 => "00111011111000000", 62 => "00111101011000000", 63 => "00111110111000000",
    64 => "01000000011000000", 65 => "01000001111000000", 66 => "01000011011000000", 67 => "01000100111000000",
    68 => "01000110010111111", 69 => "01000111110111111", 70 => "01001001010111110", 71 => "01001010110111110",
    72 => "01001100010111101", 73 => "01001101110111100", 74 => "01001111010111011", 75 => "01010000110111010",
    76 => "01010010010111001", 77 => "01010011010111000", 78 => "01010100110110111", 79 => "01010110010110101",
    80 => "01010111110110100", 81 => "01011001010110010", 82 => "01011010110110001", 83 => "01011011110101111",
    84 => "01011101010101101", 85 => "01011110110101011", 86 => "01011111110101001", 87 => "01100001010100111",
    88 => "01100010110100101", 89 => "01100011110100011", 90 => "01100101010100000", 91 => "01100110010011110",
    92 => "01100111110011011", 93 => "01101000110011001", 94 => "01101001110010110", 95 => "01101011010010011",
    96 => "01101100010010000", 97 => "01101101010001101", 98 => "01101110010001010", 99 => "01101111110000111",
    100 => "01110000110000011", 101 => "01110001110000000", 102 => "01110010101111100", 103 => "01110011101111001",
    104 => "01110100001110101", 105 => "01110101001110001", 106 => "01110110001101101", 107 => "01110111001101001",
    108 => "01110111101100101", 109 => "01111000101100001", 110 => "01111001001011101", 111 => "01111010001011000",
    112 => "01111010101010100", 113 => "01111011001001111", 114 => "01111011101001011", 115 => "01111100101000110",
    116 => "01111101001000001", 117 => "01111101100111100", 118 => "01111110000110111", 119 => "01111110000110010",
    120 => "01111110100101101", 121 => "01111111000101000", 122 => "01111111000100010", 123 => "01111111100011101",
    124 => "01111111100010111", 125 => "10000000000010010", 126 => "10000000000001100", 127 => "10000000000000110"
  );
  type t_ss6 is array(0 to 63) of unsigned(6 downto 0);
  constant C_SS6 : t_ss6 := (
    0 => "0000000", 1 => "0000000", 2 => "0000000", 3 => "0000000", 4 => "0000001", 5 => "0000001", 6 => "0000010", 7 => "0000010",
    8 => "0000011", 9 => "0000011", 10 => "0000100", 11 => "0000101", 12 => "0000110", 13 => "0000111", 14 => "0001000", 15 => "0001001",
    16 => "0001010", 17 => "0001011", 18 => "0001100", 19 => "0001110", 20 => "0001111", 21 => "0010000", 22 => "0010001", 23 => "0010011",
    24 => "0010100", 25 => "0010110", 26 => "0010111", 27 => "0011001", 28 => "0011010", 29 => "0011100", 30 => "0011101", 31 => "0011111",
    32 => "0100000", 33 => "0100001", 34 => "0100011", 35 => "0100100", 36 => "0100110", 37 => "0100111", 38 => "0101001", 39 => "0101010",
    40 => "0101100", 41 => "0101101", 42 => "0101111", 43 => "0110000", 44 => "0110001", 45 => "0110010", 46 => "0110100", 47 => "0110101",
    48 => "0110110", 49 => "0110111", 50 => "0111000", 51 => "0111001", 52 => "0111010", 53 => "0111011", 54 => "0111100", 55 => "0111101",
    56 => "0111101", 57 => "0111110", 58 => "0111110", 59 => "0111111", 60 => "0111111", 61 => "1000000", 62 => "1000000", 63 => "1000000"
  );
  type t_mod3 is array(0 to 127) of unsigned(1 downto 0);
  constant C_MOD3 : t_mod3 := (
    0 => "00", 1 => "01", 2 => "10", 3 => "00", 4 => "01", 5 => "10", 6 => "00", 7 => "01", 8 => "10", 9 => "00", 10 => "01", 11 => "10", 12 => "00", 13 => "01", 14 => "10", 15 => "00",
    16 => "01", 17 => "10", 18 => "00", 19 => "01", 20 => "10", 21 => "00", 22 => "01", 23 => "10", 24 => "00", 25 => "01", 26 => "10", 27 => "00", 28 => "01", 29 => "10", 30 => "00", 31 => "01",
    32 => "10", 33 => "00", 34 => "01", 35 => "10", 36 => "00", 37 => "01", 38 => "10", 39 => "00", 40 => "01", 41 => "10", 42 => "00", 43 => "01", 44 => "10", 45 => "00", 46 => "01", 47 => "10",
    48 => "00", 49 => "01", 50 => "10", 51 => "00", 52 => "01", 53 => "10", 54 => "00", 55 => "01", 56 => "10", 57 => "00", 58 => "01", 59 => "10", 60 => "00", 61 => "01", 62 => "10", 63 => "00",
    64 => "01", 65 => "10", 66 => "00", 67 => "01", 68 => "10", 69 => "00", 70 => "01", 71 => "10", 72 => "00", 73 => "01", 74 => "10", 75 => "00", 76 => "01", 77 => "10", 78 => "00", 79 => "01",
    80 => "10", 81 => "00", 82 => "01", 83 => "10", 84 => "00", 85 => "01", 86 => "10", 87 => "00", 88 => "01", 89 => "10", 90 => "00", 91 => "01", 92 => "10", 93 => "00", 94 => "01", 95 => "10",
    96 => "00", 97 => "01", 98 => "10", 99 => "00", 100 => "01", 101 => "10", 102 => "00", 103 => "01", 104 => "10", 105 => "00", 106 => "01", 107 => "10", 108 => "00", 109 => "01", 110 => "10", 111 => "00",
    112 => "01", 113 => "10", 114 => "00", 115 => "01", 116 => "10", 117 => "00", 118 => "01", 119 => "10", 120 => "00", 121 => "01", 122 => "10", 123 => "00", 124 => "01", 125 => "10", 126 => "00", 127 => "01"
  );
  type t_pal is array (0 to 255) of std_logic_vector(29 downto 0);
  -- packed Y(29:20) U(19:10)=Cr V(9:0)=Cb, limited range, U/V swapped for HW
  constant C_PAL : t_pal := (
    0 => "000100000010000000001000000000", 1 => "000100000010000000001000000000", 2 => "000100000010000000001000000000", 3 => "000100000010000000001000000000",
    4 => "000100000010000000001000000000", 5 => "000100000010000000001000000000", 6 => "000100000010000000001000000000", 7 => "000100000010000000001000000000",
    8 => "000100000010000000001000000000", 9 => "000100000010000000001000000000", 10 => "000100000010000000001000000000", 11 => "000100000010000000001000000000",
    12 => "000100000010000000001000000000", 13 => "000100000010000000001000000000", 14 => "000100000010000000001000000000", 15 => "000100000010000000001000000000",
    16 => "000100000010000000001000000000", 17 => "000100000010000000001000000000", 18 => "000100000010000000001000000000", 19 => "000100000010000000001000000000",
    20 => "000100000010000000001000000000", 21 => "000100000010000000001000000000", 22 => "000100000010000000001000000000", 23 => "000100000010000000001000000000",
    24 => "000100000010000000001000000000", 25 => "000100011010000010010111111101", 26 => "000100110010000100110111111001", 27 => "000101001010000111000111110110",
    28 => "000101100010001001100111110010", 29 => "000101111010001011110111101111", 30 => "000110010010001110010111101011", 31 => "000110101010010000100111101000",
    32 => "000111000010010010110111100100", 33 => "000111011010010101010111100001", 34 => "000111110010010111100111011101", 35 => "001000001010011010000111011010",
    36 => "001000100010011100010111010110", 37 => "001000111110011110100111010011", 38 => "001001010010100000110111001111", 39 => "001001100010100010000111001101",
    40 => "001001110010100011010111001011", 41 => "001010000010100100100111001000", 42 => "001010010010100101110111000110", 43 => "001010100010100111000111000100",
    44 => "001010110010101000010111000001", 45 => "001011000110101001100110111111", 46 => "001011010110101010110110111101", 47 => "001011100110101100000110111010",
    48 => "001011110110101101010110111000", 49 => "001100000110101110100110110110", 50 => "001100010110101111110110110011", 51 => "001100100110110001000110110001",
    52 => "001100110110110010010110101111", 53 => "001101000110110011100110101100", 54 => "001101010110110100110110101010", 55 => "001101100110110110000110101000",
    56 => "001101110110110111010110100101", 57 => "001110000110111000100110100011", 58 => "001110010110111001100110100001", 59 => "001110100110111010110110011111",
    60 => "001110110110111100000110011100", 61 => "001111000110111101010110011010", 62 => "001111010110111110100110011000", 63 => "001111100110111111110110010101",
    64 => "001111110111000001000110010011", 65 => "010000000111000010010110010001", 66 => "010000010111000011100110001110", 67 => "010000100111000100110110001100",
    68 => "010000110111000110000110001010", 69 => "010001000111000111010110000111", 70 => "010001010111001000100110000101", 71 => "010001100011001001000110000011",
    72 => "010001101111001001010110000010", 73 => "010001111011001001100110000000", 74 => "010010000111001001110101111111", 75 => "010010001111001010000101111101",
    76 => "010010011011001010010101111100", 77 => "010010100111001010110101111010", 78 => "010010101111001011000101111001", 79 => "010010111011001011010101110111",
    80 => "010011000111001011100101110110", 81 => "010011001111001011110101110100", 82 => "010011011011001100000101110011", 83 => "010011100111001100010101110010",
    84 => "010011110011001100100101110000", 85 => "010011111011001101000101101111", 86 => "010100000111001101010101101101", 87 => "010100010011001101100101101100",
    88 => "010100011011001101110101101010", 89 => "010100100111001110000101101001", 90 => "010100110011001110010101100111", 91 => "010100111111001110100101100110",
    92 => "010101000111001110110101100100", 93 => "010101010011001111010101100011", 94 => "010101011111001111100101100001", 95 => "010101100111001111110101100000",
    96 => "010101110011010000000101011110", 97 => "010101111111010000010101011101", 98 => "010110001011010000100101011011", 99 => "010110010011010000110101011010",
    100 => "010110011111010001000101011000", 101 => "010110101011010001010101010111", 102 => "010110110011010001110101010101", 103 => "010110111111010010000101010100",
    104 => "010111001011010010010101010011", 105 => "010111010111010010100101010001", 106 => "010111011111010010110101010000", 107 => "010111101011010011000101001110",
    108 => "010111110111010011010101001101", 109 => "010111111111010011100101001011", 110 => "011000001011010100000101001010", 111 => "011000010111010100010101001000",
    112 => "011000100011010100100101000111", 113 => "011000101011010100110101000101", 114 => "011000110111010101000101000100", 115 => "011001000011010101010101000010",
    116 => "011001001011010101100101000001", 117 => "011001010111010101110100111111", 118 => "011001100011010110010100111110", 119 => "011001101111010110100100111100",
    120 => "011001110111010110110100111011", 121 => "011010000011010111000100111001", 122 => "011010001111010111010100111000", 123 => "011010010111010111100100110110",
    124 => "011010100011010111110100110101", 125 => "011010101111011000000100110011", 126 => "011010111011011000010100110010", 127 => "011011000011011000110100110001",
    128 => "011011001111011001000100101111", 129 => "011011010111011000100100101110", 130 => "011011100011011000000100101100", 131 => "011011101011010111110100101011",
    132 => "011011110111010111010100101010", 133 => "011011111111010111000100101001", 134 => "011100000111010110100100100111", 135 => "011100010011010110010100100110",
    136 => "011100011011010101110100100101", 137 => "011100100111010101100100100011", 138 => "011100101111010101000100100010", 139 => "011100111011010100110100100001",
    140 => "011101000011010100010100011111", 141 => "011101001011010011110100011110", 142 => "011101010111010011100100011101", 143 => "011101011111010011000100011011",
    144 => "011101101011010010110100011010", 145 => "011101110011010010010100011001", 146 => "011101111111010010000100010111", 147 => "011110000111010001100100010110",
    148 => "011110001111010001010100010101", 149 => "011110011011010000110100010100", 150 => "011110100011010000100100010010", 151 => "011110101111010000000100010001",
    152 => "011110110111001111100100010000", 153 => "011111000011001111010100001110", 154 => "011111001011001110110100001101", 155 => "011111010011001110100100001100",
    156 => "011111011111001110000100001010", 157 => "011111100111001101110100001001", 158 => "011111110011001101010100001000", 159 => "011111111011001101000100000110",
    160 => "100000000011001100100100000101", 161 => "100000001111001100010100000100", 162 => "100000010111001011110100000011", 163 => "100000100011001011010100000001",
    164 => "100000101011001011000100000000", 165 => "100000110111001010100011111111", 166 => "100000111111001010010011111101", 167 => "100001000111001001110011111100",
    168 => "100001010011001001100011111011", 169 => "100001011011001001000011111001", 170 => "100001100111001000110011111000", 171 => "100001101111001000010011110111",
    172 => "100001111011001000000011110101", 173 => "100010000011000111100011110100", 174 => "100010001011000111000011110011", 175 => "100010010111000110110011110001",
    176 => "100010011111000110010011110000", 177 => "100010101011000110000011101111", 178 => "100010110011000101100011101110", 179 => "100010111111000101010011101100",
    180 => "100011000111000100110011101011", 181 => "100011001111000100100011101010", 182 => "100011011011000100000011101000", 183 => "100011100011000011110011100111",
    184 => "100011101111000011010011100110", 185 => "100011110111000010110011100100", 186 => "100100000011000010100011100011", 187 => "100100001111000001110011100010",
    188 => "100100011011000001010011100000", 189 => "100100100111000000110011011111", 190 => "100100110011000000010011011101", 191 => "100100111110111111110011011100",
    192 => "100101001010111111000011011011", 193 => "100101010110111110100011011001", 194 => "100101100010111110000011011000", 195 => "100101101110111101100011010111",
    196 => "100101111010111101000011010101", 197 => "100110000110111100010011010100", 198 => "100110010010111011110011010010", 199 => "100110011110111011010011010001",
    200 => "100110101010111010110011010000", 201 => "100110110110111010000011001110", 202 => "100111000010111001100011001101", 203 => "100111001110111001000011001011",
    204 => "100111011010111000100011001010", 205 => "100111100110111000000011001001", 206 => "100111110010110111010011000111", 207 => "100111111110110110110011000110",
    208 => "101000001110110110010011000100", 209 => "101000011010110101110011000011", 210 => "101000100110110101000011000010", 211 => "101000110010110100100011000000",
    212 => "101000111110110100000010111111", 213 => "101001001010110011100010111110", 214 => "101001010110110011000010111100", 215 => "101001100010110010010010111011",
    216 => "101001101110110001110010111001", 217 => "101001111010110001010010111000", 218 => "101010000110110000110010110111", 219 => "101010010010110000010010110101",
    220 => "101010011110101111100010110100", 221 => "101010101010101111000010110010", 222 => "101010110110101110100010110001", 223 => "101011000010101110000010110000",
    224 => "101011001110101101010010101110", 225 => "101011011010101100110010101101", 226 => "101011100110101100010010101011", 227 => "101011110010101011110010101010",
    228 => "101100000110101010110010101011", 229 => "101100001110101001110010101101", 230 => "101100011010101000110010101110", 231 => "101100100110101000000010110000",
    232 => "101100101110100111000010110010", 233 => "101100111010100110000010110100", 234 => "101101000110100101000010110101", 235 => "101101001110100100000010110111",
    236 => "101101011010100011000010111001", 237 => "101101100110100010000010111011", 238 => "101101110010100001000010111100", 239 => "101101111010100000000010111110",
    240 => "101110000110011111000011000000", 241 => "101110010010011110000011000010", 242 => "101110011010011101000011000011", 243 => "101110100110011100000011000101",
    244 => "101110110010011011000011000111", 245 => "101110111110011010000011001001", 246 => "101111000110011001000011001010", 247 => "101111010010011000000011001100",
    248 => "101111011110010111000011001110", 249 => "101111110010010101000011100110", 250 => "110000000010010011000100000000", 251 => "110000000010010000110100011010",
    252 => "110000000010001110110100110100", 253 => "110000000010001100100101001110", 254 => "110000000010001010100101101001", 255 => "110000000010001000010110000011"
  );
  -- @@TABLES_END@@

  -- 12-bit two-add value hash (inferno family), split across two stages
  function hash_a(cx, cy : unsigned(7 downto 0); seed : unsigned(15 downto 0))
    return unsigned is
    variable h16 : unsigned(15 downto 0);
    variable h : unsigned(11 downto 0);
  begin
    h16 := (cx & cy) xor seed;
    h16 := h16 xor (x"0" & h16(15 downto 4));
    h := h16(11 downto 0);
    return h + rotate_left(h, 5);
  end function;

  function hash_b(hin : unsigned(11 downto 0)) return unsigned is
    variable h : unsigned(11 downto 0);
  begin
    h := hin xor rotate_left(hin, 9);
    h := h + rotate_left(h, 3);
    h := h xor ("00000" & h(11 downto 5));
    return h(9 downto 2);
  end function;

  function mod3(d : unsigned(6 downto 0)) return unsigned is
  begin
    return C_MOD3(to_integer(d));
  end function;

  -- 4-bit cell -> 8-bit (x17)
  function x17(t : unsigned(3 downto 0)) return unsigned is
    variable r : unsigned(7 downto 0);
  begin
    r := t & t;
    return r;
  end function;

  -- grid-x address from a cell index (half mode: even columns)
  function gxa(x : unsigned(7 downto 0); half : std_logic) return unsigned is
    variable r : unsigned(7 downto 0);
  begin
    if half = '1' then r := x(6 downto 0) & '0'; else r := x; end if;
    return r;
  end function;

  -- ------------------------------------------------------------------
  -- Memories
  -- ------------------------------------------------------------------
  attribute ram_style : string;

  -- temperature grid 64 rows x 256 cells, 4-bit.  addr = row(6) & x(8)
  type t_grid is array(0 to 16383) of unsigned(3 downto 0);
  signal grid : t_grid := (others => (others => '0'));
  attribute ram_style of grid : signal is "block";
  signal g_raddr : unsigned(13 downto 0) := (others => '0');
  signal g_q, g_qf : unsigned(3 downto 0) := (others => '0');
  signal g_we : std_logic := '0';
  signal g_waddr : unsigned(13 downto 0) := (others => '0');
  signal g_wd : unsigned(3 downto 0) := (others => '0');

  -- new-row buffer (sim results for the row in progress), sim-x indexed
  type t_nrow is array(0 to 255) of unsigned(3 downto 0);
  signal nrow : t_nrow := (others => (others => '0'));
  attribute ram_style of nrow : signal is "block";
  signal nr_raddr : unsigned(7 downto 0) := (others => '0');
  signal nr_q, nr_qf : unsigned(3 downto 0) := (others => '0');
  signal nr_we : std_logic := '0';
  signal nr_waddr : unsigned(7 downto 0) := (others => '0');
  signal nr_wd : unsigned(3 downto 0) := (others => '0');

  -- display row cache: 3 slots x 256 cells (grid-x indexed).  addr = slot(2) & x(8)
  type t_cache is array(0 to 1023) of unsigned(3 downto 0);
  signal cache : t_cache := (others => (others => '0'));
  attribute ram_style of cache : signal is "block";
  signal c_raddr : unsigned(9 downto 0) := (others => '0');
  signal c_q, c_qf : unsigned(3 downto 0) := (others => '0');
  signal c_we : std_logic := '0';
  signal c_waddr : unsigned(9 downto 0) := (others => '0');
  signal c_wd : unsigned(3 downto 0) := (others => '0');

  -- Luma Mod fuel: per-cell luma averages (sim-x indexed), two banks by row parity
  type t_fuel is array(0 to 255) of unsigned(9 downto 0);
  signal fuel0 : t_fuel := (others => (others => '0'));
  signal fuel1 : t_fuel := (others => (others => '0'));
  attribute ram_style of fuel0 : signal is "block";
  attribute ram_style of fuel1 : signal is "block";
  signal f0_raddr, f1_raddr : unsigned(7 downto 0) := (others => '0');
  signal f0_q, f1_q, f0_qf, f1_qf : unsigned(9 downto 0) := (others => '0');
  signal f_we0, f_we1 : std_logic := '0';
  signal f_waddr : unsigned(7 downto 0) := (others => '0');
  signal f_wd : unsigned(9 downto 0) := (others => '0');

  -- input video delay for Overlay (32-bit words: 2 clean 16-bit halves)
  type t_vdly is array(0 to 31) of std_logic_vector(31 downto 0);
  signal vdly : t_vdly := (others => (others => '0'));
  attribute ram_style of vdly : signal is "block";
  signal vd_wptr : unsigned(4 downto 0) := (others => '0');
  signal vd_qa, vd_qb : std_logic_vector(31 downto 0) := (others => '0');

  -- ------------------------------------------------------------------
  -- Timing / per-field state
  -- ------------------------------------------------------------------
  signal sync_hs, sync_vs : std_logic_vector(C_LATENCY - 1 downto 0) := (others => '1');
  signal sync_avid : std_logic_vector(C_LATENCY - 1 downto 0) := (others => '0');
  signal s_prev_hsync_n, s_prev_vsync_n : std_logic := '1';
  signal s_saw_act : std_logic := '0';
  signal s_vsedge : std_logic;
  signal s_pixel_x : unsigned(11 downto 0) := (others => '0');
  signal s_wmeas : unsigned(11 downto 0) := to_unsigned(1920, 12);
  signal s_lcount : unsigned(11 downto 0) := (others => '0');
  signal s_lines : unsigned(11 downto 0) := to_unsigned(1080, 12);
  signal s_act_line : std_logic := '0';
  signal s_prev_avid : std_logic := '0';
  signal s_half : std_logic := '0';            -- half horizontal resolution (SD / 720p)
  signal s_xmask : unsigned(7 downto 0) := (others => '1');

  -- vertical DDA: grid row d + fraction for the current line
  signal s_yacc : unsigned(21 downto 0) := (others => '0');
  signal s_d : unsigned(5 downto 0) := (others => '0');
  signal s_rowfirst : std_logic := '0';
  signal s_ystep : std_logic := '0';
  signal s_wy : unsigned(6 downto 0) := (others => '0');
  signal s_slotA, s_slotB : unsigned(1 downto 0) := (others => '0');
  signal s_dpulse : std_logic := '0';
  signal s_dval : unsigned(6 downto 0) := (others => '0');

  -- switches
  signal s_ember, s_lumamod, s_blue, s_overlay, s_bypass : std_logic := '0';

  -- per-field constants (boost FSM)
  signal s_incx : unsigned(15 downto 0) := to_unsigned(8738, 16);   -- 256 cells / 1920 px
  signal s_incy : unsigned(15 downto 0) := to_unsigned(3701, 16);   -- 61 rows / 1080 lines
  signal s_wk : unsigned(6 downto 0) := to_unsigned(24, 7);          -- lattice x step per cell (1/16 cell)
  signal s_wk2 : unsigned(7 downto 0) := to_unsigned(48, 8);
  signal s_kt : unsigned(7 downto 0) := to_unsigned(32, 8);
  signal s_kb : unsigned(5 downto 0) := to_unsigned(32, 6);
  signal s_ke : unsigned(4 downto 0) := to_unsigned(16, 5);
  signal s_vb16 : unsigned(6 downto 0) := to_unsigned(21, 7);
  signal s_cbase : unsigned(5 downto 0) := to_unsigned(9, 6);
  signal s_samp : unsigned(7 downto 0) := to_unsigned(127, 8);      -- burner pocket / luma amplitude
  signal s_csm : unsigned(4 downto 0) := to_unsigned(8, 5);
  signal s_srcl : unsigned(7 downto 0) := to_unsigned(166, 8);
  signal s_sgain : unsigned(7 downto 0) := to_unsigned(128, 8);
  signal s_drift1, s_drift2 : unsigned(11 downto 0) := (others => '0');
  signal s_scroll1, s_scroll2 : unsigned(15 downto 0) := (others => '0');
  signal s_dofs : unsigned(7 downto 0) := (others => '0');          -- rounding-dither phase
  signal s_gcnt : unsigned(7 downto 0) := (others => '0');          -- fields until the next gust
  signal s_wtgt : signed(5 downto 0) := (others => '0');            -- gust target, 1/16 cell per field
  signal s_wacc : signed(9 downto 0) := (others => '0');            -- eased wind, 4 frac bits
  signal s_wind : signed(5 downto 0) := (others => '0');            -- wind, 1/16 cell per field
  signal s_fbk : unsigned(9 downto 0) := to_unsigned(659, 10);      -- K1 fuel scaled 0.86

  type t_bst is (BI, BM, BD1, BD2, BF, BF2);
  signal bst : t_bst := BI;
  signal b_p12 : unsigned(9 downto 0) := (others => '0');
  signal b_op : unsigned(9 downto 0) := (others => '0');
  signal b_bit : unsigned(3 downto 0) := (others => '0');
  signal b_acc : unsigned(19 downto 0) := (others => '0');
  signal b_fuel : unsigned(19 downto 0) := (others => '0');
  signal b_n : unsigned(24 downto 0) := (others => '0');
  signal b_dv : unsigned(11 downto 0) := to_unsigned(1920, 12);
  signal b_rem : unsigned(12 downto 0) := (others => '0');
  signal b_qt : unsigned(24 downto 0) := (others => '0');
  signal b_cnt : unsigned(4 downto 0) := (others => '0');

  signal s_lfsr_q : std_logic_vector(15 downto 0);   -- free-running (sim)
  signal s_lfsr_p : std_logic_vector(15 downto 0);   -- pixel-rate (display dither)

  -- ------------------------------------------------------------------
  -- Simulation sequencer
  -- ------------------------------------------------------------------
  type t_jst is (J_IDLE, J_PRE, J_CELLS);
  signal jst : t_jst := J_IDLE;
  signal j_chain, j_pendd : std_logic := '0';
  signal j_cnext : unsigned(6 downto 0) := (others => '0');
  signal j_pdval : unsigned(6 downto 0) := (others => '0');
  signal j_d : unsigned(6 downto 0) := (others => '0');
  signal j_prow : unsigned(5 downto 0) := (others => '0');
  signal j_slot : unsigned(1 downto 0) := (others => '0');
  signal j_r : unsigned(5 downto 0) := (others => '0');      -- sim row
  signal j_rw : unsigned(5 downto 0) := (others => '0');     -- write-back row
  signal j_simen, j_wben : std_logic := '0';
  signal j_px : unsigned(8 downto 0) := (others => '0');
  signal j_px1, j_px2, j_px3 : unsigned(7 downto 0) := (others => '0');
  signal j_pv1, j_pv2, j_pv3 : std_logic := '0';
  signal j_n : unsigned(8 downto 0) := (others => '0');      -- period 0..N+2
  signal j_nend : unsigned(8 downto 0) := to_unsigned(258, 9);
  signal j_pend : unsigned(8 downto 0) := to_unsigned(256, 9);
  signal st : unsigned(4 downto 0) := (others => '0');       -- step 0..19

  -- phase A (velocity) registers
  signal a_x : unsigned(7 downto 0) := (others => '0');      -- sim x of phase A
  signal b_x : unsigned(7 downto 0) := (others => '0');      -- sim x of phase B
  signal c_x : unsigned(7 downto 0) := (others => '0');      -- final-write cell (gathered 2 periods ago)
  signal w_x : unsigned(7 downto 0) := (others => '0');      -- write-back cell
  signal p1x, p2x : unsigned(11 downto 0) := (others => '0');
  signal p1y, p2y : unsigned(15 downto 0) := (others => '0');
  signal h_cx, h_cy : unsigned(7 downto 0) := (others => '0');
  signal h_seed : unsigned(15 downto 0) := (others => '0');
  signal h_a : unsigned(11 downto 0) := (others => '0');
  signal h_b : unsigned(7 downto 0) := (others => '0');
  signal lut_idx : unsigned(6 downto 0) := (others => '0');
  signal lut_q, lut_qf : unsigned(16 downto 0) := (others => '0');
  signal c00_1, c10_1, c01_1, c11_1 : unsigned(7 downto 0) := (others => '0');
  signal c00_2, c10_2, c01_2, c11_2 : unsigned(7 downto 0) := (others => '0');
  signal sx1, sy1, sx2, sy2 : unsigned(8 downto 0) := (others => '0');
  signal dx1, dy1, dx2, dy2 : unsigned(7 downto 0) := (others => '0');
  signal da1, da2 : signed(9 downto 0) := (others => '0');
  signal e10_1, e01_1, e10_2, e01_2 : signed(8 downto 0) := (others => '0');
  signal a1_8, b1_8, a2_8, b2_8 : signed(9 downto 0) := (others => '0');
  signal dpx1, dpy1 : signed(9 downto 0) := (others => '0');
  signal dpxs, dpys : signed(10 downto 0) := (others => '0');
  signal vbuoy : unsigned(7 downto 0) := (others => '0');
  signal ue : signed(8 downto 0) := (others => '0');
  signal tl, t0, tr : unsigned(3 downto 0) := (others => '0');
  signal dth, dthb, dthb2 : unsigned(7 downto 0) := (others => '0');
  signal u16 : signed(7 downto 0) := (others => '0');
  signal v16 : unsigned(6 downto 0) := (others => '0');
  signal ma_a : signed(10 downto 0) := (others => '0');
  signal ma_b : signed(9 downto 0) := (others => '0');
  signal ma_p : signed(20 downto 0) := (others => '0');
  signal ma_pl : signed(16 downto 0) := (others => '0');
  signal ma_ph : signed(15 downto 0) := (others => '0');

  -- phase B (gather / cooling / source) registers
  signal cb00, cb10, cb01, cb11 : unsigned(7 downto 0) := (others => '0');
  signal sxb, syb : unsigned(8 downto 0) := (others => '0');
  signal q0, q1 : unsigned(7 downto 0) := (others => '0');
  signal psi : unsigned(7 downto 0) := (others => '0');
  signal src : unsigned(7 downto 0) := (others => '0');
  signal fuelv : unsigned(7 downto 0) := (others => '0');
  signal lsrc : unsigned(7 downto 0) := (others => '0');
  signal gx : unsigned(7 downto 0) := (others => '0');
  signal gfx4, gfy4 : unsigned(3 downto 0) := (others => '0');
  signal gyi, gyi1 : unsigned(5 downto 0) := (others => '0');
  signal t00, t10, t01, t11 : unsigned(7 downto 0) := (others => '0');
  signal lt0, lt1 : unsigned(7 downto 0) := (others => '0');
  signal tadv : unsigned(7 downto 0) := (others => '0');
  signal tn1 : unsigned(7 downto 0) := (others => '0');
  signal mb_a : signed(9 downto 0) := (others => '0');
  signal mb_b : signed(9 downto 0) := (others => '0');
  signal mb_p : signed(19 downto 0) := (others => '0');
  signal mb_pl : signed(15 downto 0) := (others => '0');
  signal mb_ph : signed(14 downto 0) := (others => '0');

  -- ------------------------------------------------------------------
  -- Display pipeline
  -- ------------------------------------------------------------------
  signal x_acc : unsigned(23 downto 0) := (others => '0');
  signal cx1, cx1p : unsigned(7 downto 0) := (others => '0');
  signal fx1, fx2 : unsigned(7 downto 0) := (others => '0');
  signal d_y1 : unsigned(9 downto 0) := (others => '0');
  signal cr_ph : std_logic := '0';
  signal cr_pre : unsigned(3 downto 0) := to_unsigned(15, 4);
  signal cr_tag1, cr_tag2, cr_tag3 : unsigned(2 downto 0) := (others => '0');
  signal cr_v1, cr_v2, cr_v3 : std_logic := '0';
  signal curA, curB, nextA, nextB, nx2A, nx2B : unsigned(7 downto 0) := (others => '0');
  signal cA3, cB3, cA4, cB4 : unsigned(7 downto 0) := (others => '0');
  signal dA3, dB3 : signed(8 downto 0) := (others => '0');
  signal wx3 : unsigned(6 downto 0) := (others => '0');
  signal mA4, mB4 : signed(16 downto 0) := (others => '0');
  signal ha5, hb5 : unsigned(7 downto 0) := (others => '0');
  signal dv6 : signed(8 downto 0) := (others => '0');
  signal ha6 : unsigned(7 downto 0) := (others => '0');
  signal mv7 : signed(16 downto 0) := (others => '0');
  signal ha7 : unsigned(7 downto 0) := (others => '0');
  signal t8 : unsigned(7 downto 0) := (others => '0');
  signal pal9 : std_logic_vector(29 downto 0) := (others => '0');
  signal sm9 : unsigned(13 downto 0) := (others => '0');
  signal fire9, smk9 : std_logic := '0';
  signal pal10 : std_logic_vector(29 downto 0) := (others => '0');
  signal gray10 : unsigned(9 downto 0) := (others => '0');
  signal fire10, smk10 : std_logic := '0';
  signal y11, u11, v11, gray11 : unsigned(9 downto 0) := (others => '0');
  signal fire11, smk11 : std_logic := '0';
  signal y12, u12, v12 : unsigned(9 downto 0) := (others => '0');

  -- fuel accumulator (Luma Mod)
  signal f_acc : unsigned(9 downto 0) := (others => '0');
  signal f_next : unsigned(9 downto 0) := (others => '0');

begin

  lfsr_sim : entity work.lfsr16
    port map(clk => clk, enable => '1', seed => x"BEEF", load => '0', q => s_lfsr_q);
  lfsr_pix : entity work.lfsr16
    port map(clk => clk, enable => data_in.avid, seed => x"DEAD", load => '0', q => s_lfsr_p);

  s_vsedge <= '1' when data_in.vsync_n = '0' and s_prev_vsync_n = '1'
                       and s_saw_act = '1' else '0';

  -- ========================================================================
  -- Memories: canonical 1W1R, unconditional reads, fabric hop on outputs
  -- ========================================================================
  p_grid : process(clk)
  begin
    if rising_edge(clk) then
      if g_we = '1' then grid(to_integer(g_waddr)) <= g_wd; end if;
      g_q <= grid(to_integer(g_raddr));
      g_qf <= g_q;
    end if;
  end process;

  p_nrow : process(clk)
  begin
    if rising_edge(clk) then
      if nr_we = '1' then nrow(to_integer(nr_waddr)) <= nr_wd; end if;
      nr_q <= nrow(to_integer(nr_raddr));
      nr_qf <= nr_q;
    end if;
  end process;

  p_cache : process(clk)
  begin
    if rising_edge(clk) then
      if c_we = '1' then cache(to_integer(c_waddr)) <= c_wd; end if;
      c_q <= cache(to_integer(c_raddr));
      c_qf <= c_q;
    end if;
  end process;

  p_fuel0 : process(clk)
  begin
    if rising_edge(clk) then
      if f_we0 = '1' then fuel0(to_integer(f_waddr)) <= f_wd; end if;
      f0_q <= fuel0(to_integer(f0_raddr));
      f0_qf <= f0_q;
    end if;
  end process;

  p_fuel1 : process(clk)
  begin
    if rising_edge(clk) then
      if f_we1 = '1' then fuel1(to_integer(f_waddr)) <= f_wd; end if;
      f1_q <= fuel1(to_integer(f1_raddr));
      f1_qf <= f1_q;
    end if;
  end process;

  p_lut : process(clk)
  begin
    if rising_edge(clk) then
      lut_q <= C_SD(to_integer(lut_idx));
      lut_qf <= lut_q;
    end if;
  end process;

  -- ========================================================================
  -- Timing, measurement, vertical DDA, knob latch
  -- ========================================================================
  p_time : process(clk)
  begin
    if rising_edge(clk) then
      s_prev_hsync_n <= data_in.hsync_n;
      s_prev_vsync_n <= data_in.vsync_n;
      s_prev_avid <= data_in.avid;

      vdly(to_integer(vd_wptr)) <= "00" & data_in.y & data_in.u & data_in.v;
      vd_qa <= vdly(to_integer(vd_wptr - (C_LATENCY - 3)));
      vd_qb <= vd_qa;
      vd_wptr <= vd_wptr + 1;
      sync_hs   <= sync_hs(C_LATENCY - 2 downto 0) & data_in.hsync_n;
      sync_vs   <= sync_vs(C_LATENCY - 2 downto 0) & data_in.vsync_n;
      sync_avid <= sync_avid(C_LATENCY - 2 downto 0) & data_in.avid;

      s_dpulse <= '0';
      s_ystep <= '0';

      if data_in.avid = '1' then
        s_pixel_x <= s_pixel_x + 1;
        s_saw_act <= '1';
        s_act_line <= '1';
      elsif s_vsedge = '1' then
        s_saw_act <= '0';
      end if;

      if data_in.hsync_n = '0' and s_prev_hsync_n = '1' then
        if s_pixel_x /= 0 then s_wmeas <= s_pixel_x; end if;
        s_pixel_x <= (others => '0');
        s_rowfirst <= '0';
        if s_act_line = '1' then
          s_lcount <= s_lcount + 1;
          s_yacc <= s_yacc + resize(s_incy, 22);
          s_ystep <= '1';
        end if;
        s_act_line <= '0';
      end if;
      -- second cycle of the vertical DDA: derive row, weight, slots, change
      -- pulse from the registered accumulator (one cycle was the critical path)
      -- (the '0' default lives at the top of the process: placed here it
      -- overrode the hsync set and the row pointer never advanced -> black)
      if s_ystep = '1' then
        s_d <= s_yacc(21 downto 16);
        s_wy <= C_SS6(to_integer(s_yacc(15 downto 10)));
        s_slotA <= mod3("0" & s_yacc(21 downto 16));
        s_slotB <= mod3(("0" & s_yacc(21 downto 16)) + 1);
        if s_yacc(21 downto 16) /= s_d then
          s_rowfirst <= '1';
          s_dpulse <= '1';
          s_dval <= "0" & s_yacc(21 downto 16);
        end if;
      end if;

      if data_in.vsync_n = '0' and s_prev_vsync_n = '1' then
        s_ember   <= registers_in(6)(0);
        s_lumamod <= registers_in(6)(1);
        s_blue    <= registers_in(6)(2);
        s_overlay <= registers_in(6)(3);
        s_bypass  <= registers_in(6)(4);
      end if;

      if s_vsedge = '1' then
        if s_lcount > 100 then s_lines <= s_lcount; end if;
        s_lcount <= (others => '0');
        -- half horizontal resolution below 1536 px (SD, 720p)
        if s_wmeas < 1536 then
          s_half <= '1'; s_xmask <= x"7F";
        else
          s_half <= '0'; s_xmask <= x"FF";
        end if;
        s_yacc <= (others => '0');
        s_d <= (others => '0');
        s_wy <= (others => '0');
        s_slotA <= "00";
        s_slotB <= "01";
        s_rowfirst <= '1';
        s_dpulse <= '1';
        s_dval <= (others => '0');
      end if;
    end if;
  end process p_time;

  -- ========================================================================
  -- Per-field constants: one serial shift-add multiplier (P12 Blaze:
  -- (1023 - K1) x P12 blends the fuel from the knob toward the full-screen
  -- climax) + one serial restoring divider (x and y DDA increments from the
  -- measured width / line count), then derive.
  -- ========================================================================
  p_boost : process(clk)
    variable v_acc : unsigned(19 downto 0);
    variable v_rem : unsigned(13 downto 0);
    variable v_fb : unsigned(12 downto 0);
    variable v_t : unsigned(8 downto 0);
    variable v_qb : std_logic;
    variable v_k2 : unsigned(9 downto 0);
    variable v_k1 : unsigned(9 downto 0);
    variable v_gt : signed(5 downto 0);
  begin
    if rising_edge(clk) then
      case bst is
        when BI =>
          if s_vsedge = '1' then
            b_p12 <= unsigned(registers_in(7));
            -- K1 spans 0..86% of the raw fuel range (Ron: that is the right 0..100)
            v_k1 := unsigned(registers_in(0)) - resize(unsigned(registers_in(0)(9 downto 3)), 10)
                  - resize(unsigned(registers_in(0)(9 downto 6)), 10);
            s_fbk <= v_k1;
            b_op <= to_unsigned(1023, 10) - v_k1;
            -- turbulence gain (K4 512 -> 32) and base rise (K6 512 -> 21
            -- sixteenths of a cell per field) follow their knobs directly
            s_kt <= resize(unsigned(registers_in(3)(9 downto 4)), 8);
            s_vb16 <= resize(unsigned(registers_in(5)(9 downto 5)), 7) + 5;
            -- K2 Width: lattice x step per cell 16..47 sixteenths (1x .. 3x
            -- horizontal compression of the turbulence and burner pockets)
            v_k2 := unsigned(registers_in(1));
            s_wk <= resize(v_k2(9 downto 5), 7) + 16;
            s_wk2 <= (resize(v_k2(9 downto 5), 8) + 16) sll 1;
            -- K5 Plume: buoyancy + entrainment
            s_kb <= unsigned(registers_in(4)(9 downto 4));
            s_ke <= unsigned(registers_in(4)(9 downto 5));
            -- K3 Smoke: cool-regime decay (slow when high) and gray gain
            s_csm <= resize((to_unsigned(1023, 10) - unsigned(registers_in(2))) srl 6, 5) + 1;
            s_sgain <= unsigned(registers_in(2)(9 downto 2));
            b_bit <= "1001";
            b_acc <= (others => '0');
            bst <= BM;
          end if;
        when BM =>
          if b_p12(to_integer(b_bit)) = '1' then
            v_acc := (b_acc sll 1) + resize(b_op, 20);
          else
            v_acc := b_acc sll 1;
          end if;
          b_acc <= v_acc;
          if b_bit = 0 then
            b_fuel <= v_acc;
            -- divide 1: incx = cells * 2^16 / width (256, or 128 in half mode)
            if s_half = '1' then
              b_n <= to_unsigned(128, 25) sll 16;
            else
              b_n <= to_unsigned(256, 25) sll 16;
            end if;
            b_dv <= s_wmeas;
            b_rem <= (others => '0');
            b_qt <= (others => '0');
            b_cnt <= to_unsigned(24, 5);
            bst <= BD1;
          else
            b_bit <= b_bit - 1;
          end if;
        when BD1 | BD2 =>
          v_rem := (b_rem & b_n(24));
          b_n <= b_n sll 1;
          if v_rem >= resize(b_dv, 14) then
            b_rem <= resize(v_rem - resize(b_dv, 14), 13);
            b_qt <= b_qt(23 downto 0) & '1';
            v_qb := '1';
          else
            b_rem <= v_rem(12 downto 0);
            b_qt <= b_qt(23 downto 0) & '0';
            v_qb := '0';
          end if;
          if b_cnt = 0 then
            if bst = BD1 then
              s_incx <= b_qt(14 downto 0) & v_qb;
              bst <= BD2;
              -- divide 2: incy = 61 * 2^16 / lines (rows 62/63 = burner, off-screen)
              b_n <= to_unsigned(61, 25) sll 16;
              b_dv <= s_lines;
              b_rem <= (others => '0');
              b_qt <= (others => '0');
              b_cnt <= to_unsigned(24, 5);
            else
              s_incy <= b_qt(14 downto 0) & v_qb;
              bst <= BF;
            end if;
          else
            b_cnt <= b_cnt - 1;
          end if;
        when BF =>
          -- effective fuel = K1 + (1023 - K1) * P12 / 1024 (Blaze): cooling base
          -- 31..0 (0 = parcels only cool by T/32 + grain -> whole screen),
          -- burner level 32..255, burner pocket / luma amplitude 0.25x..1.25x
          v_fb := resize(s_fbk, 13) + resize(b_fuel(19 downto 10), 13);
          if v_fb > 1023 then v_fb := to_unsigned(1023, 13); end if;
          s_cbase <= resize((to_unsigned(1023, 10) - v_fb(9 downto 0)) srl 5, 6);
          v_t := resize(v_fb(9 downto 3), 9) + resize(v_fb(9 downto 3), 9) + 32;
          if v_t > 255 then v_t := to_unsigned(255, 9); end if;
          s_srcl <= v_t(7 downto 0);
          s_samp <= resize(v_fb(9 downto 3), 8) + 32;
          bst <= BF2;
        when BF2 =>
          -- advance the noise lattices: eddies ride up with the flow
          -- (separate state: the clamp->add chain was the critical path)
          s_scroll1 <= s_scroll1 + resize(s_vb16(6 downto 1), 16) + resize(s_vb16(6 downto 2), 16);
          s_scroll2 <= s_scroll2 + resize(s_vb16, 16) + resize(s_vb16(6 downto 2), 16);
          -- gusts: every 24..87 fields (0.4..1.5 s) draw a new wind target
          -- from a centre-weighted random (sum of two 4-bit LFSR nibbles - 15,
          -- scaled 3/4: -11..+11 sixteenths of a cell per field, straight most
          -- likely); the wind eases toward it (1/16 per field) and both lattice
          -- drifts ride it, so the fire leans left, right or stands straight
          if s_gcnt = 0 then
            v_gt := resize(signed(resize(unsigned(s_lfsr_q(3 downto 0)), 6))
                         + signed(resize(unsigned(s_lfsr_q(7 downto 4)), 6)) - 15, 6);
            s_wtgt <= v_gt - (v_gt sra 2);
            s_gcnt <= resize(unsigned(s_lfsr_q(13 downto 8)), 8) + 24;
          else
            s_gcnt <= s_gcnt - 1;
          end if;
          s_wacc <= s_wacc + (((resize(s_wtgt, 10) sll 4) - s_wacc) sra 4);
          s_wind <= s_wacc(9 downto 4);
          s_drift1 <= s_drift1 + unsigned(resize(s_wind sra 2, 12));
          s_drift2 <= s_drift2 + unsigned(resize(s_wind sra 2, 12))
                    + unsigned(resize(s_wind sra 3, 12));
          s_dofs <= s_dofs + 37;
          bst <= BI;
      end case;
    end if;
  end process p_boost;

  -- ========================================================================
  -- Simulation sequencer.  Job(d): prefetch grid row prow(d) into cache slot
  -- mod3(d+2); simulate row d-1 (phase A: velocity, phase B: gather/cool/
  -- burn, 20 clocks per cell, two cells in flight); write back row d-2 from
  -- the new-row buffer.  Jobs 64 and 65 run after vsync (row 63 + flush,
  -- prefetching rows 0 and 1 for the next field).
  -- ========================================================================
  p_seq : process(clk)
    variable v_d2 : unsigned(6 downto 0);
    variable v_nx : unsigned(7 downto 0);
    variable v_p1y, v_p2y : unsigned(15 downto 0);
    variable v_a : signed(17 downto 0);
    variable v_v : signed(12 downto 0);
    variable v_u : signed(12 downto 0);
    variable v_by : unsigned(10 downto 0);
    variable v_bx : unsigned(11 downto 0);
    variable v_l : unsigned(8 downto 0);
    variable v_cool : unsigned(8 downto 0);
    variable v_tn : unsigned(8 downto 0);
    variable v_sr : signed(10 downto 0);
    variable v_fl : signed(9 downto 0);
    variable v_q : unsigned(12 downto 0);
  begin
    if rising_edge(clk) then
      -- default strobes
      g_we <= '0';
      nr_we <= '0';
      c_we <= '0';

      -- pending-job bookkeeping
      -- after vsync: run every job the raster did not reach (the screen
      -- covers rows 0..61; rows 62/63 and the flush/prefetch jobs follow)
      if s_vsedge = '1' then j_chain <= '1'; j_cnext <= resize(s_d, 7) + 1; end if;
      if s_dpulse = '1' then j_pendd <= '1'; j_pdval <= s_dval; end if;

      -- multiplier pipelines: operands registered -> two partial products
      -- (low 5 / high 5 bits of the b operand) -> sum.  Latency 3.
      ma_pl <= ma_a * signed('0' & ma_b(4 downto 0));
      ma_ph <= ma_a * ma_b(9 downto 5);
      ma_p <= resize(ma_pl, 21) + shift_left(resize(ma_ph, 21), 5);
      mb_pl <= mb_a * signed('0' & mb_b(4 downto 0));
      mb_ph <= mb_a * mb_b(9 downto 5);
      mb_p <= resize(mb_pl, 20) + shift_left(resize(mb_ph, 20), 5);
      -- hash pipeline
      h_a <= hash_a(h_cx, h_cy, h_seed);
      h_b <= hash_b(h_a);

      case jst is
        when J_IDLE =>
          if j_chain = '1' or j_pendd = '1' then
            if j_chain = '1' then
              j_d <= j_cnext;
              v_d2 := j_cnext;
              j_cnext <= j_cnext + 1;
              if j_cnext >= 65 then j_chain <= '0'; end if;
            else
              j_d <= j_pdval; j_pendd <= '0';
              v_d2 := j_pdval;
            end if;
            -- prefetch row: d+2 (clamped 63 at the bottom; 0, 1 for jobs 64/65)
            if v_d2 = 64 then j_prow <= (others => '0');
            elsif v_d2 = 65 then j_prow <= to_unsigned(1, 6);
            elsif v_d2 >= 62 then j_prow <= to_unsigned(63, 6);
            else j_prow <= resize(v_d2 + 2, 6); end if;
            j_slot <= mod3(v_d2 + 2);
            -- sim row d-1, write-back row d-2
            j_r <= resize(v_d2 - 1, 6);
            j_rw <= resize(v_d2 - 2, 6);
            if v_d2 >= 1 and v_d2 <= 64 then j_simen <= '1'; else j_simen <= '0'; end if;
            if v_d2 >= 2 and v_d2 <= 65 then j_wben <= '1'; else j_wben <= '0'; end if;
            -- cell count for this field's resolution
            if s_half = '1' then
              j_pend <= to_unsigned(128, 9); j_nend <= to_unsigned(131, 9);
            else
              j_pend <= to_unsigned(256, 9); j_nend <= to_unsigned(259, 9);
            end if;
            j_px <= (others => '0');
            j_pv1 <= '0'; j_pv2 <= '0'; j_pv3 <= '0';
            jst <= J_PRE;
          end if;

        when J_PRE =>
          -- grid row -> cache slot, 3-deep address/valid pipe
          g_raddr <= j_prow & gxa(j_px(7 downto 0), s_half);
          j_px1 <= gxa(j_px(7 downto 0), s_half); j_px2 <= j_px1; j_px3 <= j_px2;
          if j_px < j_pend then j_pv1 <= '1'; j_px <= j_px + 1; else j_pv1 <= '0'; end if;
          j_pv2 <= j_pv1; j_pv3 <= j_pv2;
          c_we <= j_pv3;
          c_waddr <= j_slot & j_px3;
          c_wd <= g_qf;
          if j_px >= j_pend and j_pv1 = '0' and j_pv2 = '0' and j_pv3 = '0' then
            j_n <= (others => '0');
            st <= (others => '0');
            -- lattice x accumulators start at cell -2
            p1x <= s_drift1 - resize(s_wk2, 12);
            p2x <= s_drift2 - resize(s_wk2, 12);
            jst <= J_CELLS;
          end if;

        when J_CELLS =>
          -- period counter / step counter
          if st = 19 then
            st <= (others => '0');
            p1x <= p1x + resize(s_wk, 12);
            p2x <= p2x + resize(s_wk, 12);
            if j_n = j_nend then
              jst <= J_IDLE;
            else
              j_n <= j_n + 1;
            end if;
          else
            st <= st + 1;
          end if;

          -- ------------------------------------------------------------
          -- Phase A: curl-noise velocity for cell a_x (steps 0..19, spills
          -- into steps 0..7 of the next period).  Multiplier latency 3.
          -- ------------------------------------------------------------
          case to_integer(st) is
            when 0 =>
              -- neighbour read T(r, x+1) for the entrainment window
              v_nx := (a_x + 1) and s_xmask;
              g_raddr <= j_r & gxa(v_nx, s_half);
              v_p1y := resize(j_r & "0000", 16) - s_scroll1;
              v_p2y := resize(j_r & "0000", 16) - s_scroll2 + x"0450";
              p1y <= v_p1y; p2y <= v_p2y;
              -- entrainment window shift: T0 of this cell was last period's Tr
              tl <= t0; t0 <= tr;
              -- spill (previous cell): entrainment product (issued 17)
              ue <= ma_p(16 downto 8);
              ma_a <= resize(b2_8, 11); ma_b <= signed(resize(dy2, 10));
            when 1 =>
              h_cx <= "000" & p1x(11 downto 7); h_cy <= p1y(14 downto 7); h_seed <= x"1234";
              lut_idx <= p1x(6 downto 0);
            when 2 =>
              h_cx <= "000" & (p1x(11 downto 7) + 1); h_cy <= p1y(14 downto 7);
              lut_idx <= p1y(6 downto 0);
              -- spill: dpxs = dpx1 + dpx2 (A2_8*Dx2 issued 19)
              dpxs <= resize(dpx1, 11) + resize(ma_p(16 downto 7), 11);
            when 3 =>
              h_cx <= "000" & p1x(11 downto 7); h_cy <= p1y(14 downto 7) + 1;
              lut_idx <= p2x(5 downto 0) & '0';
              tr <= g_qf;
              -- spill: dpys = dpy1 + dpy2 (B2_8*Dy2 issued 0)
              dpys <= resize(dpy1, 11) + resize(ma_p(16 downto 7), 11);
              ma_a <= resize(dpxs, 11); ma_b <= signed(resize(s_kt, 10));
            when 4 =>
              h_cx <= "000" & (p1x(11 downto 7) + 1); h_cy <= p1y(14 downto 7) + 1;
              lut_idx <= p2y(5 downto 0) & '0';
              c00_1 <= h_b;
              sx1 <= lut_qf(16 downto 8); dx1 <= lut_qf(7 downto 0);
              ma_a <= resize(dpys, 11); ma_b <= signed(resize(s_kt, 10));
            when 5 =>
              h_cx <= "00" & p2x(11 downto 6); h_cy <= p2y(13 downto 6); h_seed <= x"8EEF";
              c10_1 <= h_b;
              sy1 <= lut_qf(16 downto 8); dy1 <= lut_qf(7 downto 0);
            when 6 =>
              h_cx <= "00" & (p2x(11 downto 6) + 1); h_cy <= p2y(13 downto 6);
              c01_1 <= h_b;
              sx2 <= lut_qf(16 downto 8); dx2 <= lut_qf(7 downto 0);
              -- spill: vertical velocity = buoyancy - kt * dpsi/dx, clamped 0..95
              v_v := signed(resize(vbuoy, 13)) - resize(ma_p(20 downto 8), 13);
              if v_v < 0 then v16 <= (others => '0');
              elsif v_v > 95 then v16 <= to_unsigned(95, 7);
              else v16 <= unsigned(v_v(6 downto 0)); end if;
            when 7 =>
              h_cx <= "00" & p2x(11 downto 6); h_cy <= p2y(13 downto 6) + 1;
              c11_1 <= h_b;
              sy2 <= lut_qf(16 downto 8); dy2 <= lut_qf(7 downto 0);
              -- spill: horizontal velocity = kt * dpsi/dy + entrainment, clamped
              v_u := resize(ue, 13) + resize(ma_p(20 downto 8), 13) + resize(s_wind, 13);
              if v_u < -127 then u16 <= to_signed(-127, 8);
              elsif v_u > 127 then u16 <= to_signed(127, 8);
              else u16 <= v_u(7 downto 0); end if;
            when 8 =>
              h_cx <= "00" & (p2x(11 downto 6) + 1); h_cy <= p2y(13 downto 6) + 1;
              c00_2 <= h_b;
              da1 <= (signed(resize(c11_1, 10)) - signed(resize(c01_1, 10)))
                   - (signed(resize(c10_1, 10)) - signed(resize(c00_1, 10)));
              e10_1 <= signed(resize(c10_1, 9)) - signed(resize(c00_1, 9));
              e01_1 <= signed(resize(c01_1, 9)) - signed(resize(c00_1, 9));
            when 9 =>
              -- per-cell rounding dither hash (fixed pattern + slow phase)
              h_cx <= a_x; h_cy <= "00" & j_r; h_seed <= x"5A5A";
              c10_2 <= h_b;
              ma_a <= resize(da1, 11); ma_b <= signed('0' & sy1);
            when 10 =>
              c01_2 <= h_b;
              ma_a <= resize(da1, 11); ma_b <= signed('0' & sx1);
            when 11 =>
              c11_2 <= h_b;
              ma_a <= signed(resize(x17(t0), 11)); ma_b <= signed(resize(s_kb, 10));
            when 12 =>
              dth <= h_b + s_dofs;
              da2 <= (signed(resize(c11_2, 10)) - signed(resize(c01_2, 10)))
                   - (signed(resize(c10_2, 10)) - signed(resize(c00_2, 10)));
              e10_2 <= signed(resize(c10_2, 9)) - signed(resize(c00_2, 9));
              e01_2 <= signed(resize(c01_2, 9)) - signed(resize(c00_2, 9));
              v_a := (resize(e10_1, 18) sll 8) + resize(ma_p, 18);
              a1_8 <= v_a(17 downto 8);
            when 13 =>
              v_a := (resize(e01_1, 18) sll 8) + resize(ma_p, 18);
              b1_8 <= v_a(17 downto 8);
              ma_a <= resize(a1_8, 11); ma_b <= signed(resize(dx1, 10));
            when 14 =>
              -- buoyancy: vb16 + T0*kb/256  (kb 63 -> 4 cells at T 255)
              vbuoy <= resize(s_vb16, 8) + resize(unsigned(ma_p(13 downto 8)), 8);
              ma_a <= resize(b1_8, 11); ma_b <= signed(resize(dy1, 10));
            when 15 =>
              ma_a <= resize(da2, 11); ma_b <= signed('0' & sy2);
            when 16 =>
              dpx1 <= ma_p(16 downto 7);
              ma_a <= resize(da2, 11); ma_b <= signed('0' & sx2);
            when 17 =>
              dpy1 <= ma_p(16 downto 7);
              ma_a <= resize(signed(resize(x17(tr), 9)) - signed(resize(x17(tl), 9)), 11);
              ma_b <= signed(resize(s_ke, 10));
            when 18 =>
              v_a := (resize(e10_2, 18) sll 8) + resize(ma_p, 18);
              a2_8 <= v_a(17 downto 8);
            when 19 =>
              v_a := (resize(e01_2, 18) sll 8) + resize(ma_p, 18);
              b2_8 <= v_a(17 downto 8);
              ma_a <= resize(a2_8, 11); ma_b <= signed(resize(dx2, 10));
              -- copies for phase B: octave-2 corners (burner), dither (2 deep)
              cb00 <= c00_2; cb10 <= c10_2; cb01 <= c01_2; cb11 <= c11_2;
              sxb <= sx2; syb <= sy2;
              dthb <= dth; dthb2 <= dthb;
            when others => null;
          end case;

          -- ------------------------------------------------------------
          -- Phase B: gather / cool / burn for cell b_x (= n-1 in period
          -- n+... : uses u16/v16 of the previous period's phase A from step
          -- 8), finishing at step 5 of the period after (cell a_x there).
          -- ------------------------------------------------------------
          case to_integer(st) is
            when 0 =>
              -- write-back of the previous row reads cell n-1: its NEW value
              -- lands at step 5 of period n+3, so the old row's value is still
              -- intact (reading n-3 fetched the finished new row -> the grid
              -- shifted up one row per field)
              nr_raddr <= w_x;
              -- late phase (cell c_x): vertical lerp of the gather
              mb_a <= signed(resize(lt1, 10)) - signed(resize(lt0, 10));
              mb_b <= signed(resize(gfy4, 10));
            when 1 =>
              mb_a <= signed(resize(cb10, 10)) - signed(resize(cb00, 10));
              mb_b <= signed('0' & sxb);
            when 2 =>
              mb_a <= signed(resize(cb11, 10)) - signed(resize(cb01, 10));
              mb_b <= signed('0' & sxb);
            when 3 =>
              -- write back last row's cell (read from the new-row buffer at 0)
              if j_wben = '1' and j_n >= 1 and j_n <= j_pend then
                g_we <= '1';
                g_waddr <= j_rw & gxa(w_x, s_half);
                g_wd <= nr_qf;
              end if;
              -- luma fuel for this cell (bank of the sim row = not the display row's)
              if j_d(0) = '1' then fuelv <= f0_qf(9 downto 2); else fuelv <= f1_qf(9 downto 2); end if;
              -- late phase: advected temperature
              v_l := unsigned(resize(signed(resize(lt0, 10)) + resize(mb_p(13 downto 4), 10), 9));
              tadv <= v_l(7 downto 0);
            when 4 =>
              -- half mode: the odd column is a copy
              if j_wben = '1' and j_n >= 1 and j_n <= j_pend and s_half = '1' then
                g_we <= '1';
                g_waddr <= j_rw & (w_x(6 downto 0) & '1');
                g_wd <= nr_qf;
              end if;
              q0 <= cb00 + unsigned(mb_p(15 downto 8));
              -- late phase: cooling (fire regime = base + T/32 + grain; smoke = csm + grain)
              if tadv >= 40 then
                v_cool := resize(s_cbase, 9) + resize(tadv(7 downto 5), 9)
                        + resize(unsigned(s_lfsr_q(11 downto 10)), 9);
              else
                v_cool := resize(s_csm, 9) + resize(unsigned(s_lfsr_q(11 downto 10)), 9);
              end if;
              if resize(tadv, 9) > v_cool then tn1 <= tadv - v_cool(7 downto 0);
              else tn1 <= (others => '0'); end if;
            when 5 =>
              q1 <= cb01 + unsigned(mb_p(15 downto 8));
              -- late phase: burner (bottom two rows) / Luma Mod fuel / embers
              v_tn := resize(tn1, 9);
              if s_lumamod = '1' then
                if lsrc > tn1 then v_tn := resize(lsrc, 9); end if;
              else
                if j_r = 63 then
                  if src > tn1 then v_tn := resize(src, 9); end if;
                elsif j_r = 62 then
                  if src > 32 and (src - 32) > tn1 then v_tn := resize(src - 32, 9); end if;
                end if;
              end if;
              if s_ember = '1' and s_lfsr_q(15 downto 5) = "00000000000" then
                v_tn := to_unsigned(200, 9);
              end if;
              -- the value finished here was gathered in the previous period for
              -- cell b_x = n-4 (writing it to a_x = n-2 shifted the whole field
              -- two cells to the right every field)
              if j_simen = '1' and j_n >= 4 and j_n <= j_pend + 3 then nr_we <= '1'; end if;
              nr_waddr <= c_x;
              -- stochastic rounding to 4 bits: (t*15 + dither) / 256
              v_q := resize(v_tn(7 downto 0) & "0000", 13) - resize(v_tn(7 downto 0), 13)
                   + resize(dthb2, 13);
              nr_wd <= v_q(11 downto 8);
            when 6 =>
              mb_a <= signed(resize(q1, 10)) - signed(resize(q0, 10));
              mb_b <= signed('0' & syb);
            when 7 =>
              -- Luma Mod injection: (luma8 - 96) * amp
              mb_a <= signed(resize(fuelv, 10)) - 96;
              mb_b <= signed(resize(s_samp, 10));
            when 8 =>
              -- back-trace: by = r*16 + v16 (down), bx = x*16 - u16
              v_by := resize(j_r & "0000", 11) + resize(v16, 11);
              if v_by(10 downto 4) > 63 then gyi <= to_unsigned(63, 6);
              else gyi <= v_by(9 downto 4); end if;
              if v_by(10 downto 4) >= 63 then gyi1 <= to_unsigned(63, 6);
              else gyi1 <= v_by(9 downto 4) + 1; end if;
              gfy4 <= v_by(3 downto 0);
              v_bx := unsigned(signed(resize(b_x & "0000", 12)) - resize(u16, 12));
              gx <= v_bx(11 downto 4) and s_xmask;
              gfx4 <= v_bx(3 downto 0);
            when 9 =>
              g_raddr <= gyi & gxa(gx, s_half);
              psi <= q0 + unsigned(mb_p(15 downto 8));
            when 10 =>
              g_raddr <= gyi & gxa((gx + 1) and s_xmask, s_half);
              -- luma injection = clamp((luma8-96)*amp/128, 0..255)
              v_fl := resize(mb_p(17 downto 7), 10);
              if v_fl < 0 then lsrc <= (others => '0');
              elsif v_fl > 255 then lsrc <= (others => '1');
              else lsrc <= unsigned(v_fl(7 downto 0)); end if;
              -- burner pocket term: (psi-128) * amp
              mb_a <= signed(resize(psi, 10)) - 128;
              mb_b <= signed(resize(s_samp, 10));
            when 11 =>
              g_raddr <= gyi1 & gxa(gx, s_half);
            when 12 =>
              g_raddr <= gyi1 & gxa((gx + 1) and s_xmask, s_half);
              t00 <= x17(g_qf);
            when 13 =>
              t10 <= x17(g_qf);
              -- burner level: srcl + (psi-128)*amp/128 + random 0..31
              v_sr := resize(signed(resize(s_srcl, 9)), 11)
                    + resize(mb_p(17 downto 7), 11)
                    + resize(signed(resize(unsigned(s_lfsr_q(4 downto 0)), 9)), 11);
              if v_sr < 0 then src <= (others => '0');
              elsif v_sr > 255 then src <= (others => '1');
              else src <= unsigned(v_sr(7 downto 0)); end if;
            when 14 =>
              t01 <= x17(g_qf);
              mb_a <= signed(resize(t10, 10)) - signed(resize(t00, 10));
              mb_b <= signed(resize(gfx4, 10));
            when 15 =>
              t11 <= x17(g_qf);
            when 16 =>
              mb_a <= signed(resize(t11, 10)) - signed(resize(t01, 10));
              mb_b <= signed(resize(gfx4, 10));
            when 17 =>
              v_l := unsigned(resize(signed(resize(t00, 10)) + resize(mb_p(13 downto 4), 10), 9));
              lt0 <= v_l(7 downto 0);
            when 19 =>
              v_l := unsigned(resize(signed(resize(t01, 10)) + resize(mb_p(13 downto 4), 10), 9));
              lt1 <= v_l(7 downto 0);
            when others => null;
          end case;
      end case;
    end if;
  end process p_seq;

  -- cell indices: phase A cell = n-2, phase B cell = n-3 (sim-x units)
  a_x <= resize(j_n - 2, 8) and s_xmask;
  b_x <= resize(j_n - 3, 8) and s_xmask;
  c_x <= resize(j_n - 4, 8) and s_xmask;      -- late-phase (final write) cell
  w_x <= resize(j_n - 1, 8) and s_xmask;      -- write-back cell

  -- fuel bank read addresses: the display's accumulator reads bank(d parity)
  -- one cell ahead, the sim reads the other bank at its own cell
  f0_raddr <= cx1 + 1 when s_d(0) = '0' else b_x;
  f1_raddr <= b_x when s_d(0) = '0' else cx1 + 1;

  -- ========================================================================
  -- Display stage 1: horizontal DDA, cache reader, fuel accumulator
  -- ========================================================================
  p_d1 : process(clk)
    variable v_xn : unsigned(23 downto 0);
    variable v_fd, v_fa : signed(10 downto 0);
    variable v_cross : std_logic;
  begin
    if rising_edge(clk) then
      -- --- horizontal DDA (restarts every line) ---
      if data_in.hsync_n = '0' and s_prev_hsync_n = '1' then
        x_acc <= (others => '0');
        cx1 <= (others => '0');
        cx1p <= (others => '0');
        cr_pre <= (others => '0');
      elsif data_in.avid = '1' then
        v_xn := x_acc + resize(s_incx, 24);
        x_acc <= v_xn;
        cx1 <= v_xn(23 downto 16);
        fx1 <= v_xn(15 downto 8);
      end if;
      d_y1 <= unsigned(data_in.y);
      cx1p <= cx1;
      v_cross := '0';
      if cx1 /= cx1p then v_cross := '1'; end if;
      fx2 <= fx1;

      -- --- cache reader: 6-read preload after hsync, then free-running cx+2 ---
      cr_ph <= not cr_ph;
      cr_v1 <= '0';
      if cr_pre /= 15 then
        -- preload: tags 0..5 = curA curB nextA nextB nx2A nx2B at cx0, cx0+1, cx0+2
        case cr_pre is
          when "0000" => c_raddr <= s_slotA & gxa(cx1, s_half); cr_tag1 <= "000"; cr_v1 <= '1';
          when "0001" => c_raddr <= s_slotB & gxa(cx1, s_half); cr_tag1 <= "001"; cr_v1 <= '1';
          when "0010" => c_raddr <= s_slotA & gxa(cx1 + 1, s_half); cr_tag1 <= "010"; cr_v1 <= '1';
          when "0011" => c_raddr <= s_slotB & gxa(cx1 + 1, s_half); cr_tag1 <= "011"; cr_v1 <= '1';
          when "0100" => c_raddr <= s_slotA & gxa(cx1 + 2, s_half); cr_tag1 <= "100"; cr_v1 <= '1';
          when "0101" => c_raddr <= s_slotB & gxa(cx1 + 2, s_half); cr_tag1 <= "101"; cr_v1 <= '1';
          when others => null;
        end case;
        cr_pre <= cr_pre + 1;
      else
        if cr_ph = '0' then
          c_raddr <= s_slotA & gxa(cx1 + 2, s_half); cr_tag1 <= "100";
        else
          c_raddr <= s_slotB & gxa(cx1 + 2, s_half); cr_tag1 <= "101";
        end if;
        cr_v1 <= '1';
      end if;
      cr_tag2 <= cr_tag1; cr_tag3 <= cr_tag2;
      cr_v2 <= cr_v1; cr_v3 <= cr_v2;

      -- crossing: shift the cell window (cur <- next <- next2)
      if v_cross = '1' and cr_pre = 15 then
        curA <= nextA; curB <= nextB;
        nextA <= nx2A; nextB <= nx2B;
      end if;
      -- returning reads (data valid 3 clocks after the address register)
      if cr_v3 = '1' then
        case cr_tag3 is
          when "000" => curA <= x17(c_qf);
          when "001" => curB <= x17(c_qf);
          when "010" => nextA <= x17(c_qf);
          when "011" => nextB <= x17(c_qf);
          when "100" => nx2A <= x17(c_qf);
          when others => nx2B <= x17(c_qf);
        end case;
      end if;

      -- --- Luma Mod fuel accumulator: one-pole IIR per cell, banked by row parity ---
      f_we0 <= '0'; f_we1 <= '0';
      if s_d(0) = '0' then f_next <= f0_qf; else f_next <= f1_qf; end if;
      if data_in.avid = '1' or s_prev_avid = '1' then
        if v_cross = '1' or (data_in.avid = '0' and s_prev_avid = '1') then
          -- commit the finished cell
          f_waddr <= cx1p;
          f_wd <= f_acc;
          if s_d(0) = '0' then f_we0 <= '1'; else f_we1 <= '1'; end if;
          if s_rowfirst = '1' then f_acc <= d_y1; else f_acc <= f_next; end if;
        else
          v_fd := signed(resize(d_y1, 11)) - signed(resize(f_acc, 11));
          v_fa := signed(resize(f_acc, 11)) + (v_fd sra 3);
          f_acc <= unsigned(v_fa(9 downto 0));
        end if;
      end if;
    end if;
  end process p_d1;

  -- ========================================================================
  -- Display stages 3..12: smoothstep bilinear, palette, compose
  -- ========================================================================
  p_d2 : process(clk)
    variable v_ha, v_hb, v_t : signed(10 downto 0);
    variable v_cu, v_cv : unsigned(10 downto 0);
  begin
    if rising_edge(clk) then
      -- c3: horizontal deltas + weight
      dA3 <= signed(resize(nextA, 9)) - signed(resize(curA, 9));
      dB3 <= signed(resize(nextB, 9)) - signed(resize(curB, 9));
      cA3 <= curA; cB3 <= curB;
      wx3 <= C_SS6(to_integer(fx2(7 downto 2)));
      -- c4: products
      mA4 <= dA3 * signed('0' & wx3);
      mB4 <= dB3 * signed('0' & wx3);
      cA4 <= cA3; cB4 <= cB3;
      -- c5: horizontal lerps
      v_ha := signed(resize(cA4, 11)) + resize(mA4(14 downto 6), 11);
      v_hb := signed(resize(cB4, 11)) + resize(mB4(14 downto 6), 11);
      ha5 <= unsigned(v_ha(7 downto 0));
      hb5 <= unsigned(v_hb(7 downto 0));
      -- c6: vertical delta
      dv6 <= signed(resize(hb5, 9)) - signed(resize(ha5, 9));
      ha6 <= ha5;
      -- c7: product with the per-line weight
      mv7 <= dv6 * signed('0' & s_wy);
      ha7 <= ha6;
      -- c8: temperature at this pixel
      v_t := signed(resize(ha7, 11)) + resize(mv7(14 downto 6), 11);
      t8 <= unsigned(v_t(7 downto 0));
      -- c9: palette ROM read; smoke gray product; flags
      pal9 <= C_PAL(to_integer(t8));
      sm9 <= t8(5 downto 0) * s_sgain;
      if t8 >= 40 then fire9 <= '1'; else fire9 <= '0'; end if;
      if t8 < 40 and t8 >= 4 then smk9 <= '1'; else smk9 <= '0'; end if;
      -- c10: fabric hop off the ROM; gray luma 64 + T*gain/64
      pal10 <= pal9;
      gray10 <= to_unsigned(64, 10) + resize(sm9(13 downto 6), 10);
      fire10 <= fire9; smk10 <= smk9;
      -- c11: colour (Blue Flame = negated chroma: yellow->blue, red->cyan)
      y11 <= unsigned(pal10(29 downto 20));
      v_cu := resize(unsigned(pal10(19 downto 10)), 11);
      v_cv := resize(unsigned(pal10(9 downto 0)), 11);
      if s_blue = '1' then
        v_cu := to_unsigned(1024, 11) - v_cu;
        v_cv := to_unsigned(1024, 11) - v_cv;
      end if;
      u11 <= v_cu(9 downto 0);
      v11 <= v_cv(9 downto 0);
      gray11 <= gray10;
      fire11 <= fire10; smk11 <= smk10;
    end if;
  end process p_d2;

  -- c12: compose + blanking gate
  p_out : process(clk)
    variable v_vy, v_vu, v_vv : unsigned(9 downto 0);
  begin
    if rising_edge(clk) then
      v_vy := unsigned(vd_qb(29 downto 20));
      v_vu := unsigned(vd_qb(19 downto 10));
      v_vv := unsigned(vd_qb( 9 downto  0));

      if sync_avid(C_LATENCY - 2) = '0' then
        -- BLANKING GATE: neutral black outside active video
        y12 <= to_unsigned(64, 10);
        u12 <= to_unsigned(512, 10);
        v12 <= to_unsigned(512, 10);
      elsif s_overlay = '1' then
        if fire11 = '1' then
          y12 <= y11; u12 <= u11; v12 <= v11;
        elsif smk11 = '1' and gray11 > (to_unsigned(80, 10)
                         + (unsigned(s_lfsr_p(1 downto 0)) & "00")) then
          -- smoke 50/50 with the video, chroma halfway to neutral
          y12 <= ('0' & gray11(9 downto 1)) + ('0' & v_vy(9 downto 1));
          u12 <= to_unsigned(256, 10) + ('0' & v_vu(9 downto 1));
          v12 <= to_unsigned(256, 10) + ('0' & v_vv(9 downto 1));
        else
          y12 <= v_vy; u12 <= v_vu; v12 <= v_vv;
        end if;
      else
        if smk11 = '1' and gray11 > y11 then
          y12 <= gray11;
          u12 <= to_unsigned(512, 10);
          v12 <= to_unsigned(512, 10);
        else
          y12 <= y11; u12 <= u11; v12 <= v11;
        end if;
      end if;
    end if;
  end process p_out;

  -- ========================================================================
  -- Output
  -- ========================================================================
  data_out.y <= data_in.y when s_bypass = '1' else std_logic_vector(y12);
  data_out.u <= data_in.u when s_bypass = '1' else std_logic_vector(u12);
  data_out.v <= data_in.v when s_bypass = '1' else std_logic_vector(v12);
  data_out.hsync_n <= data_in.hsync_n when s_bypass = '1' else sync_hs(C_LATENCY - 1);
  data_out.vsync_n <= data_in.vsync_n when s_bypass = '1' else sync_vs(C_LATENCY - 1);
  data_out.field_n <= data_in.field_n;
  data_out.avid    <= data_in.avid when s_bypass = '1' else sync_avid(C_LATENCY - 1);

end architecture pyre;
