-- AUTO-GENERATED by oubliette.py - do not edit by hand.
-- 16 tiles x 16 rows x 16 bits.  MSB = leftmost pixel.
-- fg/bg palette stored U/V-swapped for the Videomancer hardware convention.
library ieee;
use ieee.std_logic_1164.all;

package oubliette_tiles_pkg is

    constant C_NTILES : integer := 16;
    constant C_TILE_W : integer := 16;
    constant C_TILE_H : integer := 16;

    constant C_T_FLOOR  : integer := 0;
    constant C_T_WALL   : integer := 1;
    constant C_T_DOOR   : integer := 2;
    constant C_T_STAIRS : integer := 3;
    constant C_T_WATER  : integer := 4;
    constant C_T_RUBBLE : integer := 5;
    constant C_T_WALL2  : integer := 6;
    constant C_T_CHEST  : integer := 7;
    constant C_T_WEAPON : integer := 8;
    constant C_T_GRASS  : integer := 9;
    constant C_T_SAND   : integer := 10;
    constant C_T_CRACKED : integer := 11;
    constant C_T_PILLAR : integer := 12;
    constant C_T_BONES  : integer := 13;
    constant C_T_MOSS   : integer := 14;
    constant C_T_LAVA   : integer := 15;

    type t_tile_rom is array (0 to C_NTILES - 1, 0 to C_TILE_H - 1)
        of std_logic_vector(C_TILE_W - 1 downto 0);

    type t_pal is array (0 to C_NTILES - 1) of integer range 0 to 1023;

    constant C_TILES : t_tile_rom := (
         0 => (x"FFFF", x"8001", x"8411", x"8001", x"8081", x"9002", x"8001", x"8021", x"8401", x"8001", x"8041", x"9002", x"8001", x"8109", x"8001", x"FFFF"),  -- FLOOR
         1 => (x"FBDF", x"EF7D", x"BDEF", x"F7EF", x"DEF7", x"FBDF", x"EF77", x"BDF7", x"F7BF", x"DF7B", x"FBBF", x"EF7B", x"BDF7", x"F7BB", x"DEF7", x"FBDF"),  -- WALL
         2 => (x"0000", x"7FFE", x"4002", x"5FFA", x"500A", x"500A", x"518A", x"53CA", x"518A", x"500A", x"500A", x"5FFA", x"4002", x"7FFE", x"0000", x"0000"),  -- DOOR
         3 => (x"0000", x"3FFC", x"2004", x"2FF4", x"2814", x"2BD4", x"2A54", x"2A54", x"2BD4", x"2814", x"2FF4", x"2004", x"3FFC", x"0000", x"0000", x"0000"),  -- STAIRS
         4 => (x"0000", x"638C", x"9833", x"0000", x"38E3", x"C60C", x"0000", x"638C", x"9833", x"0000", x"38E3", x"C60C", x"0000", x"638C", x"9833", x"0000"),  -- WATER
         5 => (x"0000", x"1838", x"3C7C", x"3C7C", x"701C", x"00C0", x"31E3", x"79E7", x"7807", x"00C0", x"19E6", x"3DEF", x"3C0F", x"0000", x"0630", x"0F78"),  -- RUBBLE
         6 => (x"FFFF", x"DF7D", x"DF7D", x"FFFF", x"FBEF", x"FBEF", x"FFFF", x"DF7D", x"DF7D", x"FFFF", x"FBEF", x"FBEF", x"FFFF", x"DF7D", x"DF7D", x"FFFF"),  -- WALL2
         7 => (x"0000", x"0000", x"3FF0", x"4008", x"8004", x"BFF4", x"A014", x"BFFC", x"A314", x"A794", x"A314", x"BFFC", x"8004", x"4008", x"3FF0", x"0000"),  -- CHEST
         8 => (x"0002", x"0007", x"000E", x"001C", x"0038", x"0070", x"00E0", x"01C0", x"0380", x"0700", x"7F00", x"7700", x"1C00", x"1C00", x"0800", x"0000"),  -- WEAPON
         9 => (x"0000", x"2108", x"739C", x"2108", x"0000", x"0420", x"0E70", x"0420", x"0000", x"2108", x"739C", x"2108", x"0000", x"0420", x"0E70", x"0000"),  -- GRASS
        10 => (x"2211", x"0842", x"4210", x"1085", x"8421", x"2108", x"0842", x"4210", x"1085", x"8421", x"2108", x"0842", x"4210", x"1085", x"8421", x"2108"),  -- SAND
        11 => (x"FFFF", x"8401", x"8401", x"8439", x"87E5", x"8025", x"8043", x"8081", x"F901", x"8A01", x"8419", x"8425", x"8443", x"8481", x"8401", x"FFFF"),  -- CRACKED
        12 => (x"0FC0", x"1FE0", x"3FF0", x"3870", x"3870", x"3FF0", x"1FE0", x"3FF0", x"3870", x"3870", x"3870", x"3870", x"3FF0", x"1FE0", x"3FF0", x"0FC0"),  -- PILLAR
        13 => (x"0000", x"0FC0", x"1020", x"2CD0", x"2CD0", x"2110", x"2790", x"1020", x"0CC0", x"0780", x"C003", x"781E", x"1E78", x"07E0", x"C003", x"781E"),  -- BONES
        14 => (x"6666", x"F7BE", x"6666", x"0000", x"CCCC", x"F7BC", x"CCCC", x"0000", x"6666", x"F7BE", x"6666", x"0000", x"CCCC", x"F7BC", x"CCCC", x"0000"),  -- MOSS
        15 => (x"30E1", x"79F3", x"30E1", x"0000", x"E30E", x"F79F", x"E30E", x"0000", x"3860", x"7CF0", x"3860", x"0000", x"E1C7", x"F3EF", x"E1C7", x"0000")   -- LAVA
    );

    constant C_TILE_FG_Y : t_pal := (407, 272, 478, 871, 592, 479, 634, 788, 912, 587, 774, 416, 709, 890, 500, 679);
    constant C_TILE_FG_U : t_pal := (542, 530, 657, 563, 365, 537, 535, 637, 497, 368, 572, 536, 533, 529, 378, 757);
    constant C_TILE_FG_V : t_pal := (468, 495, 342, 315, 694, 477, 466, 235, 536, 371, 374, 481, 479, 476, 424, 228);
    constant C_TILE_BG_Y : t_pal := (214, 124, 187, 161, 235, 189, 310, 327, 334, 260, 525, 213, 219, 205, 227, 272);
    constant C_TILE_BG_U : t_pal := (531, 521, 562, 523, 430, 526, 502, 622, 531, 481, 566, 526, 522, 526, 487, 718);
    constant C_TILE_BG_V : t_pal := (487, 505, 461, 489, 642, 496, 477, 395, 487, 469, 410, 496, 497, 496, 479, 386);

end package oubliette_tiles_pkg;
