-- AUTO-GENERATED by oubliette.py - do not edit by hand.
-- 11 sprites x 16 rows x 16 bits.  MSB = leftmost pixel.
-- 1-bpp masks; bit=1 -> fg colour, bit=0 -> transparent.
-- fg palette stored U/V-swapped for the Videomancer hardware convention.
library ieee;
use ieee.std_logic_1164.all;

package oubliette_sprites_pkg is

    constant C_NSPR : integer := 11;
    constant C_SPR_W : integer := 16;
    constant C_SPR_H : integer := 16;

    constant C_S_PLAYER_WAR : integer := 0;
    constant C_S_PLAYER_MAG : integer := 1;
    constant C_S_PLAYER_ROG : integer := 2;
    constant C_S_PLAYER_CLR : integer := 3;
    constant C_S_RAT        : integer := 4;
    constant C_S_SKELETON   : integer := 5;
    constant C_S_SLIME      : integer := 6;
    constant C_S_BAT        : integer := 7;
    constant C_S_ORC        : integer := 8;
    constant C_S_WRAITH     : integer := 9;
    constant C_S_CHEST      : integer := 10;

    type t_spr_rom is array (0 to C_NSPR - 1, 0 to C_SPR_H - 1)
        of std_logic_vector(C_SPR_W - 1 downto 0);
    type t_spal is array (0 to C_NSPR - 1) of integer range 0 to 1023;

    constant C_SPRITES : t_spr_rom := (
         0 => (x"03C0", x"0420", x"03C4", x"030C", x"07EC", x"0994", x"118C", x"118C", x"0184", x"03C0", x"05A0", x"05A0", x"0180", x"0240", x"0660", x"0000"),  -- PLAYER_WAR
         1 => (x"0100", x"0380", x"07C0", x"0FE0", x"03C0", x"0240", x"03C4", x"07E4", x"0994", x"0184", x"03C4", x"05A4", x"0180", x"0240", x"0660", x"0000"),  -- PLAYER_MAG
         2 => (x"0000", x"03C0", x"07E0", x"0420", x"05A0", x"03C0", x"23C4", x"27E4", x"2994", x"05A0", x"0180", x"03C0", x"0420", x"0420", x"0C30", x"0000"),  -- PLAYER_ROG
         3 => (x"03C0", x"0420", x"03C0", x"0240", x"03C4", x"07E4", x"0994", x"1188", x"0184", x"03C4", x"05A4", x"05A0", x"0180", x"0240", x"0660", x"0000"),  -- PLAYER_CLR
         4 => (x"0000", x"0000", x"001C", x"0062", x"3C42", x"43BC", x"4001", x"4442", x"3BBC", x"0440", x"0C60", x"0000", x"0000", x"0000", x"0000", x"0000"),  -- RAT
         5 => (x"03C0", x"0420", x"05A0", x"0420", x"03C0", x"0180", x"1FF8", x"25A4", x"23C4", x"03C0", x"05A0", x"05A0", x"05A0", x"0C30", x"0000", x"0000"),  -- SKELETON
         6 => (x"0000", x"0000", x"07E0", x"1FF8", x"3FFC", x"7B6E", x"7FFE", x"6FF6", x"7FFE", x"7FFE", x"3FFC", x"1FF8", x"742E", x"0000", x"0000", x"0000"),  -- SLIME
         7 => (x"0000", x"0000", x"43C2", x"67E6", x"77EE", x"7FFE", x"5BDA", x"0BD0", x"05A0", x"03C0", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000"),  -- BAT
         8 => (x"03C0", x"0420", x"05A0", x"07E0", x"03C0", x"1FF8", x"2BD4", x"2BD4", x"0FF0", x"0420", x"0C30", x"0810", x"1818", x"1008", x"0000", x"0000"),  -- ORC
         9 => (x"0180", x"03C0", x"05A0", x"0420", x"0DB0", x"0810", x"13C8", x"17E8", x"17E8", x"17E8", x"0BD0", x"0AA0", x"0540", x"0280", x"0000", x"0000"),  -- WRAITH
        10 => (x"0000", x"0000", x"1FF8", x"2004", x"2FF4", x"3FFC", x"27E4", x"2814", x"2BD4", x"2814", x"3FFC", x"2004", x"1FF8", x"0000", x"0000", x"0000")   -- CHEST
    );

    constant C_SPR_Y : t_spal := (442, 498, 613, 843, 497, 862, 668, 509, 525, 819, 727);
    constant C_SPR_U : t_spal := (798, 414, 332, 583, 615, 527, 351, 606, 409, 429, 651);
    constant C_SPR_V : t_spal := (387, 763, 393, 308, 401, 479, 339, 689, 386, 559, 238);

end package oubliette_sprites_pkg;
