-- humid_vapor: Humid Vapor
-- Keyed on luma, horizontal sine wave, 8-colour palette, LFO crossfades them, P12 fades back to the source.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/humid_vapor.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   ctl_key_level control       1 ->   2
--   ctl_key_soft control       1 ->   2
--   ctl_lfo_speed control       1 ->   2
--   ctl_wave_freq control       1 ->   2
--   key        threshold     1 ->   4
--   p12        control       1 ->   2
--   glide      glide         1 ->   2
--   ramp       hramp         1 ->   2
--   sw_lfo_shape control       1 ->   2
--   lfo        lfo           1 ->   3
--   osc        osc           2 ->   5
--   pal        colorizer     5 ->   7
--   mix        mix           7 ->  11
--   wet        mix          11 ->  15
--   vout       video_out    15 ->  16
-- Program latency: 16 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   vin.out          34-bit, delayed by 4 / 6 / 10 clocks (340 FF)
-- Chroma of key is never consumed downstream; synthesis removes it.
-- Controls:
--   K1   registers_in(0)     Key Level
--   K2   registers_in(1)     Key Soft
--   K4   registers_in(3)     LFO Speed
--   K3   registers_in(2)     Wave Freq
--   P12  registers_in(7)     Dry/Wet
--   S7   registers_in(6)(0)  LFO Shape
-- Estimate: 3754 LC (48.9 %), 0 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture humid_vapor of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_ctl_key_level_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_key_soft_value   : unsigned(10 - 1 downto 0);
  signal s_ctl_lfo_speed_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_wave_freq_value  : unsigned(10 - 1 downto 0);
  signal s_key_out              : t_vm_stream;
  signal s_key_mask             : unsigned(10 - 1 downto 0);
  signal s_p12_value            : unsigned(10 - 1 downto 0);
  signal s_glide_value          : unsigned(10 - 1 downto 0);
  signal s_ramp_ramp            : unsigned(10 - 1 downto 0);
  signal s_sw_lfo_shape_value   : unsigned(10 - 1 downto 0);
  signal s_lfo_value            : unsigned(10 - 1 downto 0);
  signal s_osc_wave             : unsigned(10 - 1 downto 0);
  signal s_pal_out              : t_vm_stream;
  signal s_mix_out              : t_vm_stream;
  signal s_wet_out              : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_vin_out_d4           : t_vm_stream;
  signal s_vin_out_d6           : t_vm_stream;
  signal s_vin_out_d10          : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- ctl_key_level (K1: Key Level)
  u_ctl_key_level : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0),
              o_value => s_ctl_key_level_value);

  -- ctl_key_soft (K2: Key Soft)
  u_ctl_key_soft : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1),
              o_value => s_ctl_key_soft_value);

  -- ctl_lfo_speed (K4: LFO Speed)
  u_ctl_lfo_speed : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3),
              o_value => s_ctl_lfo_speed_value);

  -- ctl_wave_freq (K3: Wave Freq)
  u_ctl_wave_freq : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2),
              o_value => s_ctl_wave_freq_value);

  -- key (Threshold)
  u_key : entity work.vm_threshold
    generic map (G_CHANNEL => 0, G_SOFT => true)
    port map (clk => clk, i_stream => s_vin_out, i_level => s_ctl_key_level_value,
              i_soft => s_ctl_key_soft_value, o_stream => s_key_out, o_mask => s_key_mask);

  -- p12 (P12: Dry/Wet)
  u_p12 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(7),
              o_value => s_p12_value);

  -- glide (Glide)
  u_glide : entity work.vm_glide
    generic map (G_SHIFT => 3)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_p12_value,
              o_value => s_glide_value);

  -- ramp (H Ramp)
  u_ramp : entity work.vm_hramp
    generic map (G_FRAC => 7, G_WRAP => true)
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_ctl_wave_freq_value,
              i_offset => to_unsigned(0, 10), o_ramp => s_ramp_ramp);

  -- sw_lfo_shape (S7: LFO Shape)
  u_sw_lfo_shape : entity work.vm_control
    generic map (G_BIT => 0, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6),
              o_value => s_sw_lfo_shape_value);

  -- lfo (LFO)
  u_lfo : entity work.vm_lfo
    generic map (G_PHASE_BITS => 14, G_ROM_STYLE => "logic")
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_ctl_lfo_speed_value,
              i_shape => s_sw_lfo_shape_value(9 downto 8), o_value => s_lfo_value);

  -- osc (Oscillator)
  u_osc : entity work.vm_osc
    generic map (G_ADDR_BITS => 8, G_FREQ_SHIFT => 0, G_ROM_STYLE => "logic")
    port map (clk => clk, i_theta => s_ramp_ramp, i_phase => s_lfo_value, o_wave => s_osc_wave);
  u_dly_vin_out_4 : entity work.vm_delay_stream generic map (G_DELAY => 4)
    port map (clk => clk, i_stream => s_vin_out, o_stream => s_vin_out_d4);
  u_dly_vin_out_6 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_vin_out_d4, o_stream => s_vin_out_d6);
  u_dly_vin_out_10 : entity work.vm_delay_stream generic map (G_DELAY => 4)
    port map (clk => clk, i_stream => s_vin_out_d6, o_stream => s_vin_out_d10);

  -- pal (Colorizer)
  u_pal : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 3,
                 G_PALETTE => "11d24b1c129115828e16c2651aa29115828e1bb28019429115828e20a29a17d29115828e")
    port map (clk => clk, i_stream => s_vin_out_d4, i_index => s_osc_wave, o_stream => s_pal_out);

  -- mix (Mix)
  u_mix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 6)
    port map (clk => clk, i_a => s_vin_out_d6, i_b => s_pal_out, i_amount => s_lfo_value,
              o_stream => s_mix_out);

  -- wet (Mix)
  u_wet : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 4)
    port map (clk => clk, i_a => s_vin_out_d10, i_b => s_mix_out, i_amount => s_glide_value,
              o_stream => s_wet_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_wet_out, o_data => data_out);
end architecture humid_vapor;
