-- DVD Logo Bouncer (multi-logo)
--
-- Up to 4 instances of a 384 x 174 1-bit "DVD VIDEO" bitmap drift across the
-- screen, bouncing off the active-area edges and off each other (rectangle
-- AABB collision).  Each wall hit and each logo-on-logo collision advances
-- that logo's color index through an 8-color palette.
--
-- The bitmap lives in dvdlogo_logo_pkg.C_LOGO_ROM (auto-generated by
-- dvdlogo.py from dvd_logo_source.png), shared across all instances.
-- Address = row * 24 + (col >> 4); leftmost pixel of each word is the MSB.
-- Yosys infers ~17 iCE40 BRAMs.
--
-- Bitmap access — streaming prefetch.  Each logo consumes one 16-bit ROM
-- word per 16 pixels, so the single ROM read port is round-robined across
-- the 4 logos (slot = h_count mod 4).  Each slot fetches, 8 px ahead of the
-- beam, the word that logo is about to need into a 2-entry (even/odd word
-- index) per-logo buffer.  Every logo therefore has its own bitmap bit at
-- every pixel: overlapping logos no longer occlude each other with the
-- black rectangle of their bounding box — only lit glyph pixels count.
-- (Caveat: no prefetch slots exist left of h_count 0, so while a logo is
-- within ~8 px of the LEFT wall its first word can be one line stale — a
-- few-pixel sliver, only during wall contact.)
--
-- Overlap behavior (S11):
--   Bounce : pairwise AABB collision physics as before; where logos overlap
--            visually, the lowest-index LIT logo wins the color.
--   Mix    : logos pass through each other; where lit glyph pixels overlap
--            their palette colors mix additively (Y sums, U/V offsets sum,
--            both clamped).
--
-- Physics (4-phase FSM, runs once per vsync):
--   Phase 0 (vsync_start) : predict each logo's new position
--   Phase 1               : clamp + wall bounce
--   Phase 2               : pairwise AABB overlap checks (6 pairs for N=4)
--                           — forced to no-hit in Mix mode
--   Phase 3               : aggregate per-logo collision flag, flip both
--                           sign bits of bumped logos, advance their colors,
--                           commit positions
--
-- Render pipeline (per pixel):
--   1 clk : timing_gen
--   1 clk : pixel_counter
--   1 clk : S1  — register coords + per-logo bbox snapshot + active mask
--   1 clk : S2a — 4 x (dx, dy) deltas
--   1 clk : S2b — 4 x in_bbox flags AND per-logo bitmap bit → lit flags
--   1 clk : S3  — gate per-logo palette contributions by lit flags
--   1 clk : S4  — pairwise sums + pairwise priority selects
--   1 clk : S5  — Bounce: priority pick / Mix: final sum + clamp
--   1 clk : S6  — output alignment
--   4 clk : interpolator
--   2 clk : IO alignment
--   total : 9 render + 4 interp + 2 IO = 15 clocks
--
-- Parameters:
--   reg(0)    : X Spd     (top 4 bits + 1 = 1..16 px/frame X magnitude)
--   reg(1)    : Y Spd     (top 4 bits + 1 = 1..16 px/frame Y magnitude)
--   reg(2)    : Count     (top 2 bits → 1, 2, 3 or 4 active logos)
--   reg(3)    : Clr Step  (top 3 bits + 1: amount color index advances)
--   reg(4)    : Tint      (top 3 bits: rotates the 8-color palette)
--   reg(5)    : Bright    (10-bit Y level used in mono mode)
--   reg(6)(0) : Color     (0 = mono, 1 = palette)
--   reg(6)(1) : Matte     (1 = logo cuts through to underlying video)
--   reg(6)(2) : BG        (0 = passthrough, 1 = solid black)
--   reg(6)(3) : Pause     (1 = freeze position + color)
--   reg(6)(4) : Overlap   (0 = logos bounce off each other, 1 = pass
--                          through + colors mix where glyphs overlap)
--   reg(7)    : Mix       (wet/dry mix amount)

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.all;
use work.core_pkg.all;
use work.video_timing_pkg.all;
use work.dvdlogo_logo_pkg.all;

architecture dvdlogo of program_top is

    -- ========================================================================
    -- Constants
    -- ========================================================================
    constant C_CHROMA_MID : unsigned(9 downto 0) := to_unsigned(512, 10);
    constant C_DELAY      : integer := 9;       -- 1 timing + 1 px_ctr + 7 stages
    constant N_LOGOS      : integer := 4;
    constant N_PAIRS      : integer := 6;       -- C(4,2) = 6

    constant C_BX_HIGH    : integer := 8;       -- bx is 9 bits (0..383)
    constant C_BY_HIGH    : integer := 7;       -- by is 8 bits (0..173)
    constant C_WBIT_BITS  : integer := 4;       -- 4-bit selector inside 16-bit word

    -- Pair index → (i, j).  Pair k covers (i_of(k), j_of(k)) with i < j.
    type t_pair_idx is array (0 to N_PAIRS - 1) of integer range 0 to N_LOGOS - 1;
    constant C_PAIR_I : t_pair_idx := (0, 0, 0, 1, 1, 2);
    constant C_PAIR_J : t_pair_idx := (1, 2, 3, 2, 3, 3);

    -- ========================================================================
    -- Per-logo state types
    -- ========================================================================
    type t_pos_arr   is array (0 to N_LOGOS - 1) of signed(11 downto 0);
    type t_pos13_arr is array (0 to N_LOGOS - 1) of signed(12 downto 0);
    type t_color_arr is array (0 to N_LOGOS - 1) of unsigned(2 downto 0);

    -- ========================================================================
    -- Parameters
    -- ========================================================================
    signal s_xspeed_pot : unsigned(9 downto 0);
    signal s_yspeed_pot : unsigned(9 downto 0);
    signal s_count_raw  : unsigned(9 downto 0);
    signal s_step_pot   : unsigned(9 downto 0);
    signal s_tint_pot   : unsigned(9 downto 0);
    signal s_bright_pot : unsigned(9 downto 0);
    signal s_color_mode : std_logic;
    signal s_matte      : std_logic;
    signal s_bg_black   : std_logic;
    signal s_pause      : std_logic;
    signal s_mix_logos  : std_logic;    -- 0 = bounce off each other, 1 = mix
    signal s_mix_amount : unsigned(9 downto 0);

    -- 2-bit count = (s_count_raw[9:8]); active mask = "i <= count"
    signal s_count    : unsigned(1 downto 0);
    signal s_active   : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');

    signal s_step     : unsigned(3 downto 0);
    signal s_tint     : unsigned(2 downto 0);
    signal s_vx_mag   : unsigned(4 downto 0);
    signal s_vy_mag   : unsigned(4 downto 0);

    -- ========================================================================
    -- Timing + auto-measured resolution
    -- ========================================================================
    signal s_timing  : t_video_timing_port;
    signal s_h_count : unsigned(11 downto 0);
    signal s_v_count : unsigned(11 downto 0);

    signal s_h_active        : integer range 0 to 4095;
    signal s_v_active        : integer range 0 to 4095;
    signal s_h_pixel_counter : unsigned(11 downto 0) := (others => '0');
    signal s_v_line_counter  : unsigned(11 downto 0) := (others => '0');
    signal s_measured_h      : unsigned(11 downto 0) := to_unsigned(960, 12);
    signal s_measured_v      : unsigned(11 downto 0) := to_unsigned(1080, 12);

    -- Pre-registered max bounce positions = active - logo_size, clamped >= 0.
    -- Read by physics phase 0 so the subtract isn't on its critical path.
    signal s_max_pos_x : signed(12 downto 0) := to_signed(0, 13);
    signal s_max_pos_y : signed(12 downto 0) := to_signed(0, 13);

    -- ========================================================================
    -- Logo dimensions (constant, no scaling in multi-logo build)
    -- ========================================================================
    constant C_LOGO_W_S : signed(12 downto 0) := to_signed(C_LOGO_W, 13);
    constant C_LOGO_H_S : signed(12 downto 0) := to_signed(C_LOGO_H, 13);

    -- ========================================================================
    -- Initial state — laid out as a 2x2 grid that's well-separated at HD
    -- (1920x1080).  At lower resolutions the clamp brings them in but they
    -- still occupy distinct quadrants.  Inactive logos hold these values so
    -- that turning Count up always introduces a new logo at a clean spot.
    -- ========================================================================
    constant C_INIT_X : t_pos_arr := (
        to_signed(  96, 12),
        to_signed(1440, 12),
        to_signed(  96, 12),
        to_signed(1440, 12)
    );
    constant C_INIT_Y : t_pos_arr := (
        to_signed( 64, 12),
        to_signed( 64, 12),
        to_signed(800, 12),
        to_signed(800, 12)
    );
    -- vx/vy direction so each logo heads toward screen-center.
    constant C_INIT_VX : std_logic_vector(0 to N_LOGOS - 1) := "1010";
    constant C_INIT_VY : std_logic_vector(0 to N_LOGOS - 1) := "1100";
    constant C_INIT_COLOR : t_color_arr := (
        "000",  -- white
        "001",  -- red
        "100",  -- green
        "110"   -- blue
    );

    signal s_logo_x    : t_pos_arr := C_INIT_X;
    signal s_logo_y    : t_pos_arr := C_INIT_Y;
    signal s_vx_sign   : std_logic_vector(0 to N_LOGOS - 1) := C_INIT_VX;
    signal s_vy_sign   : std_logic_vector(0 to N_LOGOS - 1) := C_INIT_VY;
    signal s_color_idx : t_color_arr := C_INIT_COLOR;

    -- ========================================================================
    -- Physics FSM intermediates
    -- ========================================================================
    -- Phase: 0 = idle/predict (vsync_start), 1 = clamp, 2 = pair check,
    --        3 = commit
    signal s_ph_phase : unsigned(1 downto 0) := "00";

    -- Phase 0 → 1 handoff: raw (unclamped) predicted positions.  Splitting
    -- predict vs. clamp into separate cycles keeps each cycle's combinational
    -- chain short (one 13-bit add, then one 13-bit compare, separately).
    signal s_pred_raw_x : t_pos13_arr := (others => (others => '0'));
    signal s_pred_raw_y : t_pos13_arr := (others => (others => '0'));

    -- Phase 1 → 2 handoff: clamped positions + signs + wall-bounce flags.
    signal s_pred_x   : t_pos13_arr := (others => (others => '0'));
    signal s_pred_y   : t_pos13_arr := (others => (others => '0'));
    signal s_pred_vx  : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');
    signal s_pred_vy  : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');
    signal s_wall_bp  : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');

    -- Per-pair collision flag (registered between phase 2 and phase 3)
    signal s_pair_hit     : std_logic_vector(0 to N_PAIRS - 1) := (others => '0');
    -- Previous frame's collision state, used for edge-detection so a pair
    -- that's been stuck overlapping doesn't keep flipping signs each frame.
    signal s_was_colliding : std_logic_vector(0 to N_PAIRS - 1) := (others => '0');

    -- ========================================================================
    -- Render pipeline registers
    -- ========================================================================
    -- S1
    signal s_stg1_hx     : signed(11 downto 0) := (others => '0');
    signal s_stg1_vy     : signed(11 downto 0) := (others => '0');
    signal s_bnd_x       : t_pos_arr   := (others => (others => '0'));
    signal s_bnd_y       : t_pos_arr   := (others => (others => '0'));
    signal s_bnd_active  : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');

    -- S2a — register dx[i], dy[i] (one 13-bit subtract per axis per logo)
    type t_dx_arr is array (0 to N_LOGOS - 1) of signed(12 downto 0);
    signal s_stg2a_dx     : t_dx_arr := (others => (others => '0'));
    signal s_stg2a_dy     : t_dx_arr := (others => (others => '0'));
    signal s_stg2a_active : std_logic_vector(0 to N_LOGOS - 1)
                            := (others => '0');

    -- S2b — per-logo lit flags (in_bbox AND that logo's bitmap bit)
    signal s_stg2_lit : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');

    -- ========================================================================
    -- Streaming ROM prefetch — slot i (h_count mod 4) fetches logo i's word
    -- 8 px ahead of the beam into a 2-entry (word-index parity) buffer.
    -- PF0: bxf/byf deltas  PF1: validity + word address  PF2: ROM read
    -- PF3: buffer write.
    -- ========================================================================
    type t_word2   is array (0 to 1) of
                      std_logic_vector(C_LOGO_WORD_W - 1 downto 0);
    type t_buf_arr is array (0 to N_LOGOS - 1) of t_word2;
    signal s_pf_buf : t_buf_arr := (others => (others => (others => '0')));

    signal s_pf0_bxf : signed(12 downto 0) := (others => '0');
    signal s_pf0_byf : signed(12 downto 0) := (others => '0');
    signal s_pf0_idx : unsigned(1 downto 0) := (others => '0');

    signal s_pf1_addr  : unsigned(12 downto 0) := (others => '0');
    signal s_pf1_par   : std_logic := '0';
    signal s_pf1_idx   : unsigned(1 downto 0) := (others => '0');
    signal s_pf1_valid : std_logic := '0';

    signal s_pf2_word  : std_logic_vector(C_LOGO_WORD_W - 1 downto 0)
                         := (others => '0');
    signal s_pf2_par   : std_logic := '0';
    signal s_pf2_idx   : unsigned(1 downto 0) := (others => '0');
    signal s_pf2_valid : std_logic := '0';

    -- ========================================================================
    -- Per-frame palette registers — one (Y, U-offset, V-offset) per logo,
    -- refreshed continuously from color_idx + tint (changes only at vsync).
    -- Mono mode substitutes Bright / zero offsets so Mix just sums brightness.
    -- ========================================================================
    type t_paly_arr   is array (0 to N_LOGOS - 1) of unsigned(9 downto 0);
    type t_paloff_arr is array (0 to N_LOGOS - 1) of signed(10 downto 0);
    signal s_pal_y  : t_paly_arr   := (others => (others => '0'));
    signal s_pal_uo : t_paloff_arr := (others => (others => '0'));
    signal s_pal_vo : t_paloff_arr := (others => (others => '0'));

    -- S3 — gated per-logo contributions
    signal s_stg3_y   : t_paly_arr   := (others => (others => '0'));
    signal s_stg3_uo  : t_paloff_arr := (others => (others => '0'));
    signal s_stg3_vo  : t_paloff_arr := (others => (others => '0'));
    signal s_stg3_lit : std_logic_vector(0 to N_LOGOS - 1) := (others => '0');

    -- S4 — pairwise sums (Mix) + pairwise priority selects (Bounce)
    signal s_stg4_ysum01, s_stg4_ysum23 : unsigned(10 downto 0)
                                          := (others => '0');
    signal s_stg4_uo01,   s_stg4_uo23   : signed(11 downto 0)
                                          := (others => '0');
    signal s_stg4_vo01,   s_stg4_vo23   : signed(11 downto 0)
                                          := (others => '0');
    signal s_stg4_sely01, s_stg4_sely23 : unsigned(9 downto 0)
                                          := (others => '0');
    signal s_stg4_seluo01, s_stg4_seluo23 : signed(10 downto 0)
                                            := (others => '0');
    signal s_stg4_selvo01, s_stg4_selvo23 : signed(10 downto 0)
                                            := (others => '0');
    signal s_stg4_lit01, s_stg4_lit23   : std_logic := '0';
    signal s_stg4_any                   : std_logic := '0';

    -- S5
    signal s_stg5_y    : unsigned(9 downto 0) := (others => '0');
    signal s_stg5_u    : unsigned(9 downto 0) := C_CHROMA_MID;
    signal s_stg5_v    : unsigned(9 downto 0) := C_CHROMA_MID;
    signal s_stg5_show : std_logic := '0';

    -- S6 — output alignment
    signal s_out_y    : unsigned(9 downto 0) := (others => '0');
    signal s_out_u    : unsigned(9 downto 0) := C_CHROMA_MID;
    signal s_out_v    : unsigned(9 downto 0) := C_CHROMA_MID;
    signal s_out_show : std_logic := '0';

    -- Wet pixel mux
    signal s_wet_y : std_logic_vector(9 downto 0);
    signal s_wet_u : std_logic_vector(9 downto 0);
    signal s_wet_v : std_logic_vector(9 downto 0);

    -- ========================================================================
    -- Sync + data delay
    -- ========================================================================
    -- Sync pipe: 9 render + 4 interp = 13 entries (indexed 0..12)
    type t_sync_pipe is array (0 to 12) of std_logic_vector(3 downto 0);
    signal s_sync_pipe : t_sync_pipe := (others => (others => '0'));

    type t_data_delay is array (0 to C_DELAY - 1) of std_logic_vector(9 downto 0);
    signal s_y_delay : t_data_delay := (others => (others => '0'));
    signal s_u_delay : t_data_delay := (others => (others => '0'));
    signal s_v_delay : t_data_delay := (others => (others => '0'));

    -- ========================================================================
    -- Mix outputs
    -- ========================================================================
    signal s_mix_y_result, s_mix_u_result, s_mix_v_result : unsigned(9 downto 0);
    signal s_mix_y_valid,  s_mix_u_valid,  s_mix_v_valid  : std_logic;

    signal s_io_0 : t_video_stream_yuv444_30b;
    signal s_io_1 : t_video_stream_yuv444_30b;

    -- ========================================================================
    -- 8-color palette lookup functions (Y, U, V at 10 bit)
    -- ========================================================================
    function f_pal_y(c : unsigned(2 downto 0)) return unsigned is
    begin
        case c is
            when "000"  => return to_unsigned(940, 10);
            when "001"  => return to_unsigned(290, 10);
            when "010"  => return to_unsigned(550, 10);
            when "011"  => return to_unsigned(870, 10);
            when "100"  => return to_unsigned(620, 10);
            when "101"  => return to_unsigned(820, 10);
            when "110"  => return to_unsigned(170, 10);
            when others => return to_unsigned(440, 10);
        end case;
    end function;

    function f_pal_u(c : unsigned(2 downto 0)) return unsigned is
    begin
        case c is
            when "000"  => return to_unsigned(512, 10);
            when "001"  => return to_unsigned(425, 10);
            when "010"  => return to_unsigned(350, 10);
            when "011"  => return to_unsigned(130, 10);
            when "100"  => return to_unsigned(195, 10);
            when "101"  => return to_unsigned(600, 10);
            when "110"  => return to_unsigned(880, 10);
            when others => return to_unsigned(850, 10);
        end case;
    end function;

    function f_pal_v(c : unsigned(2 downto 0)) return unsigned is
    begin
        case c is
            when "000"  => return to_unsigned(512, 10);
            when "001"  => return to_unsigned(900, 10);
            when "010"  => return to_unsigned(750, 10);
            when "011"  => return to_unsigned(560, 10);
            when "100"  => return to_unsigned(143, 10);
            when "101"  => return to_unsigned(128, 10);
            when "110"  => return to_unsigned(580, 10);
            when others => return to_unsigned(900, 10);
        end case;
    end function;

begin

    -- ========================================================================
    -- Auto-Measure Active Resolution
    -- ========================================================================
    p_measure : process(clk)
    begin
        if rising_edge(clk) then
            if s_timing.hsync_start = '1' then
                if s_h_pixel_counter > 0 then
                    s_measured_h <= s_h_pixel_counter;
                end if;
                s_h_pixel_counter <= (others => '0');
            elsif s_timing.avid = '1' then
                s_h_pixel_counter <= s_h_pixel_counter + 1;
            end if;

            if s_timing.vsync_start = '1' then
                if s_v_line_counter > 0 then
                    s_measured_v <= s_v_line_counter;
                end if;
                s_v_line_counter <= (others => '0');
            elsif s_timing.avid_start = '1' then
                s_v_line_counter <= s_v_line_counter + 1;
            end if;
        end if;
    end process;

    p_resolution : process(clk)
    begin
        if rising_edge(clk) then
            s_h_active <= to_integer(s_measured_h);
            s_v_active <= to_integer(s_measured_v);

            -- Continuously refresh max-position bounds.  At any supported
            -- resolution h_active >= 720 and v_active >= 240 — both larger
            -- than the 384x174 logo — so no clamp-to-zero is needed.
            s_max_pos_x <= signed(resize(s_measured_h, 13)) - C_LOGO_W_S;
            s_max_pos_y <= signed(resize(s_measured_v, 13)) - C_LOGO_H_S;
        end if;
    end process;

    -- ========================================================================
    -- Register Mapping
    -- ========================================================================
    s_xspeed_pot <= unsigned(registers_in(0));
    s_yspeed_pot <= unsigned(registers_in(1));
    s_count_raw  <= unsigned(registers_in(2));
    s_step_pot   <= unsigned(registers_in(3));
    s_tint_pot   <= unsigned(registers_in(4));
    s_bright_pot <= unsigned(registers_in(5));
    s_color_mode <= registers_in(6)(0);
    s_matte      <= registers_in(6)(1);
    s_bg_black   <= registers_in(6)(2);
    s_pause      <= registers_in(6)(3);
    s_mix_logos  <= registers_in(6)(4);
    s_mix_amount <= unsigned(registers_in(7));

    s_count <= s_count_raw(9 downto 8);
    s_tint  <= s_tint_pot(9 downto 7);

    p_speed : process(clk)
    begin
        if rising_edge(clk) then
            s_vx_mag <= resize(s_xspeed_pot(9 downto 6), 5) + to_unsigned(1, 5);
            s_vy_mag <= resize(s_yspeed_pot(9 downto 6), 5) + to_unsigned(1, 5);
        end if;
    end process;

    p_step : process(clk)
    begin
        if rising_edge(clk) then
            s_step <= resize(s_step_pot(9 downto 7), 4) + to_unsigned(1, 4);
        end if;
    end process;

    -- Active mask: logo i is active when i <= count.
    p_active : process(clk)
    begin
        if rising_edge(clk) then
            for i in 0 to N_LOGOS - 1 loop
                if to_unsigned(i, 2) <= s_count then
                    s_active(i) <= '1';
                else
                    s_active(i) <= '0';
                end if;
            end loop;
        end if;
    end process;

    -- ========================================================================
    -- Video Timing Generator + Pixel Counter
    -- ========================================================================
    timing_gen_inst : entity work.video_timing_generator
        port map (
            clk         => clk,
            ref_hsync_n => data_in.hsync_n,
            ref_vsync_n => data_in.vsync_n,
            ref_avid    => data_in.avid,
            timing      => s_timing
        );

    pixel_counter_inst : entity work.pixel_counter
        port map (
            clk     => clk,
            timing  => s_timing,
            h_count => s_h_count,
            v_count => s_v_count
        );

    -- ========================================================================
    -- Physics — 4-phase FSM
    --   Phase 0 (idle/predict): on vsync_start, add velocity to position,
    --     register raw (unclamped) prediction.  Just sign-mux + 13-bit add.
    --   Phase 1 (clamp)        : compare against [0, max_pos], clamp,
    --     register clamped pos + flipped sign + wall-bounce flag.
    --   Phase 2 (pair detect)  : 6 parallel AABB overlap checks → pair flags.
    --   Phase 3 (commit)       : OR-aggregate per-logo, flip signs of bumped
    --     logos, advance colors, commit positions.  Returns to phase 0.
    -- ========================================================================
    p_physics : process(clk)
        variable v_dx, v_dy       : signed(12 downto 0);
        variable v_new_x, v_new_y : signed(12 downto 0);
        variable v_vxs, v_vys     : std_logic;
        variable v_bp             : std_logic;
        variable v_collide        : std_logic_vector(0 to N_LOGOS - 1);
        variable v_i, v_j         : integer range 0 to N_LOGOS - 1;
    begin
        if rising_edge(clk) then
            case to_integer(s_ph_phase) is

                -- ----------------------------------------------------
                -- Phase 0: predict (one sign-mux + 13-bit add per axis)
                -- ----------------------------------------------------
                when 0 =>
                    if s_timing.vsync_start = '1' and s_pause = '0' then
                        for i in 0 to N_LOGOS - 1 loop
                            if s_vx_sign(i) = '1' then
                                v_dx := signed(resize(s_vx_mag, 13));
                            else
                                v_dx := -signed(resize(s_vx_mag, 13));
                            end if;
                            if s_vy_sign(i) = '1' then
                                v_dy := signed(resize(s_vy_mag, 13));
                            else
                                v_dy := -signed(resize(s_vy_mag, 13));
                            end if;

                            s_pred_raw_x(i) <= resize(s_logo_x(i), 13) + v_dx;
                            s_pred_raw_y(i) <= resize(s_logo_y(i), 13) + v_dy;
                        end loop;
                        s_ph_phase <= to_unsigned(1, 2);
                    end if;

                -- ----------------------------------------------------
                -- Phase 1: clamp + sign flip on wall hit
                -- ----------------------------------------------------
                when 1 =>
                    for i in 0 to N_LOGOS - 1 loop
                        v_new_x := s_pred_raw_x(i);
                        v_new_y := s_pred_raw_y(i);
                        v_vxs   := s_vx_sign(i);
                        v_vys   := s_vy_sign(i);
                        v_bp    := '0';

                        if v_new_x <= to_signed(0, 13) then
                            v_new_x := to_signed(0, 13);
                            v_vxs   := '1';
                            v_bp    := '1';
                        elsif v_new_x >= s_max_pos_x then
                            v_new_x := s_max_pos_x;
                            v_vxs   := '0';
                            v_bp    := '1';
                        end if;
                        if v_new_y <= to_signed(0, 13) then
                            v_new_y := to_signed(0, 13);
                            v_vys   := '1';
                            v_bp    := '1';
                        elsif v_new_y >= s_max_pos_y then
                            v_new_y := s_max_pos_y;
                            v_vys   := '0';
                            v_bp    := '1';
                        end if;

                        s_pred_x(i)  <= v_new_x;
                        s_pred_y(i)  <= v_new_y;
                        s_pred_vx(i) <= v_vxs;
                        s_pred_vy(i) <= v_vys;
                        s_wall_bp(i) <= v_bp;
                    end loop;
                    s_ph_phase <= to_unsigned(2, 2);

                -- ----------------------------------------------------
                -- Phase 2: pairwise AABB overlap detect.  In Mix mode
                -- logos pass through each other: no hits registered.
                -- ----------------------------------------------------
                when 2 =>
                    for k in 0 to N_PAIRS - 1 loop
                        v_i := C_PAIR_I(k);
                        v_j := C_PAIR_J(k);
                        if s_mix_logos = '0' and
                           s_active(v_i) = '1' and s_active(v_j) = '1' and
                           s_pred_x(v_i) + C_LOGO_W_S > s_pred_x(v_j) and
                           s_pred_x(v_i) < s_pred_x(v_j) + C_LOGO_W_S and
                           s_pred_y(v_i) + C_LOGO_H_S > s_pred_y(v_j) and
                           s_pred_y(v_i) < s_pred_y(v_j) + C_LOGO_H_S then
                            s_pair_hit(k) <= '1';
                        else
                            s_pair_hit(k) <= '0';
                        end if;
                    end loop;
                    s_ph_phase <= to_unsigned(3, 2);

                -- ----------------------------------------------------
                -- Phase 3: aggregate (edge-detect), flip, commit.
                --   Active logos:   commit predicted state, flip signs only
                --                    on the rising edge of a pair collision
                --                    (so logos stuck overlapping don't
                --                    oscillate every frame).
                --   Inactive logos: hold at initial state so that turning
                --                    Count up makes a logo appear cleanly.
                -- ----------------------------------------------------
                when 3 =>
                    v_collide := (others => '0');
                    for k in 0 to N_PAIRS - 1 loop
                        if s_pair_hit(k) = '1' and s_was_colliding(k) = '0' then
                            v_collide(C_PAIR_I(k)) := '1';
                            v_collide(C_PAIR_J(k)) := '1';
                        end if;
                    end loop;

                    for i in 0 to N_LOGOS - 1 loop
                        if s_active(i) = '1' then
                            s_logo_x(i) <= resize(s_pred_x(i), 12);
                            s_logo_y(i) <= resize(s_pred_y(i), 12);
                            if v_collide(i) = '1' then
                                s_vx_sign(i) <= not s_pred_vx(i);
                                s_vy_sign(i) <= not s_pred_vy(i);
                            else
                                s_vx_sign(i) <= s_pred_vx(i);
                                s_vy_sign(i) <= s_pred_vy(i);
                            end if;
                            if s_wall_bp(i) = '1' or v_collide(i) = '1' then
                                s_color_idx(i) <= s_color_idx(i)
                                                  + s_step(2 downto 0);
                            end if;
                        else
                            -- Inactive: park at initial state.  When the
                            -- user raises Count, this logo enters the
                            -- screen at a known non-overlapping spot.
                            s_logo_x(i)    <= C_INIT_X(i);
                            s_logo_y(i)    <= C_INIT_Y(i);
                            s_vx_sign(i)   <= C_INIT_VX(i);
                            s_vy_sign(i)   <= C_INIT_VY(i);
                            s_color_idx(i) <= C_INIT_COLOR(i);
                        end if;
                    end loop;

                    -- Save current pair_hit for next frame's edge detect.
                    s_was_colliding <= s_pair_hit;

                    s_ph_phase <= to_unsigned(0, 2);

                when others =>
                    s_ph_phase <= to_unsigned(0, 2);
            end case;
        end if;
    end process;

    -- ========================================================================
    -- Per-frame palette registers.  color_idx only changes at vsync, so the
    -- per-pixel path never touches the 8-entry LUT — it just gates these
    -- pre-resolved (Y, U-offset, V-offset) values.  Mono mode substitutes
    -- Bright with zero chroma offsets.
    -- ========================================================================
    p_palette : process(clk)
        variable v_eff : unsigned(2 downto 0);
    begin
        if rising_edge(clk) then
            for i in 0 to N_LOGOS - 1 loop
                v_eff := s_color_idx(i) + s_tint;
                if s_color_mode = '1' then
                    s_pal_y(i)  <= f_pal_y(v_eff);
                    s_pal_uo(i) <= signed(resize(f_pal_u(v_eff), 11))
                                   - to_signed(512, 11);
                    s_pal_vo(i) <= signed(resize(f_pal_v(v_eff), 11))
                                   - to_signed(512, 11);
                else
                    s_pal_y(i)  <= s_bright_pot;
                    s_pal_uo(i) <= (others => '0');
                    s_pal_vo(i) <= (others => '0');
                end if;
            end loop;
        end if;
    end process;

    -- ========================================================================
    -- Streaming ROM prefetch.  Slot i = h_count mod 4 serves logo i; each
    -- slot computes the word that logo needs 8 px ahead of the beam and
    -- fetches it into s_pf_buf(i)(word-index parity).  A word is consumed
    -- for 16 px and refreshed at most every 4, so the double buffer always
    -- holds the current word by the time the render pipeline samples it.
    -- ========================================================================
    p_prefetch : process(clk)
        variable v_i     : integer range 0 to N_LOGOS - 1;
        variable v_valid : std_logic;
        variable v_by    : unsigned(7 downto 0);
    begin
        if rising_edge(clk) then
            -- PF0: per-slot deltas (13-bit add/subtract only)
            v_i := to_integer(s_h_count(1 downto 0));
            s_pf0_bxf <= signed(resize(s_h_count, 13)) + to_signed(8, 13)
                         - resize(s_logo_x(v_i), 13);
            s_pf0_byf <= signed(resize(s_v_count, 13))
                         - resize(s_logo_y(v_i), 13);
            s_pf0_idx <= s_h_count(1 downto 0);

            -- PF1: bounds check + word address (by * 24 + bxf >> 4)
            if s_pf0_bxf >= to_signed(0, 13) and s_pf0_bxf < C_LOGO_W_S and
               s_pf0_byf >= to_signed(0, 13) and s_pf0_byf < C_LOGO_H_S then
                v_valid := '1';
            else
                v_valid := '0';
            end if;

            if v_valid = '1' then
                v_by := unsigned(s_pf0_byf(C_BY_HIGH downto 0));
                s_pf1_addr <= resize(shift_left(resize(v_by, 13), 4), 13)
                            + resize(shift_left(resize(v_by, 13), 3), 13)
                            + resize(unsigned(
                                  s_pf0_bxf(C_BX_HIGH downto C_WBIT_BITS)),
                                  13);
            else
                s_pf1_addr <= (others => '0');
            end if;
            s_pf1_par   <= s_pf0_bxf(C_WBIT_BITS);
            s_pf1_idx   <= s_pf0_idx;
            s_pf1_valid <= v_valid;

            -- PF2: synchronous ROM read (BRAM)
            s_pf2_word  <= C_LOGO_ROM(to_integer(s_pf1_addr));
            s_pf2_par   <= s_pf1_par;
            s_pf2_idx   <= s_pf1_idx;
            s_pf2_valid <= s_pf1_valid;

            -- PF3: buffer write
            if s_pf2_valid = '1' then
                if s_pf2_par = '1' then
                    s_pf_buf(to_integer(s_pf2_idx))(1) <= s_pf2_word;
                else
                    s_pf_buf(to_integer(s_pf2_idx))(0) <= s_pf2_word;
                end if;
            end if;
        end if;
    end process;

    -- ========================================================================
    -- S1 — coords + per-logo bbox snapshot
    -- ========================================================================
    p_stage1 : process(clk)
    begin
        if rising_edge(clk) then
            s_stg1_hx <= signed(resize(s_h_count, 12));
            s_stg1_vy <= signed(resize(s_v_count, 12));
            for i in 0 to N_LOGOS - 1 loop
                s_bnd_x(i)      <= s_logo_x(i);
                s_bnd_y(i)      <= s_logo_y(i);
                s_bnd_active(i) <= s_active(i);
            end loop;
        end if;
    end process;

    -- ========================================================================
    -- S2a — per-logo deltas (one 13-bit subtract per axis)
    -- ========================================================================
    p_stage2a : process(clk)
    begin
        if rising_edge(clk) then
            for i in 0 to N_LOGOS - 1 loop
                s_stg2a_dx(i)     <= resize(s_stg1_hx, 13)
                                     - resize(s_bnd_x(i), 13);
                s_stg2a_dy(i)     <= resize(s_stg1_vy, 13)
                                     - resize(s_bnd_y(i), 13);
                s_stg2a_active(i) <= s_bnd_active(i);
            end loop;
        end if;
    end process;

    -- ========================================================================
    -- S2b — per-logo lit flags: inside bbox AND that logo's bitmap bit set
    --       (bit sampled from the prefetch buffer, even/odd word by dx(4)).
    -- ========================================================================
    p_stage2b : process(clk)
        variable v_in_x : std_logic;
        variable v_in_y : std_logic;
        variable v_bit  : std_logic;
        variable v_word : std_logic_vector(C_LOGO_WORD_W - 1 downto 0);
    begin
        if rising_edge(clk) then
            for i in 0 to N_LOGOS - 1 loop
                if s_stg2a_dx(i) >= to_signed(0, 13)
                   and s_stg2a_dx(i) < C_LOGO_W_S then
                    v_in_x := '1';
                else
                    v_in_x := '0';
                end if;
                if s_stg2a_dy(i) >= to_signed(0, 13)
                   and s_stg2a_dy(i) < C_LOGO_H_S then
                    v_in_y := '1';
                else
                    v_in_y := '0';
                end if;

                if s_stg2a_dx(i)(C_WBIT_BITS) = '1' then
                    v_word := s_pf_buf(i)(1);
                else
                    v_word := s_pf_buf(i)(0);
                end if;
                v_bit := v_word(C_LOGO_WORD_W - 1 - to_integer(
                             unsigned(s_stg2a_dx(i)(C_WBIT_BITS - 1 downto 0))));

                s_stg2_lit(i) <= v_in_x and v_in_y and s_stg2a_active(i)
                                 and v_bit;
            end loop;
        end if;
    end process;

    -- ========================================================================
    -- S3 — gate per-logo palette contributions by the lit flags.
    -- ========================================================================
    p_stage3 : process(clk)
    begin
        if rising_edge(clk) then
            for i in 0 to N_LOGOS - 1 loop
                if s_stg2_lit(i) = '1' then
                    s_stg3_y(i)  <= s_pal_y(i);
                    s_stg3_uo(i) <= s_pal_uo(i);
                    s_stg3_vo(i) <= s_pal_vo(i);
                else
                    s_stg3_y(i)  <= (others => '0');
                    s_stg3_uo(i) <= (others => '0');
                    s_stg3_vo(i) <= (others => '0');
                end if;
            end loop;
            s_stg3_lit <= s_stg2_lit;
        end if;
    end process;

    -- ========================================================================
    -- S4 — pairwise partial sums (Mix path) + pairwise priority selects
    --      (Bounce path: lowest-index lit logo wins).
    -- ========================================================================
    p_stage4 : process(clk)
    begin
        if rising_edge(clk) then
            s_stg4_ysum01 <= resize(s_stg3_y(0), 11) + resize(s_stg3_y(1), 11);
            s_stg4_ysum23 <= resize(s_stg3_y(2), 11) + resize(s_stg3_y(3), 11);
            s_stg4_uo01 <= resize(s_stg3_uo(0), 12) + resize(s_stg3_uo(1), 12);
            s_stg4_uo23 <= resize(s_stg3_uo(2), 12) + resize(s_stg3_uo(3), 12);
            s_stg4_vo01 <= resize(s_stg3_vo(0), 12) + resize(s_stg3_vo(1), 12);
            s_stg4_vo23 <= resize(s_stg3_vo(2), 12) + resize(s_stg3_vo(3), 12);

            if s_stg3_lit(0) = '1' then
                s_stg4_sely01  <= s_stg3_y(0);
                s_stg4_seluo01 <= s_stg3_uo(0);
                s_stg4_selvo01 <= s_stg3_vo(0);
            else
                s_stg4_sely01  <= s_stg3_y(1);
                s_stg4_seluo01 <= s_stg3_uo(1);
                s_stg4_selvo01 <= s_stg3_vo(1);
            end if;
            if s_stg3_lit(2) = '1' then
                s_stg4_sely23  <= s_stg3_y(2);
                s_stg4_seluo23 <= s_stg3_uo(2);
                s_stg4_selvo23 <= s_stg3_vo(2);
            else
                s_stg4_sely23  <= s_stg3_y(3);
                s_stg4_seluo23 <= s_stg3_uo(3);
                s_stg4_selvo23 <= s_stg3_vo(3);
            end if;
            s_stg4_lit01 <= s_stg3_lit(0) or s_stg3_lit(1);
            s_stg4_lit23 <= s_stg3_lit(2) or s_stg3_lit(3);
            s_stg4_any   <= s_stg3_lit(0) or s_stg3_lit(1)
                            or s_stg3_lit(2) or s_stg3_lit(3);
        end if;
    end process;

    -- ========================================================================
    -- S5 — final combine.  Bounce: priority pick.  Mix: additive sum + clamp
    --      (Y sums; U/V offsets from 512 sum, then re-center and clamp).
    -- ========================================================================
    p_stage5 : process(clk)
        variable v_ysum : unsigned(11 downto 0);
        variable v_uo   : signed(12 downto 0);
        variable v_vo   : signed(12 downto 0);
        variable v_u    : signed(12 downto 0);
        variable v_v    : signed(12 downto 0);
    begin
        if rising_edge(clk) then
            if s_mix_logos = '1' then
                v_ysum := resize(s_stg4_ysum01, 12) + resize(s_stg4_ysum23, 12);
                if v_ysum > to_unsigned(1023, 12) then
                    s_stg5_y <= to_unsigned(1023, 10);
                else
                    s_stg5_y <= v_ysum(9 downto 0);
                end if;

                v_uo := resize(s_stg4_uo01, 13) + resize(s_stg4_uo23, 13);
                v_vo := resize(s_stg4_vo01, 13) + resize(s_stg4_vo23, 13);
                v_u  := to_signed(512, 13) + v_uo;
                v_v  := to_signed(512, 13) + v_vo;
                if v_u < to_signed(0, 13) then
                    s_stg5_u <= (others => '0');
                elsif v_u > to_signed(1023, 13) then
                    s_stg5_u <= to_unsigned(1023, 10);
                else
                    s_stg5_u <= unsigned(v_u(9 downto 0));
                end if;
                if v_v < to_signed(0, 13) then
                    s_stg5_v <= (others => '0');
                elsif v_v > to_signed(1023, 13) then
                    s_stg5_v <= to_unsigned(1023, 10);
                else
                    s_stg5_v <= unsigned(v_v(9 downto 0));
                end if;
            else
                -- Priority pick: selected offsets are single palette entries,
                -- so 512 + offset is always in 0..1023 — no clamp needed.
                if s_stg4_lit01 = '1' then
                    s_stg5_y <= s_stg4_sely01;
                    v_u := to_signed(512, 13) + resize(s_stg4_seluo01, 13);
                    v_v := to_signed(512, 13) + resize(s_stg4_selvo01, 13);
                else
                    s_stg5_y <= s_stg4_sely23;
                    v_u := to_signed(512, 13) + resize(s_stg4_seluo23, 13);
                    v_v := to_signed(512, 13) + resize(s_stg4_selvo23, 13);
                end if;
                s_stg5_u <= unsigned(v_u(9 downto 0));
                s_stg5_v <= unsigned(v_v(9 downto 0));
            end if;
            s_stg5_show <= s_stg4_any;
        end if;
    end process;

    -- ========================================================================
    -- S6 — output alignment register
    -- ========================================================================
    p_stage6 : process(clk)
    begin
        if rising_edge(clk) then
            s_out_y    <= s_stg5_y;
            s_out_u    <= s_stg5_u;
            s_out_v    <= s_stg5_v;
            s_out_show <= s_stg5_show;
        end if;
    end process;

    -- ========================================================================
    -- Sync + data delay
    -- ========================================================================
    p_delay : process(clk)
    begin
        if rising_edge(clk) then
            s_sync_pipe(0) <= data_in.field_n & data_in.avid &
                              data_in.vsync_n & data_in.hsync_n;
            for i in 1 to 12 loop
                s_sync_pipe(i) <= s_sync_pipe(i - 1);
            end loop;

            s_y_delay(0) <= data_in.y;
            s_u_delay(0) <= data_in.u;
            s_v_delay(0) <= data_in.v;
            for i in 1 to C_DELAY - 1 loop
                s_y_delay(i) <= s_y_delay(i - 1);
                s_u_delay(i) <= s_u_delay(i - 1);
                s_v_delay(i) <= s_v_delay(i - 1);
            end loop;
        end if;
    end process;

    -- ========================================================================
    -- Wet-pixel mux
    -- ========================================================================
    p_wet_select : process(s_out_show, s_matte, s_bg_black,
                           s_out_y, s_out_u, s_out_v,
                           s_y_delay, s_u_delay, s_v_delay)
    begin
        if s_out_show = '1' then
            if s_matte = '1' then
                s_wet_y <= s_y_delay(C_DELAY - 1);
                s_wet_u <= s_u_delay(C_DELAY - 1);
                s_wet_v <= s_v_delay(C_DELAY - 1);
            else
                s_wet_y <= std_logic_vector(s_out_y);
                s_wet_u <= std_logic_vector(s_out_u);
                s_wet_v <= std_logic_vector(s_out_v);
            end if;
        else
            if s_bg_black = '1' then
                s_wet_y <= std_logic_vector(to_unsigned(0,   10));
                s_wet_u <= std_logic_vector(to_unsigned(512, 10));
                s_wet_v <= std_logic_vector(to_unsigned(512, 10));
            else
                s_wet_y <= s_y_delay(C_DELAY - 1);
                s_wet_u <= s_u_delay(C_DELAY - 1);
                s_wet_v <= s_v_delay(C_DELAY - 1);
            end if;
        end if;
    end process;

    -- ========================================================================
    -- Wet/dry mix
    -- ========================================================================
    mix_y_inst : entity work.interpolator_u
        generic map(G_WIDTH => 10, G_FRAC_BITS => 10,
                    G_OUTPUT_MIN => 0, G_OUTPUT_MAX => 1023)
        port map(clk => clk, enable => '1',
                 a => unsigned(s_y_delay(C_DELAY - 1)),
                 b => unsigned(s_wet_y),
                 t => s_mix_amount,
                 result => s_mix_y_result, valid => s_mix_y_valid);

    mix_u_inst : entity work.interpolator_u
        generic map(G_WIDTH => 10, G_FRAC_BITS => 10,
                    G_OUTPUT_MIN => 0, G_OUTPUT_MAX => 1023)
        port map(clk => clk, enable => '1',
                 a => unsigned(s_u_delay(C_DELAY - 1)),
                 b => unsigned(s_wet_u),
                 t => s_mix_amount,
                 result => s_mix_u_result, valid => s_mix_u_valid);

    mix_v_inst : entity work.interpolator_u
        generic map(G_WIDTH => 10, G_FRAC_BITS => 10,
                    G_OUTPUT_MIN => 0, G_OUTPUT_MAX => 1023)
        port map(clk => clk, enable => '1',
                 a => unsigned(s_v_delay(C_DELAY - 1)),
                 b => unsigned(s_wet_v),
                 t => s_mix_amount,
                 result => s_mix_v_result, valid => s_mix_v_valid);

    -- ========================================================================
    -- IO Alignment
    -- ========================================================================
    p_io : process(clk)
    begin
        if rising_edge(clk) then
            s_io_0.y       <= std_logic_vector(s_mix_y_result);
            s_io_0.u       <= std_logic_vector(s_mix_u_result);
            s_io_0.v       <= std_logic_vector(s_mix_v_result);
            s_io_0.hsync_n <= s_sync_pipe(12)(0);
            s_io_0.vsync_n <= s_sync_pipe(12)(1);
            s_io_0.avid    <= s_mix_y_valid and s_mix_u_valid and s_mix_v_valid;
            s_io_0.field_n <= s_sync_pipe(12)(3);
            s_io_1 <= s_io_0;
        end if;
    end process;

    data_out.y       <= s_io_1.y;
    data_out.u       <= s_io_1.u;
    data_out.v       <= s_io_1.v;
    data_out.hsync_n <= s_io_1.hsync_n;
    data_out.vsync_n <= s_io_1.vsync_n;
    data_out.avid    <= s_io_1.avid;
    data_out.field_n <= s_io_1.field_n;

end architecture dvdlogo;
