#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""
DVD Logo - build hook.

Reads dvd_logo_source.png (expected 384 x 174, any pixel format) and emits
dvdlogo_logo_pkg.vhd as a flat ROM of 16-bit words.

Threshold rule (matches PNG source which is black-on-transparent):
    alpha < 128         → off (background)
    luma  < 128         → on  (logo)
    otherwise           → off

Storage layout: each row is W / 16 = 24 16-bit words; the leftmost pixel of
each word is the MSB.  Address = row * WORDS_PER_ROW + (col >> 4); bit
within word = col mod 16, with the leftmost pixel as the MSB.
"""

import os
import sys

# The OSS CAD Suite environment puts its own python3 first on PATH; that
# interpreter usually lacks Pillow even though /usr/bin/python3 has it.
# Re-exec under the system python if our current interpreter can't import
# PIL but a usable one exists at /usr/bin/python3.
try:
    from PIL import Image
except ImportError:
    _SYS_PY = "/usr/bin/python3"
    if (os.path.exists(_SYS_PY)
            and os.path.realpath(sys.executable) != os.path.realpath(_SYS_PY)):
        # Clear OSS-CAD-Suite python env vars so the system interpreter
        # doesn't try to load its stdlib from the wrong tree.
        env = {k: v for k, v in os.environ.items()
               if k not in ("PYTHONHOME", "PYTHONPATH",
                            "PYTHONSTARTUP", "PYTHONNOUSERSITE")}
        os.execve(_SYS_PY, [_SYS_PY, os.path.abspath(__file__)], env)
    raise

W = 384
H = 174
WORD_W = 16
WORDS_PER_ROW = W // WORD_W       # 24
TOTAL_WORDS = H * WORDS_PER_ROW   # 4176

SRC_PATH = "dvd_logo_source.png"
OUT_PATH = "dvdlogo_logo_pkg.vhd"


def load_bitmap(path):
    im = Image.open(path).convert("RGBA")
    if im.size != (W, H):
        raise SystemExit(f"expected {W}x{H}, got {im.size}")
    bits = [[0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            r, g, b, a = im.getpixel((x, y))
            if a < 128:
                continue
            if (r + g + b) // 3 < 128:
                bits[y][x] = 1
    return bits


def preview(bits, scale=4):
    """ASCII preview, downsampled by `scale` so it fits in a terminal."""
    on = sum(sum(row) for row in bits)
    print(f"DVD logo bitmap {W}x{H}, {on} on-pixels "
          f"({100.0 * on / (W * H):.1f}% coverage):")
    for y in range(0, H, scale):
        row = []
        for x in range(0, W, scale):
            # OR-reduce the scale x scale block.
            block = 0
            for dy in range(scale):
                for dx in range(scale):
                    yy = y + dy
                    xx = x + dx
                    if yy < H and xx < W and bits[yy][xx]:
                        block = 1
                        break
                if block:
                    break
            row.append("#" if block else ".")
        print("".join(row))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.join(here, SRC_PATH)
    out = os.path.join(here, OUT_PATH)

    print(f"Reading {src}...")
    bits = load_bitmap(src)
    preview(bits, scale=4)

    # Pack into 16-bit words; MSB of each word = leftmost pixel of that group.
    words = []
    for y in range(H):
        for wx in range(WORDS_PER_ROW):
            v = 0
            for b in range(WORD_W):
                if bits[y][wx * WORD_W + b]:
                    v |= 1 << (WORD_W - 1 - b)
            words.append(v)

    lines = []
    lines.append("-- AUTO-GENERATED by dvdlogo.py - do not edit by hand.")
    lines.append(f"-- {W} x {H} 1-bit logo, packed into {TOTAL_WORDS} x "
                 f"{WORD_W}-bit words.")
    lines.append("-- Address = row * WORDS_PER_ROW + (col >> 4).")
    lines.append("-- MSB of each word = leftmost pixel within that 16-px group.")
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("")
    lines.append("package dvdlogo_logo_pkg is")
    lines.append("")
    lines.append(f"    constant C_LOGO_W             : integer := {W};")
    lines.append(f"    constant C_LOGO_H             : integer := {H};")
    lines.append(f"    constant C_LOGO_WORD_W        : integer := {WORD_W};")
    lines.append(f"    constant C_LOGO_WORDS_PER_ROW : integer := {WORDS_PER_ROW};")
    lines.append(f"    constant C_LOGO_TOTAL_WORDS   : integer := {TOTAL_WORDS};")
    lines.append("")
    lines.append("    type t_logo_rom is array (0 to C_LOGO_TOTAL_WORDS - 1)")
    lines.append("        of std_logic_vector(C_LOGO_WORD_W - 1 downto 0);")
    lines.append("")
    lines.append("    constant C_LOGO_ROM : t_logo_rom := (")

    last = TOTAL_WORDS - 1
    for i, w in enumerate(words):
        sep = "," if i < last else " "
        lines.append(f'        {i:4d} => x"{w:0{WORD_W // 4}X}"{sep}')
    lines.append("    );")
    lines.append("")
    lines.append("end package dvdlogo_logo_pkg;")
    lines.append("")

    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out}")
    print(f"  {H} rows x {WORDS_PER_ROW} words/row = {TOTAL_WORDS} words "
          f"({TOTAL_WORDS * WORD_W} bits, "
          f"~{(TOTAL_WORDS * WORD_W + 4095) // 4096} BRAMs)")


if __name__ == "__main__":
    main()
