-- untitled: Untitled
-- New program.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/untitled.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   vout       video_out     1 ->   2
-- Program latency: 2 clocks, identical in every video mode.
-- Estimate: 1217 LC (15.8 %), 0 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture untitled of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_vout_out             : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_vin_out, o_data => data_out);
end architecture untitled;
