#!/usr/bin/env python3
"""
SUGARCOAT palette generator.

Emits the VHDL palette ROM: 7 palettes x 8 entries (dark -> light), each a
10-bit YUV triple in STANDARD BT.601 (U=Cb, V=Cr), chroma centred at 512.
(Per sim_color_convention: lzx-vhdl-cli renders standard U/V, so we author in
standard and let hardware confirm; a global U<->V swap is a one-line flip if
the panel disagrees.)

Whites are authored genuinely white, blacks warm (never neutral grey), and
saturation is pushed hard -- this is candy, not tasteful.
"""

def yuv10(r, g, b):
    # 8-bit BT.601, then scale to 10-bit; chroma deviation *4, centred 512.
    y8 = 0.299 * r + 0.587 * g + 0.114 * b
    u8 = -0.168736 * r - 0.331264 * g + 0.5 * b        # Cb deviation
    v8 = 0.5 * r - 0.418688 * g - 0.081312 * b         # Cr deviation
    Y = round(y8 * 1023 / 255)
    U = round(512 + u8 * 4)
    V = round(512 + v8 * 4)
    clip = lambda x: max(0, min(1023, x))
    return clip(Y), clip(U), clip(V)


# Each palette: 8 RGB stops, dark -> light. Motif band assignment leans on the
# ordering (darkest = chocolate/licorice end, brightest = gloss/white end).
PALETTES = {
    "Penny Candy": [
        (40, 0, 10), (140, 10, 20), (220, 20, 40), (255, 120, 0),
        (255, 210, 0), (120, 210, 30), (90, 40, 160), (255, 255, 255),
    ],
    "Bubblegum": [
        (60, 20, 55), (150, 40, 110), (255, 90, 175), (255, 150, 200),
        (130, 225, 210), (120, 200, 255), (210, 180, 255), (255, 250, 250),
    ],
    "Peppermint": [
        (20, 30, 20), (10, 90, 40), (20, 140, 60), (200, 20, 40),
        (240, 70, 90), (230, 200, 60), (255, 240, 240), (255, 255, 255),
    ],
    "Bakery": [
        (35, 18, 8), (70, 38, 18), (120, 72, 34), (170, 110, 55),
        (205, 150, 85), (230, 190, 120), (245, 225, 170), (255, 248, 225),
    ],
    "Sour": [
        (20, 40, 10), (120, 200, 20), (200, 255, 0), (255, 240, 20),
        (255, 20, 200), (20, 220, 220), (180, 255, 120), (255, 255, 255),
    ],
    "Tropical Taffy": [
        (40, 20, 30), (255, 110, 90), (255, 170, 60), (255, 225, 70),
        (40, 200, 190), (60, 225, 215), (255, 130, 175), (255, 250, 245),
    ],
    "Holo Wrapper": [
        (60, 60, 70), (150, 120, 200), (120, 180, 240), (140, 240, 210),
        (240, 220, 150), (245, 170, 200), (210, 210, 235), (255, 255, 255),
    ],
}


def emit():
    names = list(PALETTES.keys())
    lines = []
    lines.append("    -- Generated by genpal.py -- 7 palettes x 8 stops (dark->light),")
    lines.append("    -- 10-bit standard BT.601 YUV, chroma centred 512.")
    lines.append("    -- Flat 56-entry ROMs, index = pal*8 + stop (flat avoids the")
    lines.append("    -- array-of-arrays GHDL synth crash; separate Y/U/V constants).")
    lines.append("    type t_pal56 is array (0 to 55) of unsigned(9 downto 0);")
    for chan, idx in (("Y", 0), ("U", 1), ("V", 2)):
        lines.append("    constant C_PAL_%s : t_pal56 := (" % chan)
        for pi, name in enumerate(names):
            vals = [yuv10(*rgb)[idx] for rgb in PALETTES[name]]
            body = ", ".join("to_unsigned(%d, 10)" % v for v in vals)
            comma = "," if pi < len(names) - 1 else ""
            lines.append("        %s%s  -- %d: %s" % (body, comma, pi * 8, name))
        lines.append("    );")
    return "\n".join(lines)


if __name__ == "__main__":
    print(emit())
    # human-readable check
    import sys
    print("\n-- palette preview (Y U V):", file=sys.stderr)
    for name, stops in PALETTES.items():
        print("--  %-16s" % name,
              " ".join("%d/%d/%d" % yuv10(*rgb) for rgb in stops),
              file=sys.stderr)
