-- sugarcoat.vhd
--
-- SUGARCOAT -- video re-rendered as candy: a 1:1 COLOUR -> CANDY-TEXTURE map.
--
-- Each pixel is classified by its chroma (hue octant / saturation) or, when
-- neutral, by its luma; the class picks one of 8 flat screen-space candy
-- materials.  NO generated geometry -- no polar/radial patterns, the picture
-- alone decides where each candy appears.  SUGAR RUSH (P12) dips the raw
-- image into the confection.
--
-- Classes: neutral dark -> dark chocolate bar (quilted grooves), neutral dim
-- -> cookies & cream (cream dots on black), neutral light -> piped icing
-- (wavy scallop piping), neutral bright -> frosting + rainbow confetti;
-- red -> candy cane stripes, yellow -> choc-chip cookie, green -> mint
-- stripes (opposite diagonal), blue/cyan/magenta -> rainbow taffy stripes
-- (palette ramp, K4).
--
-- Pipeline (streaming, C_LATENCY = 16, 1 EBR = gloss line RAM):
--   Classify: E1 in -> E2 |du|,|dv|,sat,octant -> E3 class -> E4 (+K1 rotate)
--             -> txd SR to the texture stage.
--   Geometry: W1/W2 domain warp (drifting cross-axis triangle, shift-scaled)
--             -> three projections (dx+dy, dx-dy, wavy dy) -> pattern bits.
--   Gloss:    line RAM -> 2D luma-gradient emboss -> specular sheen g_add.
--   MP/PH1:   pattern bits + garnish decision + taffy palette read.
--   PH2/CO:   texture bank (constant-colour selects) -> gloss add -> clamp.
--   SUGAR RUSH inline dry/wet lerp (M1..M3), sync-aligned output.
-- Multiplies (HX4K has no DSP): only the mix x3.  Everything else is
-- shifts, compares and slices.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.all;
use work.core_pkg.all;
use work.video_stream_pkg.all;

architecture sugarcoat of program_top is

    constant C_LATENCY : integer := 16;

    ----------------------------------------------------------------------
    -- clamp helpers
    ----------------------------------------------------------------------
    function f_cu10(v : signed) return unsigned is
    begin
        if v < 0 then
            return to_unsigned(0, 10);
        elsif v > 1023 then
            return to_unsigned(1023, 10);
        else
            return resize(unsigned(v), 10);
        end if;
    end function;

    -- Folded TRIANGLE wave (10-bit phase, 1024 = one cycle, output +/-504).
    -- Used only by the domain warp, where a triangle is visually equivalent
    -- to a sine but is fold+shift logic -- no ROM, and off the HD crit path
    -- (the sine ROM in series with the warp barrel-shift was the limiter).
    function f_tri(a : unsigned(9 downto 0)) return signed is
        variable v_i : unsigned(5 downto 0);
        variable v_t : signed(9 downto 0);
    begin
        if a(8) = '0' then v_i := a(7 downto 2);
        else               v_i := not a(7 downto 2); end if;
        v_t := signed(resize(v_i, 7) & "000");        -- v_i * 8 (0..504)
        if a(9) = '1' then return -v_t; else return v_t; end if;
    end function;

    -- cheap 16-bit hash for garnish placement (xor-rotate-add)
    function f_hash(x, y : unsigned(9 downto 0);
                    seed : unsigned(15 downto 0)) return unsigned is
        variable h : unsigned(15 downto 0);
    begin
        h := (x & y(9 downto 4)) xor seed;
        h := h xor rotate_left(h, 7);
        h := h + rotate_left(h, 3);
        h := h xor (x"00" & h(15 downto 8));
        return h;
    end function;

    ----------------------------------------------------------------------
    -- candy palette ROM (generated by genpal.py) -- flat 56-entry ROMs,
    -- index = pal*8 + stop, 10-bit standard BT.601 YUV, chroma centred 512.
    ----------------------------------------------------------------------
    type t_pal56 is array (0 to 55) of unsigned(9 downto 0);
    constant C_PAL_Y : t_pal56 := (
        to_unsigned(53, 10), to_unsigned(201, 10), to_unsigned(329, 10), to_unsigned(588, 10), to_unsigned(800, 10), to_unsigned(652, 10), to_unsigned(275, 10), to_unsigned(1023, 10),  -- 0: Penny Candy
        to_unsigned(144, 10), to_unsigned(324, 10), to_unsigned(598, 10), to_unsigned(751, 10), to_unsigned(782, 10), to_unsigned(732, 10), to_unsigned(792, 10), to_unsigned(1009, 10),  -- 8: Bubblegum
        to_unsigned(104, 10), to_unsigned(242, 10), to_unsigned(381, 10), to_unsigned(305, 10), to_unsigned(494, 10), to_unsigned(774, 10), to_unsigned(981, 10), to_unsigned(1023, 10),  -- 16: Peppermint
        to_unsigned(88, 10), to_unsigned(182, 10), to_unsigned(329, 10), to_unsigned(488, 10), to_unsigned(638, 10), to_unsigned(778, 10), to_unsigned(901, 10), to_unsigned(993, 10),  -- 24: Bakery
        to_unsigned(123, 10), to_unsigned(624, 10), to_unsigned(840, 10), to_unsigned(880, 10), to_unsigned(444, 10), to_unsigned(643, 10), to_unsigned(871, 10), to_unsigned(1023, 10),  -- 32: Sour
        to_unsigned(109, 10), to_unsigned(606, 10), to_unsigned(734, 10), to_unsigned(868, 10), to_unsigned(606, 10), to_unsigned(700, 10), to_unsigned(692, 10), to_unsigned(1007, 10),  -- 40: Tropical Taffy
        to_unsigned(245, 10), to_unsigned(554, 10), to_unsigned(678, 10), to_unsigned(829, 10), to_unsigned(875, 10), to_unsigned(786, 10), to_unsigned(854, 10), to_unsigned(1023, 10)  -- 48: Holo Wrapper
    );
    constant C_PAL_U : t_pal56 := (
        to_unsigned(505, 10), to_unsigned(444, 10), to_unsigned(417, 10), to_unsigned(181, 10), to_unsigned(62, 10), to_unsigned(213, 10), to_unsigned(718, 10), to_unsigned(512, 10),  -- 0: Penny Candy
        to_unsigned(555, 10), to_unsigned(578, 10), to_unsigned(571, 10), to_unsigned(541, 10), to_unsigned(546, 10), to_unsigned(676, 10), to_unsigned(642, 10), to_unsigned(509, 10),  -- 8: Bubblegum
        to_unsigned(499, 10), to_unsigned(466, 10), to_unsigned(433, 10), to_unsigned(431, 10), to_unsigned(437, 10), to_unsigned(212, 10), to_unsigned(502, 10), to_unsigned(512, 10),  -- 16: Peppermint
        to_unsigned(481, 10), to_unsigned(450, 10), to_unsigned(404, 10), to_unsigned(362, 10), to_unsigned(345, 10), to_unsigned(345, 10), to_unsigned(389, 10), to_unsigned(461, 10),  -- 24: Bakery
        to_unsigned(465, 10), to_unsigned(206, 10), to_unsigned(39, 10), to_unsigned(62, 10), to_unsigned(713, 10), to_unsigned(647, 10), to_unsigned(293, 10), to_unsigned(512, 10),  -- 32: Sour
        to_unsigned(519, 10), to_unsigned(374, 10), to_unsigned(235, 10), to_unsigned(182, 10), to_unsigned(600, 10), to_unsigned(603, 10), to_unsigned(518, 10), to_unsigned(499, 10),  -- 40: Tropical Taffy
        to_unsigned(532, 10), to_unsigned(652, 10), to_unsigned(672, 10), to_unsigned(519, 10), to_unsigned(359, 10), to_unsigned(521, 10), to_unsigned(562, 10), to_unsigned(512, 10)  -- 48: Holo Wrapper
    );
    constant C_PAL_V : t_pal56 := (
        to_unsigned(589, 10), to_unsigned(769, 10), to_unsigned(905, 10), to_unsigned(821, 10), to_unsigned(670, 10), to_unsigned(391, 10), to_unsigned(573, 10), to_unsigned(512, 10),  -- 0: Penny Candy
        to_unsigned(581, 10), to_unsigned(709, 10), to_unsigned(814, 10), to_unsigned(706, 10), to_unsigned(327, 10), to_unsigned(334, 10), to_unsigned(548, 10), to_unsigned(522, 10),  -- 8: Bubblegum
        to_unsigned(495, 10), to_unsigned(368, 10), to_unsigned(298, 10), to_unsigned(865, 10), to_unsigned(845, 10), to_unsigned(618, 10), to_unsigned(542, 10), to_unsigned(512, 10),  -- 16: Peppermint
        to_unsigned(549, 10), to_unsigned(583, 10), to_unsigned(620, 10), to_unsigned(650, 10), to_unsigned(643, 10), to_unsigned(615, 10), to_unsigned(570, 10), to_unsigned(533, 10),  -- 24: Bakery
        to_unsigned(482, 10), to_unsigned(411, 10), to_unsigned(485, 10), to_unsigned(614, 10), to_unsigned(923, 10), to_unsigned(112, 10), to_unsigned(406, 10), to_unsigned(512, 10),  -- 32: Sour
        to_unsigned(549, 10), to_unsigned(809, 10), to_unsigned(718, 10), to_unsigned(622, 10), to_unsigned(195, 10), to_unsigned(185, 10), to_unsigned(747, 10), to_unsigned(524, 10),  -- 40: Tropical Taffy
        to_unsigned(509, 10), to_unsigned(546, 10), to_unsigned(372, 10), to_unsigned(322, 10), to_unsigned(575, 10), to_unsigned(652, 10), to_unsigned(504, 10), to_unsigned(512, 10)  -- 48: Holo Wrapper
    );

    -- candy whites / accents (standard BT.601 YUV)
    constant C_WHITE_Y : unsigned(9 downto 0) := to_unsigned(1000, 10);

    ----------------------------------------------------------------------
    -- frame-latched controls + per-frame terms
    ----------------------------------------------------------------------
    signal s_p12 : unsigned(9 downto 0) := to_unsigned(768, 10);
    signal s_k1  : unsigned(9 downto 0) := to_unsigned(512, 10);
    signal s_k2  : unsigned(9 downto 0) := to_unsigned(512, 10);
    signal s_k3  : unsigned(9 downto 0) := to_unsigned(320, 10);
    signal s_k4  : unsigned(9 downto 0) := (others => '0');
    signal s_k5  : unsigned(9 downto 0) := to_unsigned(320, 10);
    signal s_k6  : unsigned(9 downto 0) := to_unsigned(640, 10);
    signal s_sw  : std_logic_vector(4 downto 0) := "00010";         -- S7..S11

    signal s_paloff : unsigned(5 downto 0) := (others => '0');
    signal s_mix10  : unsigned(9 downto 0) := (others => '0');
    -- 1:1 colour->texture map: chroma octant / saturation / luma classify the
    -- pixel; K1 rotates the class->texture assignment, K2 scales density.
    -- STRENGTH (P12) drives whichever map S11 selects: in CHROMA it is the
    -- saturation floor for reading a hue, in LUMA it is the ramp quantiser.
    signal s_sthr   : unsigned(9 downto 0) := to_unsigned(80, 10);
    signal s_ymask  : unsigned(2 downto 0) := "111";
    signal s_texoff : unsigned(2 downto 0) := (others => '0');     -- K1 rotate
    signal s_dgb    : integer range 3 to 6 := 4;   -- diag stripe pitch bit (K2)
                                                   -- (indexes the PRE-SCALED projection)
    -- SCALE (K3): one global size step for every texture.  Level 1 reproduces
    -- the original sizes exactly; 0 = finer, 2/3 = coarser.  Drives the stripe
    -- pitch bit above, the groove/scallop windows, and the chip/dot cell size
    -- (8/16/32/64 px).
    signal s_scl    : integer range 0 to 3 := 1;
    signal s_wsh    : integer range 3 to 11 := 11;                 -- WARP shift (K5)
    signal s_wc     : unsigned(6 downto 0) := (others => '0');      -- WARP weight
    -- STATIC bend phases -- nothing self-animates; motion comes from the video

    ----------------------------------------------------------------------
    -- raster measurement + centre
    ----------------------------------------------------------------------
    signal s_prev_vsync : std_logic := '1';
    signal s_vs_pulse   : std_logic := '0';
    signal s_avid_q     : std_logic := '0';
    signal s_xcnt       : unsigned(11 downto 0) := (others => '0');
    signal s_lcnt       : unsigned(11 downto 0) := (others => '0');
    signal s_W          : unsigned(11 downto 0) := to_unsigned(720, 12);
    signal s_H          : unsigned(11 downto 0) := to_unsigned(480, 12);
    signal s_ilace      : std_logic := '0';
    signal s_fpar       : std_logic := '0';
    signal s_cx, s_cy   : signed(13 downto 0) := (others => '0');

    signal s_seq : unsigned(4 downto 0) := (others => '0');

    ----------------------------------------------------------------------
    -- coordinate accumulators
    ----------------------------------------------------------------------
    signal s_avid_p   : std_logic := '0';
    signal s_newframe : std_logic := '1';
    signal s_dx       : signed(13 downto 0) := (others => '0');
    signal s_dyc      : signed(13 downto 0) := (others => '0');
    signal s_dyb      : signed(13 downto 0) := (others => '0');

    ----------------------------------------------------------------------
    -- colour path: chroma/luma CLASSIFIER pipeline registers
    ----------------------------------------------------------------------
    signal e1_y, e1_u, e1_v : unsigned(9 downto 0) := (others => '0');
    signal e2_sat : unsigned(9 downto 0) := (others => '0');  -- |du|+|dv|
    signal e2_dus, e2_dvs : std_logic := '0';                 -- signs (Cb>512, Cr>512)
    signal e2_cmp : std_logic := '0';                         -- |du| > |dv|
    signal e2_yb  : unsigned(2 downto 0) := (others => '0');  -- luma level (8 steps)
    signal e3_tex : unsigned(2 downto 0) := (others => '0');  -- class
    -- texture index (class + K1 rotate) delayed to the texture stage
    signal t4_tex : unsigned(2 downto 0) := (others => '0');
    type t_txd is array (0 to 5) of unsigned(2 downto 0);
    signal txd : t_txd := (others => (others => '0'));
    signal ph_tex : unsigned(2 downto 0) := (others => '0');
    -- shared pattern bits: MP-stage (t10) -> PH1 (t11) -> used at PH2 (t12)
    signal dg1, dg2     : std_logic := '0';        -- diagonal stripe parity
    signal mg1, mg2     : std_logic := '0';        -- mint stripe (other diagonal)
    signal ic1, ic2     : std_logic := '0';        -- icing scallop piping
    signal dot1, dot2   : std_logic := '0';        -- cream dot (regular grid)
    signal grv1, grv2   : std_logic := '0';        -- thin diagonal groove line
    signal chip1, chip2 : std_logic := '0';        -- cookie-chip blob
    signal mp_pj : unsigned(13 downto 0) := (others => '0');  -- taffy stripe phase

    ----------------------------------------------------------------------
    -- geometry path registers
    ----------------------------------------------------------------------
    signal e1_dx, e1_dy : signed(13 downto 0) := (others => '0');
    -- WARP stages: static cross-axis triangle bend of the coords (K5)
    signal w1_dx, w1_dy : signed(13 downto 0) := (others => '0');
    signal w1_ox, w1_oy : signed(13 downto 0) := (others => '0');  -- displacements
    signal w2_dx, w2_dy : signed(13 downto 0) := (others => '0');

    ----------------------------------------------------------------------
    -- GLOSS: 2D luma-gradient emboss -> specular sheen. One line RAM gives
    -- the previous line's luma; gx from a 1-pixel tap, gy from the line RAM.
    -- Heightfield = luma; light from upper-left; lit = -(gx+gy).
    ----------------------------------------------------------------------
    type t_lram is array (0 to 2047) of std_logic_vector(9 downto 0);
    signal lram   : t_lram;
    signal lb_rd  : std_logic_vector(9 downto 0) := (others => '0');
    signal gpl, gpl_d : unsigned(9 downto 0) := (others => '0');
    signal ggx, ggy : signed(10 downto 0) := (others => '0');
    signal glit     : signed(11 downto 0) := (others => '0');
    signal spec_hi  : std_logic := '0';                            -- glit > gspec
    signal spec_hi2 : std_logic := '0';                            -- L3->L4 carry
    signal g_sh     : signed(13 downto 0) := (others => '0');       -- L3 shift out
    signal g_add    : signed(10 downto 0) := (others => '0');
    signal s_gsh    : integer range 0 to 5 := 3;                    -- GLOSS shift (K6)
    signal s_gspec  : unsigned(8 downto 0) := to_unsigned(220, 9);  -- specular thr
    -- g_add delay to reach the compose stage
    type t_gsr is array (0 to 5) of signed(10 downto 0);
    signal gadd_sr : t_gsr := (others => (others => '0'));

    -- switches + SUGAR-RUSH-weighted terms
    signal s_bakery  : std_logic := '0';                       -- S9
    signal s_melt    : std_logic := '0';                       -- S10
    signal s_lumamap : std_logic := '0';                       -- S11: MAP mode
    signal s_sprk    : unsigned(7 downto 0) := (others => '0'); -- sprinkle density

    ----------------------------------------------------------------------
    -- MP -> PH1 -> PH2/CO texture pipeline
    ----------------------------------------------------------------------
    -- garnish decision precomputed in the MP stage (out of the compose cone)
    signal g_type : unsigned(1 downto 0) := (others => '0');  -- 0 none 1 jimmie 2 dust
    signal g_cv   : unsigned(1 downto 0) := (others => '0');  -- jimmie colour
    -- PH1: taffy palette read + carried side data (one cycle).
    signal ph_ry, ph_ru, ph_rv : unsigned(9 downto 0) := (others => '0'); -- taffy colour
    signal ph_gadd : signed(10 downto 0) := (others => '0');
    signal ph_gt   : unsigned(1 downto 0) := (others => '0');
    signal ph_gc   : unsigned(1 downto 0) := (others => '0');
    -- PH2: texture resolved here (separate cycle from the output add), so no
    -- single cone is deep.  CO is just a 2:1 taffy mux + gloss add + clamp.
    signal ph_ry2, ph_ru2, ph_rv2 : unsigned(9 downto 0) := (others => '0');
    signal co_alt_y, co_alt_u, co_alt_v : unsigned(9 downto 0) := (others => '0');
    signal co_useRing : std_logic := '0';       -- pick ph_r*2 over co_alt_*
    signal co_gy      : signed(10 downto 0) := (others => '0');  -- gloss (+garnish)
    -- stripe projections (dx+dy, dx-dy, wavy-dy), delayed to the MP stage (t10)
    type t_pjsr is array (0 to 5) of unsigned(13 downto 0);
    signal w_proj_sr  : t_pjsr := (others => (others => '0'));
    signal w_proj2_sr : t_pjsr := (others => (others => '0'));
    signal w_proj3_sr : t_pjsr := (others => (others => '0'));
    -- SCALE barrel shifts live in the geometry stage (which has slack); only
    -- the resulting 1-bit groove/scallop flags are delayed to the MP stage.
    signal grv_sr : std_logic_vector(0 to 4) := (others => '0');
    signal ic_sr  : std_logic_vector(0 to 4) := (others => '0');
    -- SCALE-selected chip/dot cell coords, REGISTERED one stage ahead so the
    -- 4:1 size mux sits outside the cookie-hash cone (it cost HD Dual ~8 MHz
    -- inline).  Costs a 1px grid offset, which is invisible.
    signal cl_ix, cl_iy : unsigned(3 downto 0) := (others => '0');
    signal cl_hx  : unsigned(9 downto 0) := (others => '0');
    signal cl_hy6 : unsigned(5 downto 0) := (others => '0');
    -- dense frosting confetti flag (MP -> PH1 -> PH2)
    signal g_d1, g_d2 : std_logic := '0';

    ----------------------------------------------------------------------
    -- compose (wet candy colour)
    ----------------------------------------------------------------------
    signal wcy, wcu, wcv : unsigned(9 downto 0) := (others => '0');

    ----------------------------------------------------------------------
    -- dry delay + SUGAR RUSH inline lerp
    ----------------------------------------------------------------------
    type t_sr is array (0 to 12) of std_logic_vector(9 downto 0);
    signal s_y_sr, s_u_sr, s_v_sr : t_sr := (others => (others => '0'));

    signal s_avid_sr    : std_logic_vector(0 to C_LATENCY - 1) := (others => '0');
    signal s_hsync_n_sr : std_logic_vector(0 to C_LATENCY - 1) := (others => '1');
    signal s_vsync_n_sr : std_logic_vector(0 to C_LATENCY - 1) := (others => '1');
    signal s_field_n_sr : std_logic_vector(0 to C_LATENCY - 1) := (others => '0');

    signal m1_ay, m1_au, m1_av : unsigned(9 downto 0) := (others => '0');
    signal m1_dy, m1_du, m1_dv : signed(10 downto 0) := (others => '0');
    signal m2_ay, m2_au, m2_av : unsigned(9 downto 0) := (others => '0');
    signal m2_py, m2_pu, m2_pv : signed(19 downto 0) := (others => '0');
    signal m3_y, m3_u, m3_v    : unsigned(9 downto 0) := (others => '0');

begin

    ------------------------------------------------------------------------
    -- raster measurement (interlace-aware; own snapshotted counters)
    ------------------------------------------------------------------------
    p_measure : process(clk)
    begin
        if rising_edge(clk) then
            s_prev_vsync <= data_in.vsync_n;
            s_vs_pulse   <= '0';
            if data_in.vsync_n = '0' and s_prev_vsync = '1' then
                s_vs_pulse <= '1';
            end if;

            s_avid_q <= data_in.avid;
            if data_in.avid = '1' then
                s_xcnt <= s_xcnt + 1;
            elsif s_avid_q = '1' then
                if s_xcnt > 16 then s_W <= s_xcnt; end if;
                s_xcnt <= (others => '0');
                s_lcnt <= s_lcnt + 1;
            end if;

            if s_vs_pulse = '1' then
                if s_lcnt > 8 then
                    if s_ilace = '1' then s_H <= shift_left(s_lcnt, 1);
                    else                  s_H <= s_lcnt; end if;
                end if;
                s_lcnt <= (others => '0');
                s_fpar <= data_in.field_n;
                if data_in.field_n /= s_fpar then s_ilace <= '1';
                else                              s_ilace <= '0'; end if;
            end if;
        end if;
    end process p_measure;

    ------------------------------------------------------------------------
    -- per-frame control latch + vblank sequencer
    ------------------------------------------------------------------------
    p_frame : process(clk)
        variable v_pal : integer range 0 to 6;
        variable v_p   : integer range 0 to 1023;
        variable v_c   : integer;
    begin
        if rising_edge(clk) then
            if s_vs_pulse = '1' then
                s_p12 <= unsigned(registers_in(7));
                s_k1  <= unsigned(registers_in(0));
                s_k2  <= unsigned(registers_in(1));
                s_k3  <= unsigned(registers_in(2));
                s_k4  <= unsigned(registers_in(3));
                s_k5  <= unsigned(registers_in(4));
                s_k6  <= unsigned(registers_in(5));
                s_sw  <= registers_in(6)(4 downto 0);
                s_bakery  <= registers_in(6)(2);          -- S9
                s_melt    <= registers_in(6)(3);          -- S10
                s_lumamap <= registers_in(6)(4);          -- S11
                s_cx <= signed(resize(s_W(11 downto 1), 14));
                s_cy <= signed(resize(s_H(11 downto 1), 14));
                s_seq <= to_unsigned(7, 5);
            elsif s_seq /= 0 and data_in.avid = '0' then
                -- SUGAR RUSH is now FIXED at 100% (fully candied) -- K3 was
                -- freed for SCALE -- so every ramp below sits at full travel.
                v_p := 1023;
                case to_integer(s_seq) is
                    when 7 =>
                        -- WARP weight (K5, SUGAR-RUSH-weighted). Kept to a plain
                        -- subtract+shift+min here; the shift-ladder is a SEPARATE
                        -- sequencer step (step 5) so neither cone is deep -- this
                        -- p12->s_wsh chain was the HD critical path.
                        if v_p < 150 then v_c := 0;
                        else v_c := (v_p - 150) / 8; end if;      -- >>3, 0..109
                        if v_c > to_integer(s_k5(9 downto 3)) then
                            v_c := to_integer(s_k5(9 downto 3));
                        end if;
                        s_wc <= to_unsigned(v_c, 7);
                    when 6 =>
                        -- GLOSS (K6) as a SHIFT level (mult-free pixel path),
                        -- gated on by SUGAR RUSH above ~30% travel.  Simple
                        -- slice+compare only -- no divide/min in this cone.
                        v_c := to_integer(s_k6(9 downto 7));      -- 0..7
                        if v_c > 5 then v_c := 5; end if;
                        if v_p < 300 then s_gsh <= 0;             -- matte
                        else               s_gsh <= v_c; end if;
                        s_gspec <= to_unsigned(300, 9) - resize(s_k6(9 downto 3), 9);
                    when 5 =>
                        -- WARP shift ladder (from the registered weight only).
                        if    s_wc < 4  then s_wsh <= 11;         -- off
                        elsif s_wc < 8  then s_wsh <= 8;
                        elsif s_wc < 16 then s_wsh <= 7;
                        elsif s_wc < 32 then s_wsh <= 6;
                        elsif s_wc < 56 then s_wsh <= 5;
                        elsif s_wc < 90 then s_wsh <= 4;
                        else                 s_wsh <= 3; end if;
                    when 4 =>
                        -- SPRINKLES density: fades in over the top ~half,
                        -- capped so garnish tops out "buried" (~30% of cells)
                        -- rather than covering the whole frame.
                        if v_p < 512 then v_c := 0;
                        else v_c := (v_p - 512) / 4; end if;      -- >>2, 0..127
                        if v_c > 48 then v_c := 48; end if;
                        s_sprk <= to_unsigned(v_c, 8);
                    when 3 =>
                        -- PALETTE (K4); BAKERY (S9) forces the Bakery ramp
                        if s_bakery = '1' then
                            s_paloff <= to_unsigned(24, 6);       -- Bakery
                        else
                            v_pal := to_integer(shift_right(s_k4 * 7, 10));
                            if v_pal > 6 then v_pal := 6; end if;
                            s_paloff <= to_unsigned(v_pal * 8, 6);
                        end if;
                    when 2 =>
                        -- TEXTURE (K1 rotates the class->texture map), DENSITY
                        -- (K2 = stripe pitch), SCALE (K3 = global texture size)
                        -- and the MAP STRENGTH (P12) for the mode S11 selects.
                        s_scl  <= to_integer(s_k3(9 downto 8));
                        -- stripe pitch: K2 trim + the global scale step
                        s_dgb  <= 6 - to_integer(s_k2(9 downto 8));
                        s_texoff <= s_k1(9 downto 7);
                        -- CHROMA strength: saturation floor sweeps 263 (only
                        -- vivid colour reads a hue) down to 8 (almost any tint
                        -- does).  Keeps a small floor so true grey never picks
                        -- a hue octant from noise.
                        s_sthr <= to_unsigned(8 + 255 - to_integer(s_p12(9 downto 2)), 10);
                        -- LUMA strength: how many varieties the ramp resolves.
                        if    s_p12 < 341 then s_ymask <= "100";   -- 2 candies
                        elsif s_p12 < 682 then s_ymask <= "110";   -- 4 candies
                        else                   s_ymask <= "111";   -- all 8
                        end if;
                    when 1 =>
                        -- SUGAR RUSH fixed at 100%: fully candied (no dry mix).
                        s_mix10 <= to_unsigned(1023, 10);
                    when others =>
                        null;
                end case;
                s_seq <= s_seq - 1;
            end if;
        end if;
    end process p_frame;

    ------------------------------------------------------------------------
    -- coordinate accumulators: dx = x - cx (per pixel), dy = y - cy
    -- (per active line; +2 on interlaced sources with a field offset).
    ------------------------------------------------------------------------
    p_acc : process(clk)
        variable v_dy0 : signed(13 downto 0);
    begin
        if rising_edge(clk) then
            s_avid_p <= data_in.avid;
            if s_vs_pulse = '1' then
                s_newframe <= '1';
            elsif data_in.avid = '1' and s_avid_p = '0' then
                if s_newframe = '1' then
                    if s_ilace = '1' and data_in.field_n = '1' then
                        v_dy0 := resize(-s_cy, 14) + 1;
                    else
                        v_dy0 := resize(-s_cy, 14);
                    end if;
                    s_dyc <= v_dy0;
                    if s_ilace = '1' then s_dyb <= v_dy0 + 2; else s_dyb <= v_dy0 + 1; end if;
                    s_newframe <= '0';
                else
                    s_dyc <= s_dyb;
                    if s_ilace = '1' then s_dyb <= s_dyb + 2; else s_dyb <= s_dyb + 1; end if;
                end if;
                s_dx <= resize(-s_cx, 14);
            elsif data_in.avid = '1' then
                s_dx <= s_dx + 1;
            end if;
        end if;
    end process p_acc;

    ------------------------------------------------------------------------
    -- COLOUR PATH + COMPOSE
    ------------------------------------------------------------------------
    p_pix : process(clk)
        variable v_dua, v_dva : unsigned(9 downto 0);  -- |U-512|, |V-512|
        variable v_dus, v_dvs : std_logic;
        variable v_oct : unsigned(3 downto 0);         -- hue octant (0..7)
        variable v_idxb : integer range 0 to 55;
        variable v_by, v_bu, v_bv : unsigned(9 downto 0);
        variable v_pjm  : unsigned(13 downto 0);   -- melt-sheared projection
        variable v_shp  : unsigned(13 downto 0);   -- shifted taffy phase
        variable v_hc2  : unsigned(15 downto 0);   -- cookie-chip hash
        variable v_ax4, v_ay4 : unsigned(3 downto 0);  -- folded in-cell dist
        variable v_cx, v_cy, v_aya : signed(5 downto 0);  -- chip-shape coords
        variable v_hc : unsigned(15 downto 0);
        variable v_sx3, v_sy3 : unsigned(2 downto 0);
        variable v_indot : boolean;
    begin
        if rising_edge(clk) then
            -- dry delay line
            s_y_sr(0) <= data_in.y;
            s_u_sr(0) <= data_in.u;
            s_v_sr(0) <= data_in.v;
            for i in 1 to 12 loop
                s_y_sr(i) <= s_y_sr(i - 1);
                s_u_sr(i) <= s_u_sr(i - 1);
                s_v_sr(i) <= s_v_sr(i - 1);
            end loop;

            -- E1: input + geometry snapshot.  HARDWARE U/V SWAP (reconfirmed
            -- on HW 2026-07-27: standard-authored cookie tan rendered blue):
            -- the hardware's u wire carries Cr, v carries Cb, so swap here --
            -- the classifier and all texture constants stay standard BT.601,
            -- and the wet output swaps back at compose.
            e1_y  <= unsigned(data_in.y);
            e1_u  <= unsigned(data_in.v);
            e1_v  <= unsigned(data_in.u);
            e1_dx <= s_dx;
            e1_dy <= s_dyc;

            -- E2: chroma split -- |du|, |dv|, saturation, hue-octant terms
            if e1_u >= 512 then v_dua := resize(e1_u - 512, 10); v_dus := '1';
            else                v_dua := resize(512 - e1_u, 10); v_dus := '0'; end if;
            if e1_v >= 512 then v_dva := resize(e1_v - 512, 10); v_dvs := '1';
            else                v_dva := resize(512 - e1_v, 10); v_dvs := '0'; end if;
            e2_sat <= v_dua + v_dva;
            e2_dus <= v_dus;
            e2_dvs <= v_dvs;
            if v_dua > v_dva then e2_cmp <= '1'; else e2_cmp <= '0'; end if;
            e2_yb  <= e1_y(9 downto 7);

            -- E3: CLASSIFY -- 1:1 picture -> candy texture.
            -- MAP switch (S11) picks WHICH property drives the map; STRENGTH
            -- (P12) sets how hard that property is read (see the vblank calc).
            if s_lumamap = '1' then
                -- LUMA: all 8 candies over brightness.  s_ymask quantises the
                -- ramp (STRENGTH): "111" = 8 varieties, "110" = 4, "100" = 2 --
                -- masking keeps them SPREAD across the bank, not clustered.
                case to_integer(e2_yb and s_ymask) is           -- dark -> light
                    when 0      => e3_tex <= to_unsigned(0, 3);  -- dark chocolate
                    when 1      => e3_tex <= to_unsigned(1, 3);  -- cookies & cream
                    when 2      => e3_tex <= to_unsigned(2, 3);  -- choc-chip cookie
                    when 3      => e3_tex <= to_unsigned(6, 3);  -- rainbow taffy
                    when 4      => e3_tex <= to_unsigned(4, 3);  -- mint
                    when 5      => e3_tex <= to_unsigned(3, 3);  -- candy cane
                    when 6      => e3_tex <= to_unsigned(5, 3);  -- piped icing
                    when others => e3_tex <= to_unsigned(7, 3);  -- frosting
                end case;
            elsif e2_sat < s_sthr then
                -- CHROMA, but this pixel is too grey to read a hue: fall back
                -- to luma (4 neutral confections).
                case to_integer(e2_yb(2 downto 1)) is
                    when 0      => e3_tex <= to_unsigned(0, 3);  -- dark chocolate
                    when 1      => e3_tex <= to_unsigned(1, 3);  -- cookies & cream
                    when 2      => e3_tex <= to_unsigned(5, 3);  -- piped icing
                    when others => e3_tex <= to_unsigned(7, 3);  -- frosting
                end case;
            else
                -- CHROMA: full HUE OCTANT -> a different candy per octant, so
                -- a colourful frame shows many varieties at once.  Octant =
                -- (Cr high, Cb high, |Cb| dominant).
                v_oct := unsigned'('0' & e2_dvs & e2_dus & e2_cmp);
                case to_integer(v_oct) is
                    when 0      => e3_tex <= to_unsigned(4, 3);  -- green: mint
                    when 1      => e3_tex <= to_unsigned(1, 3);  -- teal: cookies & cream
                    when 2      => e3_tex <= to_unsigned(7, 3);  -- cyan: frosting
                    when 3      => e3_tex <= to_unsigned(6, 3);  -- blue: rainbow taffy
                    when 4      => e3_tex <= to_unsigned(3, 3);  -- red: candy cane
                    when 5      => e3_tex <= to_unsigned(2, 3);  -- amber: choc-chip cookie
                    when 6      => e3_tex <= to_unsigned(5, 3);  -- pink: piped icing
                    when others => e3_tex <= to_unsigned(0, 3);  -- violet: dark chocolate
                end case;
            end if;

            -- E4: apply the K1 rotate
            t4_tex <= e3_tex + s_texoff;

            -- texture-index + gloss delay SRs to the pattern stage
            txd(0) <= t4_tex;
            for i in 1 to 5 loop
                txd(i) <= txd(i - 1);
            end loop;
            gadd_sr(0) <= g_add;
            for i in 1 to 5 loop
                gadd_sr(i) <= gadd_sr(i - 1);
            end loop;

            -- MP: pattern bits from the three projections (bit pick = pitch;
            -- no multiplies).  MELT (S10) shears the main diagonal by luma.
            v_pjm := w_proj_sr(5);
            if s_melt = '1' then
                v_pjm := v_pjm + resize(unsigned(s_y_sr(8)(9 downto 3)), 14);
            end if;
            mp_pj <= v_pjm;                            -- taffy stripe phase
            dg1   <= v_pjm(s_dgb);                     -- candy-cane stripes
            mg1   <= w_proj2_sr(5)(s_dgb);             -- mint stripes (other diag)
            -- groove / scallop flags: already scaled + aligned in p_geo
            grv1 <= grv_sr(4);
            ic1  <= ic_sr(4);
            v_hc2 := f_hash(cl_hx, cl_hy6 & "0000", x"C3B1");
            if cl_ix(3) = '1' then v_ax4 := unsigned('0' & cl_ix(2 downto 0));
            else                   v_ax4 := unsigned('0' & not cl_ix(2 downto 0)); end if;
            if cl_iy(3) = '1' then v_ay4 := unsigned('0' & cl_iy(2 downto 0));
            else                   v_ay4 := unsigned('0' & not cl_iy(2 downto 0)); end if;
            -- chip shape: triangle with a SIDEWAYS point and a rounded front
            -- (two slope cuts), mirrored + y-jittered per cell by hash bits
            v_cx := signed(resize(cl_ix, 6)) - 8;
            v_cy := signed(resize(cl_iy, 6)) - 8;
            if v_hc2(9) = '1' then v_cx := -v_cx; end if;      -- point left/right
            if v_hc2(10) = '1' then v_cy := v_cy + 2;          -- sit high/low
            else                    v_cy := v_cy - 1; end if;
            if v_cy < 0 then v_aya := -v_cy; else v_aya := v_cy; end if;
            if v_hc2(7 downto 0) < 96 and v_cx > -4 and v_aya < 4
               and (v_cx + shift_left(v_aya, 1)) < 7
               and (v_cx + v_aya) < 6 then
                chip1 <= '1';
            else
                chip1 <= '0';
            end if;
            -- cream dots (cookies & cream): REGULAR dot grid, every 16px cell
            if (v_ax4 + v_ay4) < 5 then dot1 <= '1'; else dot1 <= '0'; end if;

            -- GARNISH decision, computed HERE (MP has slack; keeps the hash
            -- out of the compose cone).  Registered into g_type / g_cv.
            -- y arg pre-shifted so f_hash's internal y(9:4) slice lands on the
            -- REAL cell bits (was y>>7 granularity = vertical column streaks)
            v_hc := f_hash(resize(s_xcnt(9 downto 3), 10),
                           s_lcnt(8 downto 3) & "0000", x"5A3C");
            v_sx3 := s_xcnt(2 downto 0);
            v_sy3 := s_lcnt(2 downto 0);
            if v_hc(12) = '0' then
                v_indot := (v_sy3 >= 3 and v_sy3 <= 4 and v_sx3 >= 1 and v_sx3 <= 6);
            else
                v_indot := (v_sx3 >= 3 and v_sx3 <= 4 and v_sy3 >= 1 and v_sy3 <= 6);
            end if;
            g_cv <= v_hc(14 downto 13);        -- jimmie colour, always captured
            if s_sprk /= 0 and v_hc(7 downto 0) < s_sprk and v_indot then
                g_type <= "01";
            elsif s_sprk /= 0 and v_hc(15 downto 9) < ('0' & s_sprk(7 downto 2))
                  and v_hc(3 downto 0) > 13
                  and v_sx3(2 downto 1) = "01" and v_sy3 = "011" then
                g_type <= "10";                -- sugar-dust GLINT (2x1 px, static)
            else
                g_type <= "00";
            end if;
            -- dense frosting confetti (only drawn inside the frosting texture)
            if s_sprk /= 0 and v_hc(7 downto 0) < (s_sprk(5 downto 0) & "00")
               and v_indot then
                g_d1 <= '1';
            else
                g_d1 <= '0';
            end if;

            -- PH1: taffy stripe colour -- palette ramp indexed by the diagonal
            -- stripe number (pitch follows K2 via s_dgb).  Plus side data.
            v_shp := shift_right(mp_pj, s_dgb);
            v_idxb := to_integer(s_paloff) + to_integer(v_shp(2 downto 0));
            ph_ry <= C_PAL_Y(v_idxb);
            ph_ru <= C_PAL_U(v_idxb);
            ph_rv <= C_PAL_V(v_idxb);
            ph_gadd <= gadd_sr(4);   -- one less (gloss gained an L4 stage)
            ph_gt <= g_type; ph_gc <= g_cv;
            -- pattern bits forward
            dg2   <= dg1;
            mg2   <= mg1;
            ic2   <= ic1;
            dot2  <= dot1;
            grv2  <= grv1;
            chip2 <= chip1;
            g_d2  <= g_d1;
            ph_tex <= txd(5);

            -- PH2: TEXTURE BANK -- each colour class's candy material, from
            -- the shared pattern bits (all constant-colour selects, no maths).
            co_useRing <= '0';
            co_gy      <= ph_gadd;                     -- gloss sheen
            ph_ry2 <= ph_ry; ph_ru2 <= ph_ru; ph_rv2 <= ph_rv;  -- align taffy
            case to_integer(ph_tex) is
                when 0 =>          -- DARK CHOCOLATE bar: cocoa + groove lines
                    if grv2 = '1' then
                        co_alt_y <= to_unsigned(105, 10);
                    else
                        co_alt_y <= to_unsigned(185, 10);
                    end if;
                    co_alt_u <= to_unsigned(462, 10); co_alt_v <= to_unsigned(566, 10);
                when 1 =>          -- COOKIES & CREAM: cream dot grid on black
                    if dot2 = '1' then
                        co_alt_y <= to_unsigned(965, 10);
                        co_alt_u <= to_unsigned(506, 10); co_alt_v <= to_unsigned(522, 10);
                    else
                        co_alt_y <= to_unsigned(85, 10);
                        co_alt_u <= to_unsigned(502, 10); co_alt_v <= to_unsigned(526, 10);
                    end if;
                when 2 =>          -- CHOC-CHIP COOKIE: tan dough + dark chips
                    if chip2 = '1' then
                        co_alt_y <= to_unsigned(170, 10);
                        co_alt_u <= to_unsigned(462, 10); co_alt_v <= to_unsigned(570, 10);
                    else
                        co_alt_y <= to_unsigned(600, 10);
                        co_alt_u <= to_unsigned(400, 10); co_alt_v <= to_unsigned(600, 10);
                    end if;
                when 3 =>          -- CANDY CANE: red / white diagonal stripes
                    if dg2 = '1' then
                        co_alt_y <= to_unsigned(360, 10);
                        co_alt_u <= to_unsigned(425, 10); co_alt_v <= to_unsigned(865, 10);
                    else
                        co_alt_y <= C_WHITE_Y;
                        co_alt_u <= to_unsigned(512, 10); co_alt_v <= to_unsigned(512, 10);
                    end if;
                when 4 =>          -- MINT: spearmint / white stripes (other diag)
                    if mg2 = '1' then
                        co_alt_y <= to_unsigned(690, 10);
                        co_alt_u <= to_unsigned(420, 10); co_alt_v <= to_unsigned(350, 10);
                    else
                        co_alt_y <= C_WHITE_Y;
                        co_alt_u <= to_unsigned(512, 10); co_alt_v <= to_unsigned(512, 10);
                    end if;
                when 5 =>          -- PIPED ICING: pink scallop piping on white
                    if ic2 = '1' then
                        co_alt_y <= to_unsigned(720, 10);
                        co_alt_u <= to_unsigned(560, 10); co_alt_v <= to_unsigned(650, 10);
                    else
                        co_alt_y <= to_unsigned(980, 10);
                        co_alt_u <= to_unsigned(508, 10); co_alt_v <= to_unsigned(518, 10);
                    end if;
                when 6 =>          -- RAINBOW TAFFY: palette-ramp diagonal stripes
                    co_useRing <= '1';
                    co_alt_y <= C_WHITE_Y;
                    co_alt_u <= to_unsigned(512, 10); co_alt_v <= to_unsigned(512, 10);
                when others =>     -- FROSTING: white + dense rainbow confetti
                    if g_d2 = '1' then
                        case ph_gc is
                            when "00"   => co_alt_y <= to_unsigned(560,10); co_alt_u <= to_unsigned(700,10); co_alt_v <= to_unsigned(760,10);
                            when "01"   => co_alt_y <= to_unsigned(720,10); co_alt_u <= to_unsigned(680,10); co_alt_v <= to_unsigned(300,10);
                            when "10"   => co_alt_y <= to_unsigned(760,10); co_alt_u <= to_unsigned(300,10); co_alt_v <= to_unsigned(560,10);
                            when others => co_alt_y <= to_unsigned(700,10); co_alt_u <= to_unsigned(360,10); co_alt_v <= to_unsigned(400,10);
                        end case;
                    else
                        co_alt_y <= to_unsigned(1010, 10);
                        co_alt_u <= to_unsigned(512, 10); co_alt_v <= to_unsigned(512, 10);
                    end if;
            end case;

            -- GARNISH override (constants).  Last assignment wins, so this
            -- supersedes the tone above.  Jimmies only land on the SMOOTH
            -- bright surfaces (icing 5, frosting 7) -- stripes stay clean.
            if ph_gt = "01" and ph_tex(2) = '1' and ph_tex(0) = '1' then -- jimmie
                case ph_gc is
                    when "00"   => co_alt_y <= to_unsigned(560,10); co_alt_u <= to_unsigned(700,10); co_alt_v <= to_unsigned(760,10);
                    when "01"   => co_alt_y <= to_unsigned(720,10); co_alt_u <= to_unsigned(680,10); co_alt_v <= to_unsigned(300,10);
                    when "10"   => co_alt_y <= to_unsigned(760,10); co_alt_u <= to_unsigned(300,10); co_alt_v <= to_unsigned(560,10);
                    when others => co_alt_y <= to_unsigned(700,10); co_alt_u <= to_unsigned(360,10); co_alt_v <= to_unsigned(400,10);
                end case;
                co_useRing <= '0'; co_gy <= to_signed(120, 11);
            elsif ph_gt = "10" then                        -- sugar dust
                co_alt_y <= C_WHITE_Y; co_alt_u <= to_unsigned(512, 10);
                co_alt_v <= to_unsigned(512, 10);
                co_useRing <= '0'; co_gy <= (others => '0');
            end if;

            -- CO: output cone is now just a 2:1 ring mux + gloss add + clamp.
            if co_useRing = '1' then
                v_by := ph_ry2; v_bu := ph_ru2; v_bv := ph_rv2;
            else
                v_by := co_alt_y; v_bu := co_alt_u; v_bv := co_alt_v;
            end if;
            wcy <= f_cu10(signed(resize(v_by, 12)) + resize(co_gy, 12));
            wcu <= v_bv;               -- U/V swap back out for hardware
            wcv <= v_bu;
        end if;
    end process p_pix;

    ------------------------------------------------------------------------
    -- GEOMETRY: static warp bend -> three stripe projections.  No generated
    -- shapes -- these only define the LOCAL grain of each candy texture.
    ------------------------------------------------------------------------
    p_geo : process(clk)
        variable v_pj, v_pj2, v_pj3 : signed(14 downto 0);
        variable v_ax, v_ay : unsigned(9 downto 0);
    begin
        if rising_edge(clk) then
            -- W1: STATIC cross-axis triangle bend (WARP, K5).  Each axis is
            -- pushed by a triangle of the OTHER axis so stripes wave instead
            -- of staying ruler-straight.  No drift -- the bend never moves.
            v_ax := unsigned(std_logic_vector(e1_dy(7 downto 0))) & "00";
            v_ay := unsigned(std_logic_vector(e1_dx(7 downto 0))) & "00";
            -- shift instead of multiply (HX4K has no DSP): displacement is
            -- tri >> s_wsh, +/-63px at s_wsh=3 down to 0 at s_wsh>=10.
            w1_ox <= resize(shift_right(f_tri(v_ax), s_wsh), 14);
            w1_oy <= resize(shift_right(f_tri(v_ay), s_wsh), 14);
            w1_dx <= e1_dx;
            w1_dy <= e1_dy;

            -- W2: apply displacement
            w2_dx <= w1_dx + w1_ox;
            w2_dy <= w1_dy + w1_oy;

            -- stripe projections: both 45-deg diagonals + a wavy horizontal
            -- (dy + tri(dx) = icing scallops); low 12 bits are periodic.
            v_pj  := resize(w2_dx, 15) + resize(w2_dy, 15);
            v_pj2 := resize(w2_dx, 15) - resize(w2_dy, 15);
            v_pj3 := resize(w2_dy, 15)
                     + resize(shift_right(f_tri(unsigned(std_logic_vector(w2_dx(9 downto 0)))), 3), 15);
            -- SCALE applied ONCE, here: every consumer downstream then uses
            -- its original narrow slice/shift (widening those muxes instead
            -- cost ~5 MHz on HD).  Coarser scale = shift the pitch up.
            w_proj_sr(0)  <= shift_right(unsigned(std_logic_vector(v_pj(13 downto 0))), s_scl);
            w_proj2_sr(0) <= shift_right(unsigned(std_logic_vector(v_pj2(13 downto 0))), s_scl);
            w_proj3_sr(0) <= shift_right(unsigned(std_logic_vector(v_pj3(13 downto 0))), s_scl);
            for i in 1 to 5 loop
                w_proj_sr(i)  <= w_proj_sr(i - 1);
                w_proj2_sr(i) <= w_proj2_sr(i - 1);
                w_proj3_sr(i) <= w_proj3_sr(i - 1);
            end loop;

            -- SCALE windows, computed HERE (geometry has slack) from the
            -- already-registered projection so the barrel shift is off the MP
            -- critical path.  Sliding the window up = coarser texture;
            -- s_scl=1 reproduces the original pitches.
            -- chocolate-bar segment grooves: thin lines on BOTH diagonals
            if w_proj_sr(0)(4 downto 0) = "00000"
               or w_proj2_sr(0)(4 downto 0) = "00000" then
                grv_sr(0) <= '1';
            else grv_sr(0) <= '0'; end if;
            -- icing scallop piping: thin wavy bands
            if w_proj3_sr(0)(3 downto 2) = "11" then ic_sr(0) <= '1';
            else ic_sr(0) <= '0'; end if;
            -- flags align with w_proj_sr(1..5): read index 4 at the MP stage
            for i in 1 to 4 loop
                grv_sr(i) <= grv_sr(i - 1);
                ic_sr(i)  <= ic_sr(i - 1);
            end loop;

            -- chip/dot CELL SIZE from SCALE: 8/16/32/64 px.  cl_ix/cl_iy are
            -- the in-cell position normalised to 0..15 so one shape rule
            -- serves every size; cl_hx/cl_hy6 are the cell coords for the hash
            -- (y pre-placed into bits 9:4 -- see the f_hash granularity trap).
            case s_scl is
                when 0 =>
                    cl_ix <= s_xcnt(2 downto 0) & '0'; cl_iy <= s_lcnt(2 downto 0) & '0';
                    cl_hx <= resize(s_xcnt(9 downto 3), 10); cl_hy6 <= resize(s_lcnt(8 downto 3), 6);
                when 1 =>
                    cl_ix <= s_xcnt(3 downto 0); cl_iy <= s_lcnt(3 downto 0);
                    cl_hx <= resize(s_xcnt(10 downto 4), 10); cl_hy6 <= resize(s_lcnt(9 downto 4), 6);
                when 2 =>
                    cl_ix <= s_xcnt(4 downto 1); cl_iy <= s_lcnt(4 downto 1);
                    cl_hx <= resize(s_xcnt(10 downto 5), 10); cl_hy6 <= resize(s_lcnt(10 downto 5), 6);
                when others =>
                    cl_ix <= s_xcnt(5 downto 2); cl_iy <= s_lcnt(5 downto 2);
                    cl_hx <= resize(s_xcnt(10 downto 6), 10); cl_hy6 <= resize(s_lcnt(10 downto 6), 6);
            end case;
        end if;
    end process p_geo;

    ------------------------------------------------------------------------
    -- GLOSS: line-RAM luma heightfield -> emboss -> specular sheen (g_add).
    -- Produced ~4 stages in, delayed to meet the compose stage.
    ------------------------------------------------------------------------
    p_gloss : process(clk)
        variable v_a : signed(13 downto 0);
        variable v_lit : signed(11 downto 0);
        variable v_sh : signed(13 downto 0);
    begin
        if rising_edge(clk) then
            -- L0: line RAM (read previous line, then write current), luma taps
            if data_in.avid = '1' then
                lb_rd <= lram(to_integer(s_xcnt(10 downto 0)));
                lram(to_integer(s_xcnt(10 downto 0))) <= data_in.y;
            end if;
            gpl   <= unsigned(data_in.y);
            gpl_d <= gpl;

            -- L1: gradients (gpl=P, gpl_d=P-1 horizontal, lb_rd=P one line up)
            ggx <= signed('0' & gpl) - signed('0' & gpl_d);
            ggy <= signed('0' & gpl) - signed('0' & lb_rd);

            -- L2: lit = gx+gy -> shoulder rising toward the upper-left light.
            -- Also decide the specular threshold HERE (parallel), so L3 is a
            -- shift + one add + one clamp -- shorter cone (HD timing).
            v_lit := resize(ggx, 12) + resize(ggy, 12);
            if v_lit > signed('0' & s_gspec) then spec_hi <= '1';
            else                                  spec_hi <= '0'; end if;
            -- bound glit here (parallel, has slack) so L3 needs no clamp
            -- before its shift -- keeps the L3 cone short.
            if    v_lit >  255 then glit <= to_signed(255, 12);
            elsif v_lit < -255 then glit <= to_signed(-255, 12);
            else                    glit <= v_lit; end if;

            -- L3: sheen SHIFT only (no multiply).  gsh=0 -> matte; else
            -- glit << (gsh-1).  The spec add + clamp are split into L4 so this
            -- barrel-shift cone stays short (was the HD HDMI critical path).
            if s_gsh = 0 then
                v_sh := (others => '0');                       -- matte
            else
                v_sh := shift_left(resize(glit, 14), s_gsh - 1); -- glit<=+-255
            end if;
            g_sh    <= v_sh;
            spec_hi2 <= spec_hi;                              -- carry to L4

            -- L4: blown-crescent add + clamp (separate cycle from the shift).
            v_a := g_sh;
            if spec_hi2 = '1' then v_a := v_a + 360; end if;
            if v_a > 511 then v_a := to_signed(511, 14);
            elsif v_a < -300 then v_a := to_signed(-300, 14); end if;
            g_add <= resize(v_a, 11);
        end if;
    end process p_gloss;

    ------------------------------------------------------------------------
    -- SUGAR RUSH dry/wet mix (inline, 3 clocks). Wet compose depth = 9,
    -- so the dry tap is s_y_sr(8) (data_in delayed 9).
    ------------------------------------------------------------------------
    p_mix : process(clk)
        variable v_s : signed(12 downto 0);
    begin
        if rising_edge(clk) then
            m1_ay <= unsigned(s_y_sr(12));
            m1_au <= unsigned(s_u_sr(12));
            m1_av <= unsigned(s_v_sr(12));
            m1_dy <= signed(resize(wcy, 11)) - signed(resize(unsigned(s_y_sr(12)), 11));
            m1_du <= signed(resize(wcu, 11)) - signed(resize(unsigned(s_u_sr(12)), 11));
            m1_dv <= signed(resize(wcv, 11)) - signed(resize(unsigned(s_v_sr(12)), 11));

            -- 6-bit blend t (mix10>>4) instead of 8-bit -> smaller LUT mults;
            -- result = a + (t * diff) >> 6.  Error <= diff/64, invisible.
            m2_py <= resize(signed('0' & s_mix10(9 downto 4)) * m1_dy, 20);  -- 7b*11b
            m2_pu <= resize(signed('0' & s_mix10(9 downto 4)) * m1_du, 20);
            m2_pv <= resize(signed('0' & s_mix10(9 downto 4)) * m1_dv, 20);
            m2_ay <= m1_ay; m2_au <= m1_au; m2_av <= m1_av;

            v_s := signed(resize(m2_ay, 13)) + resize(shift_right(m2_py, 6), 13);
            m3_y <= f_cu10(v_s);
            v_s := signed(resize(m2_au, 13)) + resize(shift_right(m2_pu, 6), 13);
            m3_u <= f_cu10(v_s);
            v_s := signed(resize(m2_av, 13)) + resize(shift_right(m2_pv, 6), 13);
            m3_v <= f_cu10(v_s);
        end if;
    end process p_mix;

    ------------------------------------------------------------------------
    -- sync delay + output
    ------------------------------------------------------------------------
    p_sync : process(clk)
    begin
        if rising_edge(clk) then
            s_avid_sr    <= data_in.avid    & s_avid_sr   (0 to C_LATENCY - 2);
            s_hsync_n_sr <= data_in.hsync_n & s_hsync_n_sr(0 to C_LATENCY - 2);
            s_vsync_n_sr <= data_in.vsync_n & s_vsync_n_sr(0 to C_LATENCY - 2);
            s_field_n_sr <= data_in.field_n & s_field_n_sr(0 to C_LATENCY - 2);
        end if;
    end process p_sync;

    data_out.y       <= std_logic_vector(m3_y);
    data_out.u       <= std_logic_vector(m3_u);
    data_out.v       <= std_logic_vector(m3_v);
    data_out.avid    <= s_avid_sr(C_LATENCY - 1);
    data_out.hsync_n <= s_hsync_n_sr(C_LATENCY - 1);
    data_out.vsync_n <= s_vsync_n_sr(C_LATENCY - 1);
    data_out.field_n <= s_field_n_sr(C_LATENCY - 1);

end architecture sugarcoat;
