-- wavekey: Wave Key
-- Horizontal and vertical LFO-driven sine colour fields keyed by the input luma. P12 sets the LFO speed.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/wavekey.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   k1         control       1 ->   2
--   k2         control       1 ->   2
--   k3         control       1 ->   2
--   k4         control       1 ->   2
--   key        threshold     1 ->   4
--   p12        control       1 ->   2
--   s7         control       1 ->   2
--   s8         control       1 ->   2
--   speed      glide         1 ->   2
--   lfoa       lfo           1 ->   3
--   hramp      hramp         1 ->   2
--   hosc       osc           2 ->   5
--   hcol       colorizer     5 ->   7
--   lfob       lfo           1 ->   3  (sine ROM in one EBR)
--   vcnt       vcount        1 ->   2  (line index; the top 10 bits drive the vertical oscillator)
--   vosc       osc           0 ->   3
--   vcol       colorizer     4 ->   6
--   mix        mix           7 ->  11  (pixel-rate amount: the luma key)
--   vout       video_out    11 ->  12
-- Program latency: 12 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   key.out          34-bit, delayed by 1 clocks (34 FF)
--   vosc.wave        10-bit, delayed by 1 clocks (10 FF)
--   vcol.out         34-bit, delayed by 1 clocks (34 FF)
--   key.mask         10-bit, delayed by 3 clocks (30 FF)
-- Chroma of vin, key is never consumed downstream; synthesis removes it.
-- Controls:
--   K1   registers_in(0)     H Freq
--   K2   registers_in(1)     V Freq
--   K3   registers_in(2)     Key Level
--   K4   registers_in(3)     Key Soft
--   P12  registers_in(7)     Speed
--   S7   registers_in(6)(0)  LFO A
--   S8   registers_in(6)(1)  LFO B
-- Estimate: 2964 LC (38.6 %), 4 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture wavekey of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_k1_value             : unsigned(10 - 1 downto 0);
  signal s_k2_value             : unsigned(10 - 1 downto 0);
  signal s_k3_value             : unsigned(10 - 1 downto 0);
  signal s_k4_value             : unsigned(10 - 1 downto 0);
  signal s_key_out              : t_vm_stream;
  signal s_key_mask             : unsigned(10 - 1 downto 0);
  signal s_p12_value            : unsigned(10 - 1 downto 0);
  signal s_s7_value             : unsigned(10 - 1 downto 0);
  signal s_s8_value             : unsigned(10 - 1 downto 0);
  signal s_speed_value          : unsigned(10 - 1 downto 0);
  signal s_lfoa_value           : unsigned(10 - 1 downto 0);
  signal s_hramp_ramp           : unsigned(10 - 1 downto 0);
  signal s_hosc_wave            : unsigned(10 - 1 downto 0);
  signal s_hcol_out             : t_vm_stream;
  signal s_lfob_value           : unsigned(10 - 1 downto 0);
  signal s_vcnt_v               : unsigned(11 - 1 downto 0);
  signal s_vosc_wave            : unsigned(10 - 1 downto 0);
  signal s_vcol_out             : t_vm_stream;
  signal s_mix_out              : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_key_out_d1           : t_vm_stream;
  signal s_vosc_wave_d1         : unsigned(10 - 1 downto 0);
  signal s_vcol_out_d1          : t_vm_stream;
  signal s_key_mask_d3          : unsigned(10 - 1 downto 0);
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- k1 (K1: H Freq)
  u_k1 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0), o_value => s_k1_value);

  -- k2 (K2: V Freq)
  u_k2 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1), o_value => s_k2_value);

  -- k3 (K3: Key Level)
  u_k3 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2), o_value => s_k3_value);

  -- k4 (K4: Key Soft)
  u_k4 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3), o_value => s_k4_value);

  -- key (Threshold)
  u_key : entity work.vm_threshold
    generic map (G_CHANNEL => 0, G_SOFT => true)
    port map (clk => clk, i_stream => s_vin_out, i_level => s_k3_value, i_soft => s_k4_value,
              o_stream => s_key_out, o_mask => s_key_mask);

  -- p12 (P12: Speed)
  u_p12 : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(7),
              o_value => s_p12_value);

  -- s7 (S7: LFO A)
  u_s7 : entity work.vm_control
    generic map (G_BIT => 0, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6), o_value => s_s7_value);

  -- s8 (S8: LFO B)
  u_s8 : entity work.vm_control
    generic map (G_BIT => 1, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6), o_value => s_s8_value);

  -- speed (Glide)
  u_speed : entity work.vm_glide
    generic map (G_SHIFT => 4)
    port map (clk => clk, i_stream => s_vin_out, i_target => s_p12_value,
              o_value => s_speed_value);

  -- lfoa (LFO)
  u_lfoa : entity work.vm_lfo
    generic map (G_PHASE_BITS => 16, G_ROM_STYLE => "logic")
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_speed_value,
              i_shape => s_s7_value(9 downto 8), o_value => s_lfoa_value);

  -- hramp (H Ramp)
  u_hramp : entity work.vm_hramp
    generic map (G_FRAC => 8, G_WRAP => true)
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_k1_value, i_offset => s_lfoa_value,
              o_ramp => s_hramp_ramp);

  -- hosc (Oscillator)
  u_hosc : entity work.vm_osc
    generic map (G_ADDR_BITS => 7, G_FREQ_SHIFT => 0, G_ROM_STYLE => "logic")
    port map (clk => clk, i_theta => s_hramp_ramp, i_phase => to_unsigned(0, 10),
              o_wave => s_hosc_wave);
  u_dly_key_out_1 : entity work.vm_delay_stream generic map (G_DELAY => 1)
    port map (clk => clk, i_stream => s_key_out, o_stream => s_key_out_d1);

  -- hcol (Colorizer)
  u_hcol : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 4,
                 G_PALETTE => "0402002000922682440f52942bc12f20d35117914b39a2140f232a2ae0992b93480402492e90a918e29f16c0c525f25b0741d830e0d615835817316931b2272aa29523c3ac200200")
    port map (clk => clk, i_stream => s_key_out_d1, i_index => s_hosc_wave,
              o_stream => s_hcol_out);

  -- lfob (LFO): sine ROM in one EBR
  u_lfob : entity work.vm_lfo
    generic map (G_PHASE_BITS => 16, G_ROM_STYLE => "auto")
    port map (clk => clk, i_stream => s_vin_out, i_rate => s_speed_value,
              i_shape => s_s8_value(9 downto 8), o_value => s_lfob_value);

  -- vcnt (V Counter): line index; the top 10 bits drive the vertical oscillator
  u_vcnt : entity work.vm_vcount
    generic map (G_WIDTH => 11)
    port map (clk => clk, i_stream => s_vin_out, o_v => s_vcnt_v);

  -- vosc (Oscillator)
  u_vosc : entity work.vm_osc
    generic map (G_ADDR_BITS => 10, G_FREQ_SHIFT => 2, G_ROM_STYLE => "auto")
    port map (clk => clk, i_theta => s_vcnt_v(10 downto 1), i_phase => s_lfob_value,
              o_wave => s_vosc_wave);
  u_dly_vosc_wave_1 : entity work.vm_delay_scalar generic map (G_WIDTH => 10, G_DELAY => 1)
    port map (clk => clk, i_value => s_vosc_wave, o_value => s_vosc_wave_d1);

  -- vcol (Colorizer)
  u_vcol : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 3,
                 G_PALETTE => "0402002000722e01dc0ff2c12b41361a538c2470d430431505e26e30522e0fa3ac200200")
    port map (clk => clk, i_stream => s_key_out, i_index => s_vosc_wave_d1,
              o_stream => s_vcol_out);
  u_dly_vcol_out_1 : entity work.vm_delay_stream generic map (G_DELAY => 1)
    port map (clk => clk, i_stream => s_vcol_out, o_stream => s_vcol_out_d1);
  u_dly_key_mask_3 : entity work.vm_delay_scalar generic map (G_WIDTH => 10, G_DELAY => 3)
    port map (clk => clk, i_value => s_key_mask, o_value => s_key_mask_d3);

  -- mix (Mix): pixel-rate amount: the luma key
  u_mix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 5)
    port map (clk => clk, i_a => s_hcol_out, i_b => s_vcol_out_d1, i_amount => s_key_mask_d3,
              o_stream => s_mix_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_mix_out, o_data => data_out);
end architecture wavekey;
