-- glass_ember: Glass Ember
-- H blur, proc amp, keyed on U, concentric rings, 8-colour palette, LFO crossfades them, colour fringing.
--
-- GENERATED by vm-nodes/tools/generate.ts from graphs/glass_ember.json. Readable by design:
-- edit freely, but regenerate rather than merge if the graph changes.
--
-- Nodes (topological order), start clock -> output clock after data_in:
--   vin        video_in      0 ->   1
--   ctl_bright control       1 ->   2
--   ctl_centre_x control       1 ->   2
--   ctl_contrast control       1 ->   2
--   ctl_key_level control       1 ->   2
--   ctl_key_soft control       1 ->   2
--   ctl_saturation control       1 ->   2
--   hb         hblur         1 ->   7
--   pa         procamp       7 ->  12
--   key        threshold    12 ->  15
--   rx         hramp         1 ->   2
--   ry         vramp         1 ->   2
--   rad        radial        2 ->   4
--   osc        osc           4 ->   7
--   pal        colorizer    12 ->  14
--   sw_lfo_shape control       1 ->   2
--   lfo        lfo           1 ->   3
--   mix        mix          14 ->  18
--   fringe     chroma_shift  18 ->  19
--   vout       video_out    19 ->  20
-- Program latency: 20 clocks, identical in every video mode.
-- Delay matching (inserted on the earlier branch of each join):
--   osc.wave         10-bit, delayed by 5 clocks (50 FF)
--   pa.out           34-bit, delayed by 2 clocks (68 FF)
-- Chroma of key is never consumed downstream; synthesis removes it.
-- Controls:
--   K1   registers_in(0)     Bright
--   K6   registers_in(5)     Centre X
--   K2   registers_in(1)     Contrast
--   K4   registers_in(3)     Key Level
--   K5   registers_in(4)     Key Soft
--   K3   registers_in(2)     Saturation
--   S7   registers_in(6)(0)  LFO Shape
-- Estimate: 4274 LC (55.7 %), 0 EBR, zone green.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.video_timing_pkg.all;
use work.video_stream_pkg.all;
use work.core_pkg.all;
use work.vm_nodes_pkg.all;

architecture glass_ember of program_top is
  signal s_vin_out              : t_vm_stream;
  signal s_vin_y                : unsigned(10 - 1 downto 0);
  signal s_vin_u                : unsigned(10 - 1 downto 0);
  signal s_vin_v                : unsigned(10 - 1 downto 0);
  signal s_ctl_bright_value     : unsigned(10 - 1 downto 0);
  signal s_ctl_centre_x_value   : unsigned(10 - 1 downto 0);
  signal s_ctl_contrast_value   : unsigned(10 - 1 downto 0);
  signal s_ctl_key_level_value  : unsigned(10 - 1 downto 0);
  signal s_ctl_key_soft_value   : unsigned(10 - 1 downto 0);
  signal s_ctl_saturation_value : unsigned(10 - 1 downto 0);
  signal s_hb_out               : t_vm_stream;
  signal s_pa_out               : t_vm_stream;
  signal s_key_out              : t_vm_stream;
  signal s_key_mask             : unsigned(10 - 1 downto 0);
  signal s_rx_ramp              : unsigned(10 - 1 downto 0);
  signal s_ry_ramp              : unsigned(10 - 1 downto 0);
  signal s_rad_r                : unsigned(10 - 1 downto 0);
  signal s_osc_wave             : unsigned(10 - 1 downto 0);
  signal s_pal_out              : t_vm_stream;
  signal s_sw_lfo_shape_value   : unsigned(10 - 1 downto 0);
  signal s_lfo_value            : unsigned(10 - 1 downto 0);
  signal s_mix_out              : t_vm_stream;
  signal s_fringe_out           : t_vm_stream;
  signal s_vout_out             : t_vm_stream;
  -- delay-matching taps
  signal s_osc_wave_d5          : unsigned(10 - 1 downto 0);
  signal s_pa_out_d2            : t_vm_stream;
begin

  -- vin (Video In)
  u_vin : entity work.vm_video_in
    port map (clk => clk, i_data => data_in, o_stream => s_vin_out, o_y => s_vin_y,
              o_u => s_vin_u, o_v => s_vin_v);

  -- ctl_bright (K1: Bright)
  u_ctl_bright : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(0),
              o_value => s_ctl_bright_value);

  -- ctl_centre_x (K6: Centre X)
  u_ctl_centre_x : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(5),
              o_value => s_ctl_centre_x_value);

  -- ctl_contrast (K2: Contrast)
  u_ctl_contrast : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(1),
              o_value => s_ctl_contrast_value);

  -- ctl_key_level (K4: Key Level)
  u_ctl_key_level : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(3),
              o_value => s_ctl_key_level_value);

  -- ctl_key_soft (K5: Key Soft)
  u_ctl_key_soft : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(4),
              o_value => s_ctl_key_soft_value);

  -- ctl_saturation (K3: Saturation)
  u_ctl_saturation : entity work.vm_control
    generic map (G_BIT => -1, G_LATCH => false)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(2),
              o_value => s_ctl_saturation_value);

  -- hb (H Blur)
  u_hb : entity work.vm_hblur
    generic map (G_TAPS => 3, G_CHROMA => false)
    port map (clk => clk, i_stream => s_vin_out, o_stream => s_hb_out);

  -- pa (Proc Amp)
  u_pa : entity work.vm_procamp
    generic map (G_IMPL => "shift", G_BITS => 6)
    port map (clk => clk, i_stream => s_hb_out, i_bright => s_ctl_bright_value,
              i_contrast => s_ctl_contrast_value, i_sat => s_ctl_saturation_value,
              o_stream => s_pa_out);

  -- key (Threshold)
  u_key : entity work.vm_threshold
    generic map (G_CHANNEL => 1, G_SOFT => true)
    port map (clk => clk, i_stream => s_pa_out, i_level => s_ctl_key_level_value,
              i_soft => s_ctl_key_soft_value, o_stream => s_key_out, o_mask => s_key_mask);

  -- rx (H Ramp)
  u_rx : entity work.vm_hramp
    generic map (G_FRAC => 6, G_WRAP => false)
    port map (clk => clk, i_stream => s_vin_out, i_rate => to_unsigned(52, 10),
              i_offset => to_unsigned(0, 10), o_ramp => s_rx_ramp);

  -- ry (V Ramp)
  u_ry : entity work.vm_vramp
    generic map (G_FRAC => 4, G_WRAP => false)
    port map (clk => clk, i_stream => s_vin_out, i_rate => to_unsigned(13, 10),
              i_offset => to_unsigned(0, 10), o_ramp => s_ry_ramp);

  -- rad (Radial)
  u_rad : entity work.vm_radial
    generic map (G_METRIC => "octagon", G_SCALE => 1)
    port map (clk => clk, i_x => s_rx_ramp, i_y => s_ry_ramp, i_cx => s_ctl_centre_x_value,
              i_cy => to_unsigned(512, 10), o_r => s_rad_r);

  -- osc (Oscillator)
  u_osc : entity work.vm_osc
    generic map (G_ADDR_BITS => 8, G_FREQ_SHIFT => 1, G_ROM_STYLE => "logic")
    port map (clk => clk, i_theta => s_rad_r, i_phase => to_unsigned(578, 10),
              o_wave => s_osc_wave);
  u_dly_osc_wave_5 : entity work.vm_delay_scalar generic map (G_WIDTH => 10, G_DELAY => 5)
    port map (clk => clk, i_value => s_osc_wave, o_value => s_osc_wave_d5);

  -- pal (Colorizer)
  u_pal : entity work.vm_colorizer
    generic map (G_ENTRIES_BITS => 3,
                 G_PALETTE => "0cf1d02371541922001611991891bc20d14e18e2961821612e62231fa2a92f81f71be33f")
    port map (clk => clk, i_stream => s_pa_out, i_index => s_osc_wave_d5, o_stream => s_pal_out);

  -- sw_lfo_shape (S7: LFO Shape)
  u_sw_lfo_shape : entity work.vm_control
    generic map (G_BIT => 0, G_LATCH => true)
    port map (clk => clk, i_stream => s_vin_out, i_reg => registers_in(6),
              o_value => s_sw_lfo_shape_value);

  -- lfo (LFO)
  u_lfo : entity work.vm_lfo
    generic map (G_PHASE_BITS => 16, G_ROM_STYLE => "logic")
    port map (clk => clk, i_stream => s_vin_out, i_rate => to_unsigned(35, 10),
              i_shape => s_sw_lfo_shape_value(9 downto 8), o_value => s_lfo_value);
  u_dly_pa_out_2 : entity work.vm_delay_stream generic map (G_DELAY => 2)
    port map (clk => clk, i_stream => s_pa_out, o_stream => s_pa_out_d2);

  -- mix (Mix)
  u_mix : entity work.vm_mix
    generic map (G_IMPL => "shift", G_BITS => 4)
    port map (clk => clk, i_a => s_pa_out_d2, i_b => s_pal_out, i_amount => s_lfo_value,
              o_stream => s_mix_out);

  -- fringe (Chroma Shift)
  u_fringe : entity work.vm_chroma_shift
    generic map (G_PIXELS => 8, G_LEAD => "luma")
    port map (clk => clk, i_stream => s_mix_out, o_stream => s_fringe_out);

  -- vout (Video Out)
  u_vout : entity work.vm_video_out
    port map (clk => clk, i_stream => s_fringe_out, o_data => data_out);
end architecture glass_ember;
